<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unrestricted</name>
   <tag></tag>
   <elementGuidId>3a53f93a-442a-4c83-a1b1-66c8e3552a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.restrict-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Request']/div/div/form/div[2]/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dab0ff76-76f4-4e00-a4c9-0e8d025920a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>restrict-select</value>
      <webElementGuid>2d4880ff-cd43-42e1-8f69-d0b2da180b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unrestricted​</value>
      <webElementGuid>ee1eefe1-42b6-4047-9d03-b1f910425185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Request&quot;)/div[@class=&quot;container foi-review-request-container&quot;]/div[@class=&quot;foi-review-container&quot;]/form[@class=&quot;jss11 foi-request-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;foi-request-review-header-col1-row&quot;]/div[@class=&quot;requestRestriction&quot;]/div[@class=&quot;restrict-dropdown-all&quot;]/div[@class=&quot;restrict-select&quot;]</value>
      <webElementGuid>77af542f-d46c-487e-a4e7-2766937d8158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>4023e0e2-02ba-46cb-9e77-15362d1cd230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag'])[1]/following::div[4]</value>
      <webElementGuid>3d4ab0a5-854f-4336-baac-192411fd4478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watchers'])[1]/following::div[6]</value>
      <webElementGuid>c7f54566-b293-4713-8940-8be7107e94d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>5625058e-1338-49cf-91d1-38d46c951963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Unrestricted​' or . = 'Unrestricted​')]</value>
      <webElementGuid>e780e75b-55b8-4d8f-825d-870a582654e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
