apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
objects:
  - apiVersion: v1
    data:
      mail-config.properties: |
        # send mails via SMTP
        mail.transport.protocol=smtp
        mail.smtp.host=${SMTP_SERVER}
        mail.smtp.port=25
        mail.smtp.auth=false
        mail.smtp.ssl.enable=false
        #mail.smtp.socketFactory.port=465
        #mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
        # poll mails via IMAPS
        #mail.store.protocol=imaps
        # mail.imaps.host=imap.gmail.com
        #mail.imaps.port=993
        #mail.imaps.timeout=10000
        # additional config
        #mail.poll.folder=INBOX
        mail.sender=${SMTP_MAIL_SENDER}
        mail.sender.alias=DoNotReply
        mail.attachment.download=true
        mail.attachment.path=attachments
        # credentials
        mail.user=
        mail.password=
    kind: ConfigMap
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}-mail-config

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      host: ${CAMUNDA_URL}
      path: /camunda
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
      wildcardPolicy: None

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      ports:
        - name: web
          port: 8080
          targetPort: 8080
      selector:
        app: ${NAME}

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - ${NAME}
                  topologyKey: kubernetes.io/hostname
          containers:
            - env:
                - name: APP_SECURITY_ORIGIN
                  valueFrom:
                    secretKeyRef:
                      key: APP_SECURITY_ORIGIN
                      name: ${FFA_BPM_SECRET}
                - name: WEBSOCKET_SECURITY_ORIGIN
                  valueFrom:
                    secretKeyRef:
                      key: WEBSOCKET_SECURITY_ORIGIN
                      name: ${FFA_BPM_SECRET}
                - name: CAMUNDA_JDBC_DRIVER
                  valueFrom:
                    secretKeyRef:
                      key: CAMUNDA_JDBC_DRIVER
                      name: ${FFA_BPM_SECRET}  
                - name: DATABASE_SERVICE_NAME
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_SERVICE_NAME
                      name: ${FFA_BPM_SECRET}
                - name: DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_PORT
                      name: ${FFA_BPM_SECRET}
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_NAME
                      name: ${FFA_BPM_SECRET}
                - name: CAMUNDA_JDBC_URL
                  value: jdbc:postgresql://${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${DATABASE_NAME}
                - name: WAIT_FOR
                  value: ${DATABASE_SERVICE_NAME}:${DATABASE_PORT}
                - name: CAMUNDA_JDBC_USER
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: ${DATABASE_SECRET}
                - name: CAMUNDA_JDBC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: ${DATABASE_SECRET}                      
                - name: KEYCLOAK_URL
                  valueFrom:
                    secretKeyRef:
                      key: KEYCLOAK_URL
                      name: ${FFA_BPM_SECRET}
                - name: KEYCLOAK_URL_REALM
                  valueFrom:
                    secretKeyRef:
                      key: KEYCLOAK_URL_REALM
                      name: ${FFA_BPM_SECRET}
                - name: KEYCLOAK_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      key: KEYCLOAK_CLIENTID
                      name: ${FFA_BPM_SECRET}
                - name: KEYCLOAK_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      key: BPM_CLIENT_SECRET
                      name: ${FFA_BPM_SECRET}
                - name: DEBUG
                  value: "False"
                - name: MAIL_CONFIG
                  value: /app/mail-config.properties
                - name: TZ
                  value: UTC
                - name: CAMUNDA_JDBC_DB
                  valueFrom:
                    secretKeyRef:
                      key: DATABASE_NAME
                      name: ${FFA_BPM_SECRET}
                - name: CAMUNDA_APP_ROOT_LOG_FLAG
                  value: info
                - name: WEBSOCKET_ENCRYPT_KEY
                  valueFrom:
                    secretKeyRef:
                      key: WEBSOCKET_ENCRYPT_KEY
                      name: ${FFA_BPM_SECRET}
                - name: WEBSOCKET_MESSAGE_TYPE
                  value: ${WEBSOCKET_MESSAGE_TYPE}                
                - name: WEBSOCKET_BROKER_HOST
                  value: ${WEBSOCKET_BROKER_HOST}
                - name: WEBSOCKET_BROKER_PORT
                  value: ${WEBSOCKET_BROKER_PORT}   
                - name: WEBSOCKET_BROKER_PASSCODE
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: ${MSGBROKER_SECRET}                 
                - name: WEBSOCKET_FOI_RAWREQUEST_TOPIC
                  value: ${WEBSOCKET_FOI_RAWREQUEST_TOPIC} 
                - name: FORMSFLOW_WF_URL
                  valueFrom:
                    secretKeyRef:
                      key: FORMSFLOW_WF_URL
                      name: ${FFA_BPM_SECRET} 
                - name: FOI_REQ_MANAGEMENT_API_URL
                  value: ${FOI_REQ_MANAGEMENT_API_URL}
                - name: FORMSFLOW_API_URL
                  valueFrom:
                    secretKeyRef:
                      key: FORMSFLOW_API_URL
                      name: ${FFA_BPM_SECRET}  
                - name: FORMSFLOW_WEB_URL
                  valueFrom:
                    secretKeyRef:
                      key: FORMSFLOW_WEB_URL
                      name: ${FFA_BPM_SECRET}  
                - name: FORMIO_ROOT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      key: formio_root_email
                      name: ${FFA_SECRET}
                - name: FORMIO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: formio_root_password
                      name: ${FFA_SECRET}
                - name: FORMIO_DEFAULT_PROJECT_URL
                  valueFrom:
                    secretKeyRef:
                      key: FORMIO_DEFAULT_PROJECT_URL
                      name: ${FFA_BPM_SECRET}  
                - name: FORMIO_URL
                  valueFrom:
                    secretKeyRef:
                      key: FORMIO_URL
                      name: ${FFA_BPM_SECRET}  
                - name: isIMAPEnabled
                  value: "False"
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /camunda/actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 60
                successThreshold: 1
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: 600m
                  memory: 1Gi
                requests:
                  cpu: 200m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /app/mail-config.properties
                  name: ${NAME}-mail-config
                  subPath: mail-config.properties
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                items:
                  - key: mail-config.properties
                    path: mail-config.properties
                name: ${NAME}-mail-config
              name: ${NAME}-mail-config
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${NAME}
          from:
            kind: ImageStreamTag
            name: ${IMAGE_NAME}:${IMAGE_TAG}
            namespace: ${TOOLS_WORKSPACE}
        type: ImageChange

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
  - name: IMAGE_NAME
    description: The Image name.
    required: true
  - name: IMAGE_TAG
    description: The image tag to pull for the deployment.
    required: true
  - name: TOOLS_WORKSPACE
    description: The location for your image streams (Tools Workspace).
    required: true
  - name: DATABASE_SECRET
    description: Secrets are referred from this.
    required: true
  - name: FFA_SECRET
    description: Secrets are referred from this.
    required: true
  - name: FFA_BPM_SECRET
    description: Secrets are referred from this.
    required: true
  - name: MSGBROKER_SECRET
    description: Secrets are referred from this.
    required: true
  - name: CAMUNDA_APP_ROOT_LOG_FLAG
    description: CAMUNDA_APP_ROOT_LOG_FLAG
    required: true
    value: "info"
  - name: CAMUNDA_URL
    displayName: CAMUNDA_URL
    description:
      Route to access Camunda
    required: true
  - name: WEBSOCKET_MESSAGE_TYPE
    description: WEBSOCKET_MESSAGE_TYPE
    required: true
    value: "TASK_EVENT"
  - name: WEBSOCKET_BROKER_HOST
    description: WEBSOCKET_BROKER_HOST
    required: true
  - name: WEBSOCKET_BROKER_PORT
    description: WEBSOCKET_BROKER_PORT
    required: true
  - name: WEBSOCKET_FOI_RAWREQUEST_TOPIC
    description: WEBSOCKET_FOI_RAWREQUEST_TOPIC
    required: true
  - name: FOI_REQ_MANAGEMENT_API_URL
    description: FOI_REQ_MANAGEMENT_API_URL
    required: true
  - name: SMTP_SERVER
    description: SMTP_SERVER
    required: true
  - name: SMTP_MAIL_SENDER
    description: SMTP_MAIL_SENDER
    required: true