const FOI_ACTION_CONSTANTS = {
    ERROR: "ERROR",
    IS_LOADING: "IS_LOADING",
    IS_ASSIGNEDTOLIST_LOADING: "IS_ASSIGNEDTOLIST_LOADING",
    IS_ATTACHMENTLIST_LOADING: "IS_ATTACHMENTLIST_LOADING",
    FOI_CATEGORYLIST: "FOI_CATEGORYLIST",
    FOI_COUNTRYLIST: "FOI_COUNTRYLIST",
    FOI_PROVINCELIST: "FOI_PROVINCELIST",    
    FOI_REQUEST_TYPELIST: "FOI_REQUEST_TYPELIST",   
    FOI_RECEIVED_MODELIST: "FOI_RECEIVED_MODELIST",
    FOI_DELIVERY_MODELIST: "FOI_DELIVERY_MODELIST",
    FOI_ASSIGNED_TOLIST: "FOI_ASSIGNED_TOLIST",
    FOI_FULL_ASSIGNED_TOLIST: "FOI_FULL_ASSIGNED_TOLIST",
    FOI_MINISTRY_ASSIGNED_TOLIST: "FOI_MINISTRY_ASSIGNED_TOLIST",
    FOI_PROGRAM_AREALIST: "FOI_PROGRAM_AREALIST",

    FOI_LIST_REQUESTS: "FOI_LIST_REQUESTS",
    FOI_REQUESTS_COUNT: "FOI_REQUESTS_COUNT",

    FOI_REQUEST_DETAIL: "FOI_REQUEST_DETAIL",
    FOI_MINISTRYVIEW_REQUEST_DETAIL: "FOI_MINISTRYVIEW_REQUEST_DETAIL",
    CLEAR_REQUEST_DETAILS: "CLEAR_REQUEST_DETAILS",
    CLEAR_MINISTRYVIEWREQUEST_DETAILS: "CLEAR_MINISTRYVIEWREQUEST_DETAILS",

    FOI_IS_REQUEST_UPDATED: "FOI_IS_REQUEST_UPDATED",
    FOI_REQUEST_DESCRIPTION_HISTORY: "FOI_REQUEST_DESCRIPTION_HISTORY",
    FOI_MINISTRY_REQUESTSLIST: "FOI_MINISTRY_REQUESTSLIST",
    FOI_MINISTRY_DIVISIONALSTAGES :"FOI_MINISTRY_DIVISIONALSTAGES",

    FOI_WATCHER_LIST: "FOI_WATCHER_LIST",

    CLOSING_REASONS: "CLOSING_REASONS",

    FOI_REQUEST_COMMENTS:"FOI_REQUEST_COMMENTS",

    FOI_REQUEST_ATTACHMENTS:"FOI_REQUEST_ATTACHMENTS",
    
  };
  
  export default FOI_ACTION_CONSTANTS;
  