const FOI_ACTION_CONSTANTS = {
    ERROR: "ERROR",
    IS_LOADING: "IS_LOADING", 
    FOI_CATEGORYLIST: "FOI_CATEGORYLIST",
    FOI_COUNTRYLIST: "FOI_COUNTRYLIST",
    FOI_PROVINCELIST: "FOI_PROVINCELIST",    
    FOI_REQUEST_TYPELIST: "FOI_REQUEST_TYPELIST",   
    FOI_RECEIVED_MODELIST: "FOI_RECEIVED_MODELIST",
    FOI_DELIVERY_MODELIST: "FOI_DELIVERY_MODELIST",
    FOI_ASSIGNED_TO: "FOI_ASSIGNED_TO",
    FOI_PROGRAM_AREALIST: "FOI_PROGRAM_AREALIST",

    FOI_LIST_REQUESTS: "FOI_LIST_REQUESTS",
    FOI_REQUESTS_COUNT: "FOI_REQUESTS_COUNT",

    FOI_REQUEST_DETAIL: "FOI_REQUEST_DETAIL",
    CLEAR_REQUEST_DETAILS: "CLEAR_REQUEST_DETAILS",

    FOI_IS_REQUEST_UPDATING: "FOI_IS_REQUEST_UPDATING",
  };
  
  export default FOI_ACTION_CONSTANTS;
  