version: '3'
services: 
 
  BACKEND:
    build:
      context: ./request-management-api  
      dockerfile: dockerfile.local
    image: foirequestsbackendimage
    container_name: aot_foi_requests_backend_api
    depends_on: 
      - foi-requests-DB     
    networks:
      services-network:
        aliases:
          - backendnw
    ports:
      - 15000:5000
    environment:
      - DATABASE_USERNAME=${FOI_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${FOI_DATABASE_PASSWORD}
      - DATABASE_NAME=${FOI_DATABASE_NAME}
      - DATABASE_HOST=${FOI_DATABASE_HOST}
      - DATABASE_PORT=${FOI_DATABASE_PORT}
      - FLASK_ENV:production
      - FOI_REQUESTQUEUE_REDISHOST=${WEBSOCKET_BROKER_HOST}
      - FOI_REQUESTQUEUE_REDISPORT=${WEBSOCKET_BROKER_PORT}
      - FOI_REQUESTQUEUE_REDISPASSWORD=${WEBSOCKET_BROKER_PASSCODE}
      - FOI_REQUESTQUEUE_REDISCHANNEL=${WEBSOCKET_FOI_RAWREQUEST_TOPIC}
      - KEYCLOAK_ADMIN_HOST=${KEYCLOAK_URL}
      - KEYCLOAK_ADMIN_REALM=${KEYCLOAK_URL_REALM}
      - KEYCLOAK_ADMIN_CLIENT_ID=foi-lob-api
      - KEYCLOAK_ADMIN_CLIENT_SECRET=${KEYCLOAK_ADMIN_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_SRVACCOUNT=foisrcaccount
      - KEYCLOAK_ADMIN_SRVPASSWORD=${KEYCLOAK_ADMIN_SRVPASSWORD}
      - KEYCLOAK_ADMIN_INTAKE_GROUPID=${KEYCLOAK_ADMIN_INTAKE_GROUPID}
      - BPM_ENGINE_REST_URL=${FORMSFLOW_WF_URL}
      - BPM_TOKEN_URL=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM}/protocol/openid-connect/token
      - BPM_CLIENT_ID=forms-flow-bpm
      - BPM_CLIENT_SECRET=${KEYCLOAK_BPM_CLIENT_SECRET}
      - JWT_OIDC_AUDIENCE=${JWT_OIDC_AUDIENCE}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_OIDC_WELL_KNOWN_CONFIG=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM}/.well-known/openid-configuration
      - JWT_OIDC_ALGORITHMS=RS256
      - JWT_OIDC_JWKS_URI=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM}/protocol/openid-connect/certs
      - JWT_OIDC_ISSUER=${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM}
      - JWT_OIDC_CACHING_ENABLED=True
      - JWT_OIDC_JWKS_CACHE_TIMEOUT=300
      - CACHE_TIMEOUT=${CACHE_TIMEOUT}
      - FOI_REQUESTQUEUE_REDISURL=${FOI_REQUESTQUEUE_REDISURL}
      - CACHE_ENABLED=${CACHE_ENABLED}
      - OSS_S3_FORMS_BUCKET=${OSS_S3_FORMS_BUCKET}
      - OSS_S3_FORMS_ACCESS_KEY_ID=${OSS_S3_FORMS_ACCESS_KEY_ID}
      - OSS_S3_FORMS_SECRET_ACCESS_KEY=${OSS_S3_FORMS_SECRET_ACCESS_KEY}
      - OSS_S3_HOST=${OSS_S3_HOST} 
      - OSS_S3_REGION=${OSS_S3_REGION}
      - OSS_S3_SERVICE=${OSS_S3_SERVICE}

  foi-requests-DB:
    image: postgres
    container_name: aot_foi_requests_db_pg
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=${FOI_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${FOI_DATABASE_PASSWORD}
    networks:
      services-network:
        aliases:
          - db   

           
volumes:
  dbdata:
networks:
  forms-flow-bpm-network:
  services-network:    
    driver: bridge
