version: '3'
services: 
  foiredis:
    image: redis:4.0
    container_name: aot_foi_request_redis
    ports:
      - "6379:6379" 
  BACKEND:
    build:
      # context: ./      
      # dockerfile: request-management-api/dockerfile
      context: ./request-management-api  
      dockerfile: dockerfile.local
    image: foirequestsbackendimage
    container_name: aot_foi_requests_backend_api
    depends_on: 
      - foi-requests-DB     
    networks:
      services-network:
        aliases:
          - backendnw
    ports:
      - 15000:5000
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Fo!123
      - DATABASE_NAME=postgres
      - DATABASE_HOST=foi-requests-DB
      - DATABASE_PORT=5432
      - FLASK_ENV:production
      - FOI_REQUESTQUEUE_REDISHOST=10.0.0.143
      - FOI_REQUESTQUEUE_REDISPORT=6379
      - FOI_REQUESTQUEUE_REDISPASSWORD=
      - FOI_REQUESTQUEUE_REDISCHANNEL=FOI_WF_REQUEST_CHANNEL
      - KEYCLOAK_ADMIN_HOST=https://dev.oidc.gov.bc.ca/
      - KEYCLOAK_ADMIN_REALM=
      - KEYCLOAK_ADMIN_CLIENT_ID=foi-lob-api
      - KEYCLOAK_ADMIN_CLIENT_SECRET=
      - KEYCLOAK_ADMIN_SRVACCOUNT=foisrcaccount
      - KEYCLOAK_ADMIN_SRVPASSWORD=
      - KEYCLOAK_ADMIN_INTAKE_GROUPID=
      - BPM_ENGINE_REST_URL=
      - BPM_TOKEN_URL=
      - BPM_CLIENT_ID=forms-flow-bpm
      - BPM_CLIENT_SECRET=
  foi-requests-DB:
    image: postgres
    container_name: aot_foi_requests_db_pg
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Fo!123
    networks:
      services-network:
        aliases:
          - db   
volumes:
  dbdata:
networks:
  services-network:    
    driver: bridge
