apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      NOTIFICATION_REDIS_HOST: "${NOTIFICATION_REDIS_HOST}"
      NOTIFICATION_REDIS_PORT: "${NOTIFICATION_REDIS_PORT}"
      NOTIFICATION_REDIS_PASSWORD: '${NOTIFICATION_REDIS_PASSWORD}'
      NOTIFICATION_STREAM_KEY: '${NOTIFICATION_STREAM_KEY}'
      DATABASE_NAME: '${DATABASE_NAME}'
      KEYCLOAK_ADMIN_HOST: '${KEYCLOAK_ADMIN_HOST}'
      KEYCLOAK_ADMIN_REALM: '${KEYCLOAK_ADMIN_REALM}'
      KEYCLOAK_ADMIN_CLIENT_ID: '${KEYCLOAK_ADMIN_CLIENT_ID}'
      KEYCLOAK_ADMIN_CLIENT_SECRET: '${KEYCLOAK_ADMIN_CLIENT_SECRET}'
      KEYCLOAK_ADMIN_SRVACCOUNT: '${KEYCLOAK_ADMIN_SRVACCOUNT}'
      KEYCLOAK_ADMIN_SRVPASSWORD: '${KEYCLOAK_ADMIN_SRVPASSWORD}'
      

    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: notification-manager
  - name: NOTIFICATION_REDIS_HOST
    description: NOTIFICATION_REDIS_HOST
    required: true
  - name: NOTIFICATION_REDIS_PORT
    description: NOTIFICATION_REDIS_PORT
    required: true
  - name: NOTIFICATION_REDIS_PASSWORD
    description: NOTIFICATION_REDIS_PASSWORD
    required: true
  - name: NOTIFICATION_STREAM_KEY
    description: NOTIFICATION_STREAM_KEY
    required: true
  - name: DATABASE_NAME
    description: DATABASE_NAME
    required: true
  - name: KEYCLOAK_ADMIN_HOST
    description: KEYCLOAK_ADMIN_HOST
    required: true
  - name: KEYCLOAK_ADMIN_REALM
    description: KEYCLOAK_ADMIN_REALM
    required: true
  - name: KEYCLOAK_ADMIN_CLIENT_ID
    description: KEYCLOAK_ADMIN_CLIENT_ID
    required: true
  - name: KEYCLOAK_ADMIN_CLIENT_SECRET
    description: KEYCLOAK_ADMIN_CLIENT_SECRET
    required: true
  - name: KEYCLOAK_ADMIN_SRVACCOUNT
    description: KEYCLOAK_ADMIN_SRVACCOUNT
    required: true
  - name: KEYCLOAK_ADMIN_SRVPASSWORD
    description: KEYCLOAK_ADMIN_SRVPASSWORD
    required: true
  