const FOI_ACTION_CONSTANTS = {
    ERROR: "ERROR",
    IS_LOADING: "IS_LOADING", 
    //REQUESTS
    FOI_LIST_REQUESTS: "FOI_LIST_REQUESTS",
    FOI_REQUESTS_COUNT: "FOI_REQUESTS_COUNT",
    FOI_REQUEST_DETAIL: "FOI_REQUEST_DETAIL",
    FOI_IS_REQUEST_UPDATING: "FOI_IS_REQUEST_UPDATING", 
  };
  
  export default FOI_ACTION_CONSTANTS;
  