<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EDU_selectspanEDU</name>
   <tag></tag>
   <elementGuidId>7aebaa9d-9e48-42c4-bfec-a75faa1719cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='selectspanEDU']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectspanEDU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c3721b7-dc29-4e96-99d5-defc789e6ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectspanEDU</value>
      <webElementGuid>860f8801-e474-49ae-b1af-0f529f0269a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>3455eee8-4b23-4b6a-9dd9-f26f608fa79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectspanEDU&quot;)</value>
      <webElementGuid>6a979fbf-6244-44cf-9f32-eaaa0f1ec300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='selectspanEDU']</value>
      <webElementGuid>7f287a9d-bcbe-444e-92a5-14d2fe173a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lblEDU']/span</value>
      <webElementGuid>e417ccd2-efbf-4863-ae20-b4e8f12ae839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[11]/span</value>
      <webElementGuid>8f669c9c-d1b6-4dfe-92d9-6353f5fa8e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'selectspanEDU']</value>
      <webElementGuid>ed4a7a3d-7d1b-4b03-bb4a-8f6b34befe0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
