<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_g</name>
   <tag></tag>
   <elementGuidId>d0c3a3d4-f3eb-41ae-97d6-e47726999bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='outlined-multiline-request-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#outlined-multiline-request-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>312049fb-6b96-4b4f-ba98-dc8e4eddc832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ca1051c-f9b5-47cc-bdb2-bcef91e6f1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-multiline-request-description</value>
      <webElementGuid>431eda9b-20c4-4fbb-87c3-b74bd3565883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>38a0b31c-23ec-40e0-9178-dcfb315d7876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMultiline MuiOutlinedInput-inputMultiline</value>
      <webElementGuid>b19c6797-b5dd-4b4e-aae0-6189d15ab635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>g</value>
      <webElementGuid>35463b2c-80bc-4860-bb6c-78b4e5ba021a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-multiline-request-description&quot;)</value>
      <webElementGuid>a31d4f34-eac1-49f4-96a7-633f7515c041</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='outlined-multiline-request-description']</value>
      <webElementGuid>bcaca003-9069-4b94-90e2-81de745adf02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div[7]/div/div[2]/div/div/div/div/div[4]/div/div/div/div/textarea</value>
      <webElementGuid>787d3653-a537-413d-8679-79b0ec86f8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[2]/following::textarea[1]</value>
      <webElementGuid>820b53bd-4492-4f85-a9e7-d8aab27cacbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Ministry Client *'])[1]/preceding::textarea[1]</value>
      <webElementGuid>61f5e2f4-eff9-4c10-b59c-b5784440ea9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='g']/parent::*</value>
      <webElementGuid>c2b73657-75d5-49ec-a11d-4e93f37bc55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9ef7662f-ab51-4066-bb21-eceb7387b9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'outlined-multiline-request-description' and (text() = 'g' or . = 'g')]</value>
      <webElementGuid>ca10d850-d817-4aca-9920-31f267344d2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
