<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_ABC-2099-310</name>
   <tag></tag>
   <elementGuidId>fd141b12-1fef-4ec9-b067-dfe3ef7317a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Request']/div/div/form/div/div/div/a/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.foi-review-request-text.foi-ministry-requestheadertext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>69cc3294-b050-43ca-84ed-81af1166b5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foi-review-request-text foi-ministry-requestheadertext</value>
      <webElementGuid>3a499447-78c0-420a-b873-04956378afda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABC-2099-310</value>
      <webElementGuid>173eea45-dbc6-4d44-a0ef-2df0fafcf502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Request&quot;)/div[@class=&quot;container foi-review-request-container&quot;]/div[@class=&quot;foi-review-container&quot;]/form[@class=&quot;jss11 foi-request-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;foi-request-review-header-col1-row axis-request-id&quot;]/a[@class=&quot;MuiTypography-root MuiLink-root MuiLink-underlineHover MuiTypography-colorPrimary&quot;]/h1[@class=&quot;foi-review-request-text foi-ministry-requestheadertext&quot;]</value>
      <webElementGuid>2b9e8f7c-3ae9-4cb3-ad7e-4bea51cec90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div/div/div/a/h1</value>
      <webElementGuid>45c3df05-f606-4d96-b5aa-42075f74be21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABC-2099-310'])[3]/following::h1[1]</value>
      <webElementGuid>31c0d1c2-db8b-4561-94f4-5f4fdd9bb837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Queue'])[1]/following::h1[1]</value>
      <webElementGuid>8c1aa425-bd74-4e9d-899f-9b445c61175b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IAO Assigned To'])[1]/preceding::h1[1]</value>
      <webElementGuid>b5463b88-5d04-4f5c-a8c1-7cfb16bbb607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IAO Assigned To'])[2]/preceding::h1[1]</value>
      <webElementGuid>e6993d21-f9d5-466e-ab33-6a0d70d8eb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>07057488-9a30-4c15-bc9b-dc8a11a74397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'ABC-2099-310' or . = 'ABC-2099-310')]</value>
      <webElementGuid>e7f1d26a-cbeb-4600-9cb7-7d6bcf42539c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
