<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EDU_checkmark</name>
   <tag></tag>
   <elementGuidId>89ba8d36-c9cf-4086-8009-03734861eb62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Request']/div/div/form/div[7]/div/div[2]/div/div/div/div/div[6]/div/label[11]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8645c229-5206-427b-ae9f-579e93f3758e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>73764705-487d-4ef5-82d8-aef842ab6bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Request&quot;)/div[@class=&quot;container foi-review-request-container&quot;]/div[@class=&quot;foi-review-container&quot;]/form[@class=&quot;jss11 foi-request-form&quot;]/div[@class=&quot;request-accordian&quot;]/div[@class=&quot;MuiPaper-root MuiAccordion-root Mui-expanded MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[1]/div[@class=&quot;MuiAccordionDetails-root&quot;]/div[@class=&quot;foi-ministries-container&quot;]/div[@class=&quot;foi-ministries-checkboxes&quot;]/label[@class=&quot;check-item&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>8d6cd0da-2c53-4542-bca4-6c54bf59f707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div[7]/div/div[2]/div/div/div/div/div[6]/div/label[11]/span</value>
      <webElementGuid>c8e2381a-8de2-4533-ae5f-ea7385e6ff64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[11]/span</value>
      <webElementGuid>cc1796cf-cb35-4477-bdba-d9f57f94ec03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
