<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_queue header ON BEHALF OF</name>
   <tag></tag>
   <elementGuidId>0c5122e2-9da5-4802-bbef-0aba6e3ea2a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;container foi-container&quot;]/div[@class=&quot;col-sm-12 col-md-12 foi-grid-container&quot;]/div[@class=&quot;jss1&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-root foi-data-grid&quot;]/div[@class=&quot;MuiDataGrid-main&quot;]/div[@class=&quot;MuiDataGrid-columnsContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderWrapper&quot;]/div[@class=&quot;MuiDataGrid-columnHeader--sortable MuiDataGrid-columnHeader&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderDraggableContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderTitleContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderTitle&quot;][count(. | //*[@data-field = 'onBehalf']) = count(//*[@data-field = 'onBehalf'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c92a6953-5454-464b-a9ef-eeda1ab30916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDataGrid-columnHeaderTitle</value>
      <webElementGuid>4639396f-966a-447d-935f-9eedaa085fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ON BEHALF </value>
      <webElementGuid>3a60d36e-c8f9-402b-bcc8-2bd74f7998ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;container foi-container&quot;]/div[@class=&quot;col-sm-12 col-md-12 foi-grid-container&quot;]/div[@class=&quot;jss1&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-root foi-data-grid&quot;]/div[@class=&quot;MuiDataGrid-main&quot;]/div[@class=&quot;MuiDataGrid-columnsContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderWrapper&quot;]/div[@class=&quot;MuiDataGrid-columnHeader--sortable MuiDataGrid-columnHeader&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderDraggableContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderTitleContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderTitle&quot;]</value>
      <webElementGuid>4bca47cf-d106-46c4-9cad-17cdfcfb6c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>columnheader</value>
      <webElementGuid>fd1b2745-8983-44c0-baf5-dd3457ba5cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>onBehalf</value>
      <webElementGuid>25e2c299-07dc-4c2b-b088-4048cc34d448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[3]/div/div[2]/div/div/div[5]/div/div/div</value>
      <webElementGuid>eea8126c-ac4d-4cdc-968e-dac2d7057c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CURRENT STATE'])[1]/following::div[7]</value>
      <webElementGuid>890efed4-594e-4ccc-9267-404837e0f1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID NUMBER'])[1]/following::div[14]</value>
      <webElementGuid>b13a6843-e410-4711-82e3-08f92eced7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECEIVED DATE'])[1]/preceding::div[4]</value>
      <webElementGuid>02bd0835-8619-4ad5-92c6-669bae36edff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XGOV'])[1]/preceding::div[11]</value>
      <webElementGuid>03059eaa-fe7b-40bd-984f-d0a7ec9d41e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ASSIGNED TO']/parent::*</value>
      <webElementGuid>7caf9ab4-222e-41c5-9ec0-035fa136b1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>d55e8444-7fe1-4d03-b345-c66de3c015c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
