<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Watching Notifications</name>
   <tag></tag>
   <elementGuidId>92ecb8dc-f42a-4300-8ead-ba8bbd815b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uncontrolled-tab-example-tab-watch-request']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uncontrolled-tab-example-tab-watch-request</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>457ca752-6602-4c3e-bbe2-12a3a667bbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tab-watch-request</value>
      <webElementGuid>cb70633d-621a-40d2-a056-2c2200ac2bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>afa86086-7ce6-4abe-b431-cd5d979985da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f8301ead-c592-4789-ac81-7e1dcff926bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>watch-request</value>
      <webElementGuid>42476551-0e4f-461e-a48d-50cba9940ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tabpane-watch-request</value>
      <webElementGuid>50d555ca-b4e9-4d5c-9089-887fe79b0155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72f905c0-03c3-42d7-bbc6-cc7207a86205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link</value>
      <webElementGuid>ca70dd07-f6f3-4087-9ded-b7b00ac7386c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watching Notifications</value>
      <webElementGuid>251b0539-15a3-4143-a98f-e6bb796d4db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uncontrolled-tab-example-tab-watch-request&quot;)</value>
      <webElementGuid>314308f0-21d9-419d-9e84-16a5d1a4b8bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uncontrolled-tab-example-tab-watch-request']</value>
      <webElementGuid>7b77633e-53b2-4701-8039-b4376f3c4559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-2']/nav/a[2]</value>
      <webElementGuid>e31793c0-4537-4aa3-98a6-bf2c76ef1b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Watching Notifications')]</value>
      <webElementGuid>0cbd1a05-566e-4583-b534-fbc6b231fe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'uncontrolled-tab-example-tab-watch-request', '&quot;', ')')])[1]/following::a[2]</value>
      <webElementGuid>45fdba4d-ecdc-4a1a-a600-c21fafa3c5a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::a[2]</value>
      <webElementGuid>dfaa3672-57b6-401a-9d4a-9d21463ca15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>d9ed2f88-ac2f-4d6d-b05a-419a03094591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No notifications'])[2]/preceding::a[1]</value>
      <webElementGuid>3771ef8c-90ff-4a55-94fd-9555116b2b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watching Notifications']/parent::*</value>
      <webElementGuid>3177884e-b651-42f9-9756-16178acc33af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>849c80af-c23e-49dd-a75b-6c364927e4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>629213be-11d2-48e9-a164-9e957ee0e9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uncontrolled-tab-example-tab-watch-request' and @href = '#' and (text() = 'Watching Notifications' or . = 'Watching Notifications')]</value>
      <webElementGuid>d5a6245c-c04f-4676-a6ee-3f470f83ff8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
