<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_notification list 2 delete</name>
   <tag></tag>
   <elementGuidId>06428c8a-8cc2-4928-8db1-41eab03622c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uncontrolled-tab-example-tabpane-my-request']/div[2]/div[2]/div/div[2]/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;uncontrolled-tab-example-tabpane-my-request&quot;)/div[@class=&quot;notification-list list-group&quot;]/div[@class=&quot;list-group-item&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;close-btn-align col&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bdf2d47c-f71b-4c23-ad5b-6aac01d74509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>891bfab0-9b28-4969-91ae-6e5f34d78e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uncontrolled-tab-example-tabpane-my-request&quot;)/div[@class=&quot;notification-list list-group&quot;]/div[@class=&quot;list-group-item&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;close-btn-align col&quot;]/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>0a0216e4-dc97-4657-ac7e-2885644b318d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uncontrolled-tab-example-tabpane-my-request']/div[2]/div[2]/div/div[2]/i</value>
      <webElementGuid>1ab8ba57-72aa-49c6-ab85-9582768dac14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/i</value>
      <webElementGuid>8a00c224-bb05-4c09-b41f-8f743b70e65b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
