<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Received Date_receivedDate</name>
   <tag></tag>
   <elementGuidId>7366997d-6688-4721-80a9-4711d3d648eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receivedDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receivedDate']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'receivedDate' and @type = 'date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d59a3619-32fa-489c-8e23-d1d9b050823e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39cdb260-888c-4b81-8c9e-57820eb78e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receivedDate</value>
      <webElementGuid>2134541d-136f-461d-9409-ef3d2ae1c5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>5623d697-28c1-474a-8d88-610acbe591a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2023-02-23</value>
      <webElementGuid>bbdb92d6-f5cc-4d52-bb7e-ed44f0b7adea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>f94f6c80-853b-49e5-8f1e-7c8b8e201bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receivedDate&quot;)</value>
      <webElementGuid>69e6c7d5-42b0-4df6-ba1c-291e4e582522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receivedDate']</value>
      <webElementGuid>60235ac3-5378-4f50-a03b-aa1c200b5152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div[8]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>963bbdf8-12fa-47d9-96a8-928ff28e5a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1c2db3f6-5bf1-40ce-a21c-c5978673a583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receivedDate' and @type = 'date']</value>
      <webElementGuid>87d5feb5-c762-4537-98ff-f1734f8ed179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
