<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_idapp</name>
   <tag></tag>
   <elementGuidId>88b56292-c467-4e5c-92ce-5b4ea647be85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.foitabheadercollection.foitabheaderCFRG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CFRForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9877d28-047f-4d1e-937c-90ed4fac5c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foitabheadercollection foitabheaderCFRG</value>
      <webElementGuid>17713aa6-6429-4872-b21e-3004da4443e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABC-2099-3921StatusCall For RecordsStatusRequestCFR FormAttachments Comments (8)Contact Applicant 172 Days OverdueCFR Due in -172 DaysExtensions 0</value>
      <webElementGuid>94e7fe22-2ec8-404f-91e0-86756b0160d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;foiformcontent false&quot;]/div[@class=&quot;foitabbedContainer&quot;]/div[@class=&quot;foitabheadercollection foitabheaderCFRG&quot;]</value>
      <webElementGuid>c98704ef-df1e-48c5-a6fb-684f8615d9c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div</value>
      <webElementGuid>c609faa5-736e-4227-8e7e-e4c12cccc2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::div[3]</value>
      <webElementGuid>62d2d183-8f42-45e4-aeb8-ff72458790e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>226f8554-b132-4d34-8ab9-14efe44ba3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ABC-2099-3921StatusCall For RecordsStatusRequestCFR FormAttachments Comments (8)Contact Applicant 172 Days OverdueCFR Due in -172 DaysExtensions 0' or . = 'ABC-2099-3921StatusCall For RecordsStatusRequestCFR FormAttachments Comments (8)Contact Applicant 172 Days OverdueCFR Due in -172 DaysExtensions 0')]</value>
      <webElementGuid>5302cd40-e773-4103-9e17-4e4cd9ae77b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
