<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_INCOMPATIBLE_selectchk14989</name>
   <tag></tag>
   <elementGuidId>f147902d-d962-4f05-bb09-4094c28b4901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @data-iaocode = '12396']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectchk14989</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Records']/div/div[2]/div[6]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>881fb95a-939c-4aa6-b61a-f9e07a668d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2232d443-0d90-4b42-a3cb-32ed92cdf49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark record-checkmark</value>
      <webElementGuid>bf15a932-9bc4-43d4-8602-0ae7aced73e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectchk14989</value>
      <webElementGuid>cb6326cb-74b9-4ca3-a9e0-064966082e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iaocode</name>
      <type>Main</type>
      <value>12396</value>
      <webElementGuid>8fbfbd8c-2b0b-442e-bf7a-09bdd033ef58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectchk14989&quot;)</value>
      <webElementGuid>fcf7a547-a4d2-4dde-a7a8-c69284ce9f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectchk14989']</value>
      <webElementGuid>edb4ae77-f798-4361-a459-3f5005cd2202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Records']/div/div[2]/div[6]/div/div/input</value>
      <webElementGuid>9d53a24f-270c-484c-876a-ea0e2ee653f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div/div/input</value>
      <webElementGuid>5f1c66ff-db2d-47f6-842f-e1ea878179b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectchk14989']</value>
      <webElementGuid>1f880643-651e-401c-9bbb-7e71113c92c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
