<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_INCOMPATIBLE</name>
   <tag></tag>
   <elementGuidId>5926f7b9-e63f-401f-b0f8-003a8e701d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-3Tag > span.MuiChip-label.MuiChip-labelSmall.css-1pjtbja</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-3Tag']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5870bf38-7e7b-40b3-b09a-71538ca3f521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiChip-label MuiChip-labelSmall css-1pjtbja</value>
      <webElementGuid>7dc2700c-e04b-4995-a575-c35d65b04fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INCOMPATIBLE</value>
      <webElementGuid>1951398c-c8e2-46a5-9100-03d08ab29f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-3Tag&quot;)/span[@class=&quot;MuiChip-label MuiChip-labelSmall css-1pjtbja&quot;]</value>
      <webElementGuid>6301227e-877b-4619-ab38-1c63b3b69cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-3Tag']/span</value>
      <webElementGuid>10137327-3f61-42d3-a304-5c486d6904a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ERRORS'])[1]/following::span[2]</value>
      <webElementGuid>2ce878a2-5dd2-418f-aa6d-650701103169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[2]/following::span[4]</value>
      <webElementGuid>1fcd3d37-5049-4ac5-ade8-2a440a30fbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[2]</value>
      <webElementGuid>090b5803-679a-403f-bfec-c2fa5bab3fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::span[3]</value>
      <webElementGuid>a02a3e85-3214-429a-83ad-0c5d0210e56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INCOMPATIBLE']/parent::*</value>
      <webElementGuid>bdc7c5a5-28ec-4554-a755-02c1cccd0ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span</value>
      <webElementGuid>db699ff0-2b9a-460d-8e5a-ba10b8a73ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'INCOMPATIBLE' or . = 'INCOMPATIBLE')]</value>
      <webElementGuid>7084016a-452c-4231-9450-34ae7e821b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
