<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>56a466a7-30ee-4a33-9883-3281ffe7c43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btncfrsave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btncfrsave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c958254f-97d1-40d5-84a1-950150f57e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecd5c5af-ac90-4673-9fef-5f01b4ee2450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-4 btn btn-bottom btn-save</value>
      <webElementGuid>3db72e2c-8789-4550-ba36-21569b9bd13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btncfrsave</value>
      <webElementGuid>434ebf72-cb42-4eca-9da4-d6df8dc4101e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f097d2cd-0357-4534-af0b-3a7382fd1c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>02228eb7-3f54-4c93-a6de-e7e0a83746fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btncfrsave&quot;)</value>
      <webElementGuid>85760723-5311-49c8-9ce0-76c4d4414cd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btncfrsave']</value>
      <webElementGuid>bb304137-2fae-401f-b7ef-5407ae2d96a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[5]/button</value>
      <webElementGuid>b5cf5cd4-9de6-41aa-a75f-20d37f0c9397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combined suggestions for futher clarifications'])[2]/following::button[1]</value>
      <webElementGuid>8a334738-aad4-4de8-9596-4ce61d1bd50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combined suggestions for futher clarifications'])[1]/following::button[1]</value>
      <webElementGuid>aeebf6bf-b1b6-4035-9210-8aa142d5c764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Create New CFR Form'])[1]/preceding::button[1]</value>
      <webElementGuid>ad171b1b-493c-4355-8fad-b6a941d26599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #ABC-2099-6009417'])[1]/preceding::button[2]</value>
      <webElementGuid>431c1a66-0eca-4387-a6a5-8c6e585a8095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>55f768ba-ed1b-4c3e-b148-8408426a2fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btncfrsave' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>c8e090ab-3516-49be-877a-faf07e1aa244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
