<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Request</name>
   <tag></tag>
   <elementGuidId>5376eac0-f709-4d3b-bda8-e3634f5a377c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;Request&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='Request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38898bbc-9e23-40e0-83d7-9e366600aaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tablinks</value>
      <webElementGuid>62b5244c-a28b-4b9e-9465-e988f6de0337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>4a6c58b1-3b4b-45f7-9daf-6f3678bc7162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>d65c1848-4ee7-4c82-8046-c2e6239a331d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;foiformcontent&quot;]/div[@class=&quot;foitabbedContainer&quot;]/div[@class=&quot;foitabheadercollection foitabheaderCFRG&quot;]/div[@class=&quot;tab&quot;]/div[@class=&quot;tablinks&quot;]</value>
      <webElementGuid>fe5997ae-cd31-4534-b945-6c484d28ad55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='Request']</value>
      <webElementGuid>30fa771a-36be-4666-87ed-aaa68f33941c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>432a5816-742a-406c-95d0-d35baff05543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::div[2]</value>
      <webElementGuid>fd5708dd-6450-4e62-b897-fcd0f27f0ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Call For Records'])[1]/following::div[2]</value>
      <webElementGuid>94b2b1c3-6e56-43a1-b715-96ffca4ad4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CFR Form'])[1]/preceding::div[1]</value>
      <webElementGuid>a1b7c5e0-6336-4fb0-a14c-600e46093126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/preceding::div[2]</value>
      <webElementGuid>64db3718-72f2-48f4-80ea-5ee03f3d3a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request']/parent::*</value>
      <webElementGuid>b6604519-5f96-4920-8baa-a442971ee603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div</value>
      <webElementGuid>11d1b0ce-4663-45ff-b4ec-2ad238f94c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'Request' and (text() = 'Request' or . = 'Request')]</value>
      <webElementGuid>b0df5d9c-d42e-4c7b-af0c-d5e1ee62d1e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
