<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ABC-2099-6009417</name>
   <tag></tag>
   <elementGuidId>742d1a42-6947-4013-8a61-a6cf9cb2bcbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Request']/div/div/form/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf89c0fb-c4ef-4a39-a868-6e278044f410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-6</value>
      <webElementGuid>c3fdfda7-b2f4-4e03-9f3b-01780f8c9153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABC-2099-6009417</value>
      <webElementGuid>e0369455-8d66-4abe-80f1-aac7adfd53f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Request&quot;)/div[@class=&quot;container foi-review-request-container&quot;]/div[@class=&quot;foi-review-container&quot;]/form[@class=&quot;jss1 foi-request-form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]</value>
      <webElementGuid>f6c72adc-1ee5-4f64-bbde-cd9ac8dfb023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div/div</value>
      <webElementGuid>b397b243-9bf3-4d56-a4c2-00e5e5d02c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABC-2099-6009417'])[3]/following::div[2]</value>
      <webElementGuid>5c5b5faf-3070-4ff6-b965-f812a95e8cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Queue'])[1]/following::div[3]</value>
      <webElementGuid>c5dbf112-6588-4d49-bc49-53d41d12f1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IAO Assigned To'])[1]/preceding::div[2]</value>
      <webElementGuid>803a0687-b4fc-4a68-a09b-2f9f5259baed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>8f5dc326-5b41-4785-adea-b1e9a8fd4d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ABC-2099-6009417' or . = 'ABC-2099-6009417')]</value>
      <webElementGuid>a5e0650e-4c21-4dc3-91e9-8618b92370e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
