<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimated Hours_locating</name>
   <tag></tag>
   <elementGuidId>c1bbf19a-b5e8-4bf0-82ac-071acff704f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimatedlocating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimatedlocating']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33160fe9-3906-4939-925a-4b9bd12b45bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d82c11f1-4f25-495b-8d54-4d338da5108e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimatedlocating</value>
      <webElementGuid>6433b7d0-5ea3-422f-bea7-acde83634475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locating</value>
      <webElementGuid>a4a2f034-e546-4439-9c46-503ac1455506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4b9ae4f7-f1af-4637-8863-a1d64d6bc5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>estimatedlocating-label</value>
      <webElementGuid>19064829-729b-4267-bc5b-542069a93fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.25</value>
      <webElementGuid>4b22da29-5566-4b2c-a5a1-0732f2de7371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d8f9d553-c392-408c-a5b5-e19814a3eb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-1uvydh2</value>
      <webElementGuid>8edd54ff-7693-42c8-9545-380c9f116dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1bc58c9c-f072-4079-919a-0f9a1a503cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimatedlocating&quot;)</value>
      <webElementGuid>06268f7c-8815-4677-9be2-5297b44876a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimatedlocating']</value>
      <webElementGuid>d402c1af-8f31-4554-a43b-2fea50f8ba29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ceb52e58-193c-4b43-b914-1925633c6667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>17746fb5-6952-446e-906d-b76baa8d5bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimatedlocating' and @name = 'locating' and @type = 'number']</value>
      <webElementGuid>a53e9461-6041-43d4-9fcd-0f31f34b3cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
