<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Call For RecordsFee EstimateHarms Assess_73e490</name>
   <tag></tag>
   <elementGuidId>fcead3ac-45ab-42b7-9693-842b83bbf72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.MuiList-root.MuiMenu-list.MuiList-padding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-']/div[3]/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>bb0c8721-c096-4aec-84b6-eb0e1a6660cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiMenu-list MuiList-padding</value>
      <webElementGuid>c888d4df-18c9-418b-876c-cd127e73df7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ff57b687-97a8-4876-b85f-2342eaefcf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>50d9505f-2cdb-4376-8bb7-e2d1acb375f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>foi-status-dropdown-label</value>
      <webElementGuid>4e0a7ad2-b3dc-47cb-9c2e-a101ff90348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Call For RecordsFee EstimateHarms AssessmentDeduplicationRecords ReviewMinistry Sign Off</value>
      <webElementGuid>01229f4d-45e7-4b0d-b596-10e22c265d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]</value>
      <webElementGuid>79965f4d-2c6a-4df9-8a66-99016dca7d4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul</value>
      <webElementGuid>8e1dbdc1-97d5-45e0-8ee7-07e68488c247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more comments'])[1]/following::ul[4]</value>
      <webElementGuid>3a2e8cc5-1838-478c-98f8-89e2de94d5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No comments under this filter category'])[1]/following::ul[4]</value>
      <webElementGuid>ccfbd8c7-e6e7-450b-a692-ad8db9f7482c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/ul</value>
      <webElementGuid>6fba112f-c5d0-4a7f-8bd8-bca8925d8a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'Call For RecordsFee EstimateHarms AssessmentDeduplicationRecords ReviewMinistry Sign Off' or . = 'Call For RecordsFee EstimateHarms AssessmentDeduplicationRecords ReviewMinistry Sign Off')]</value>
      <webElementGuid>2038b4ae-7a96-4236-b9af-cc7a224c36da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
