

INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Advanced Education and Skills Training ','BC GOV Ministry', True,'AEST','AED');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Agriculture, Food and Fisheries ','BC GOV Ministry', True,'AFF','AGR');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Attorney General ','BC GOV Ministry', True,'AG','MAG');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Children and Family Development ','BC GOV Ministry', True,'MCF','CFD');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Citizens’ Services ','BC GOV Ministry', True,'CITZ ','CTZ');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Education ','BC GOV Ministry', True,'EDUC ','EDU');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Energy, Mines and Low Carbon Innovation ','BC GOV Ministry', True,'EMLI ','EML');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Environment and Climate Change Strategy ','BC GOV Ministry', True,'ENV ','MOE');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Finance ','BC GOV Ministry', True,'FIN ','FIN');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Forests, Lands, Natural Resource Operations and Rural Development ','BC GOV Ministry', True,'FLNR ','FNR');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Health ','BC GOV Ministry', True,'HLTH ','HTH');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Indigenous Relations and Reconciliation ','BC GOV Ministry', True,'IRR ','IRR');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Jobs, Economic Recovery and Innovation ','BC GOV Ministry', True,'JERI ','JER');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Labour ','BC GOV Ministry', True,'LBR ','LBR');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Mental Health and Addictions ','BC GOV Ministry', True,'MMHA ','MHA');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Municipal Affairs ','BC GOV Ministry', True,'MUNI ','MMA');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Public Safety and Solicitor General ','BC GOV Ministry', True,'PSSG ','PSS');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Social Development and Poverty Reduction ','BC GOV Ministry', True,'SDPR ','MSD');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Tourism, Arts, Culture and Sport ','BC GOV Ministry', True,'TACS ','TAC');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Ministry of Transportation and Infrastructure ','BC GOV Ministry', True,'TRAN ','TRA');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('BC Coroners Service ','Other', True,'','OCC');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('BC Public Service Agency ','Other', True,'','PSA');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Board Resourcing and Development Office ','Other', True,'','BRD');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Community Living BC ','Other', True,'','CLB');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Crown Agencies Secretariat ','Other', True,'','CAS');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Emergency Management BC ','Other', True,'','EMB');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Environmental Assessment Office ','Other', True,'','EAO');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Government Communications and Public Engagement ','Other', True,'','GCP');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Independent Investigations Office ','Other', True,'','IIO');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Office of the Premier ','Other', True,'','OOP');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Liquor Distribution Branch ','Other', True,'','LDB');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Transportation Investment Corporation ','Other', True,'','TIC');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Order of British Columbia Advisory Council ','Other', True,'','OBC');
INSERT INTO public."ProgramAreas"(name, type, isactive, bcgovcode, iaocode) VALUES ('Medal of Good Citizenship Selection Committee ','Other', True,'','MGC');
