"""Manage profile specific variables
"""
import os
#IO Configuration
REDIS_HOST = os.getenv('NOTIFICATION_REDIS_HOST') 
REDIS_PORT = os.getenv('NOTIFICATION_REDIS_PORT')
REDIS_PASSWORD = os.getenv('NOTIFICATION_REDIS_PASSWORD')

# STREAM READER CONFIGURATION - NOTIFICATION
NOTIFICATION_STREAM_KEY = os.getenv('NOTIFICATION_STREAM_KEY')
BLOCK_TIME = 5000
    


# DB Settings
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT')
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USERNAME = os.getenv('DATABASE_USERNAME')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')

# KC Settings
KEYCLOAK_ADMIN_HOST = os.getenv('KEYCLOAK_ADMIN_HOST')
KEYCLOAK_ADMIN_REALM = os.getenv('KEYCLOAK_ADMIN_REALM')
KEYCLOAK_ADMIN_CLIENT_ID = os.getenv('KEYCLOAK_ADMIN_CLIENT_ID')
KEYCLOAK_ADMIN_CLIENT_SECRET = os.getenv('KEYCLOAK_ADMIN_CLIENT_SECRET')
KEYCLOAK_ADMIN_SRVACCOUNT = os.getenv('KEYCLOAK_ADMIN_SRVACCOUNT')
KEYCLOAK_ADMIN_SRVPASSWORD = os.getenv('KEYCLOAK_ADMIN_SRVPASSWORD')
