<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s this)_submitButton</name>
   <tag></tag>
   <elementGuidId>69dbdc0d-3864-4e25-a255-983d833618dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submitButton&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submitButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d29d79f2-d35a-4fe3-aa1d-d1aef0e8abec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>94d103a6-822b-4967-a025-6e05337d0ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>d68f4d46-d28e-4b07-8c6f-50e3bcd230fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit Payment</value>
      <webElementGuid>3d5e6c86-2eb1-4ca2-bfdf-493de6add223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SubmitTrans();</value>
      <webElementGuid>6bfeb477-e5ae-41be-a3a3-8c0c5736f217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPayment&quot;)/table[2]/tbody[1]/tr[12]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/input[1]</value>
      <webElementGuid>e1beb776-e2c7-407e-908b-8537c4802e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submitButton']</value>
      <webElementGuid>c48bde21-1cb9-451a-ac7f-cc87c3bec668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPayment']/table[2]/tbody/tr[12]/td/table/tbody/tr/td[3]/input</value>
      <webElementGuid>c341ef1c-f0a5-4fb7-89e1-d1c3e00cf417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>e8f141c6-c33d-4fa4-8680-d0e5e95cfc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'submitButton']</value>
      <webElementGuid>2cb8b279-632f-4e74-8e8e-c345eea4f377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
