<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post comment</name>
   <tag></tag>
   <elementGuidId>140c7ab5-9a0f-4b5e-90b7-c7529a48bc7b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'postBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-lg-1.paperplanecontainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@id='Comments']&#xd;
  //div[contains(@class,'inputBox')][not(contains(@style,'display: none'))]&#xd;
  //div[contains(@class,'newCommentInputActions')]&#xd;
  //button[contains(@class,'btn-save') and @type='button' and not(@disabled)]&#xd;
)[last()]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de52a252-1ebb-44ea-9aba-fa6030681131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>postBtn</value>
      <webElementGuid>6879065d-32e8-4798-87e0-9f781c2de956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Comments&quot;)/div[@class=&quot;section&quot;]/div[@class=&quot;inputBox&quot;]/div[@class=&quot;inputActions&quot;]/div[@class=&quot;col-lg-1 paperplanecontainer&quot;]/button[@class=&quot;postBtn&quot;]</value>
      <webElementGuid>d8cce787-f685-4c85-a506-657a131a7467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Comments']/div/div[3]/div/div[2]/button</value>
      <webElementGuid>17ac1abe-516c-483b-a7ce-c57f4cb1a9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Comment'])[1]/following::div[17]</value>
      <webElementGuid>c28a31fc-2ade-4a9c-b80d-476a94cc812a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #U-00512'])[2]/following::div[18]</value>
      <webElementGuid>4a40b38f-6285-439a-ad17-0d538f1a804d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Comments'])[1]/preceding::div[1]</value>
      <webElementGuid>0408b9c6-1a17-407f-83a2-3b8b59411a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request History'])[1]/preceding::div[1]</value>
      <webElementGuid>4c91a0ef-6f25-45dd-9ca5-06fccd8f8186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div[2]</value>
      <webElementGuid>e375f4c9-1f2e-4071-bed7-1a6988a3ede0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
