<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tagging option 4</name>
   <tag></tag>
   <elementGuidId>958304c6-89ca-4da7-a7d3-f5a0f21f369e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mention-option-fv8ok-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Comments']/div/div[2]/form/div[3]/div[4]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mention-option-fv8ok-1' and (text() = 'Andrews, Arielle' or . = 'Andrews, Arielle')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f18e614d-c367-4ba6-9fa5-9429331c1319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>myz2dw1</value>
      <webElementGuid>677872f0-442b-4829-9790-b5a9b0732126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ed6d8cf1-c465-4587-94c0-6a6e90265081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mention-option-fv8ok-1</value>
      <webElementGuid>22be32b0-b8a6-4f7b-b915-1d73f7585577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>058bbe92-aa31-4b76-915c-94bdd8fa36fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andrews, Arielle</value>
      <webElementGuid>56edf1bf-c53e-4b98-98c4-d402f22f238b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mention-option-fv8ok-1&quot;)</value>
      <webElementGuid>1dbe8830-58eb-4230-b66f-ce9427cdd6b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mention-option-fv8ok-1']</value>
      <webElementGuid>147a2fef-d1a0-44f7-9e20-ac7aaad2a986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Comments']/div/div[3]/form/div[3]/div[2]/div</value>
      <webElementGuid>babccb2e-b990-47cf-b2d0-ef4680e455a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Antony, Abin'])[1]/following::div[2]</value>
      <webElementGuid>95dabfae-537d-4dd1-a3fa-6b580a4ec321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@'])[1]/following::div[5]</value>
      <webElementGuid>e1e4fae6-d020-4475-a466-fcffb6ce4642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viswanath, Divya'])[1]/preceding::div[1]</value>
      <webElementGuid>961850d7-4074-4a3d-a541-bfd50c68f51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>b71bae62-121e-44a6-8c44-d18ff78c706f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mention-option-fv8ok-1' and (text() = 'Andrews, Arielle' or . = 'Andrews, Arielle')]</value>
      <webElementGuid>c9abb7a4-4822-43a1-a506-c556e6d9f7e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
