<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_A request can only be restricted when it is assigned to one team member, not a team queue</name>
   <tag></tag>
   <elementGuidId>b73cc165-2d1e-423d-83e7-d3fe5ceca70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='restricted-modal-text']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.confirmation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a969153b-af2f-4882-bda6-17665dc3a6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirmation-message</value>
      <webElementGuid>d8f19ec3-da7e-4632-bda9-8f73d77231a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A request can only be restricted when it is assigned to one team member, not a team queue.</value>
      <webElementGuid>6acee9d5-7c8c-40e2-ac14-21072839cf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restricted-modal-text&quot;)/div[@class=&quot;modal-msg&quot;]/div[@class=&quot;confirmation-message&quot;]</value>
      <webElementGuid>3aa6e404-bf8a-459c-9f0e-4db6933d56a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='restricted-modal-text']/div/div</value>
      <webElementGuid>fe25ffcc-b359-44e4-b56a-be330f33a0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[3]</value>
      <webElementGuid>11ce5c97-9a40-4be7-b8d1-0df256517b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Restrict File'])[1]/following::div[3]</value>
      <webElementGuid>c73ebded-54e4-4688-b30f-3f3229638f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Change'])[1]/preceding::div[2]</value>
      <webElementGuid>8f0ac68a-2a0a-4c3f-a80d-138885b0c327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[2]</value>
      <webElementGuid>5cf17018-f3c8-4ba3-a47e-00b04f0e1938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A request can only be restricted when it is assigned to one team member, not a team queue.']/parent::*</value>
      <webElementGuid>f1ba8301-9566-4d15-8522-011c18cfb14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>db0f9c98-b2cf-41bd-9fd8-5391ccd32de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'A request can only be restricted when it is assigned to one team member, not a team queue.' or . = 'A request can only be restricted when it is assigned to one team member, not a team queue.')]</value>
      <webElementGuid>897646a3-62fc-4db7-9439-614595a0ad21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
