NODE_ENV=production
IMAGE_NAMESPACE=04d1a3-tools
TAG_NAME=latest
REACT_APP_APPLICATION_NAME=forms-flow-ai-web
NAME=forms-flow-ai-web
IMAGE_NAME=forms-flow-ai-web
REACT_APP_APPLICATION_NAME=foi-flow
REACT_APP_KEYCLOAK_URL=
REACT_APP_KEYCLOAK_URL_REALM=
REALM=
REACT_APP_SOCKETIO_CONNECT_URL=
REACT_APP_SOCKETIO_CONNECT_NONCE=
REACT_APP_SOCKETIO_RECONNECTION_DELAY_MAX=30000
REACT_APP_SOCKETIO_RECONNECTION_DELAY=15000
REACT_APP_AXIS_API_URL=
REACT_APP_FOI_FLOW_REPORTING_URL=
REACT_APP_CAMUNDA_API_URI=
REACT_APP_FOI_BASE_API_URL=
FFAWEB_URL=
REACT_APP_FORMIO_JWT_SECRET=
REACT_APP_WEBSOCKET_ENCRYPT_KEY=
REACT_APP_FORMS_SERVER_URL=
REACT_APP_ANONYMOUS_ID=
REACT_APP_USER_RESOURCE_FORM_ID=
REACT_APP_STAFF_DESIGNER_ID=
REACT_APP_STAFF_REVIEWER_ID=
REACT_APP_CLIENT_ID=
REACT_APP_CLIENT_ROLE=formsflow-client
REACT_APP_STAFF_DESIGNER_ROLE=formsflow-designer
REACT_APP_STAFF_REVIEWER_ROLE=formsflow-reviewer
REACT_APP_API_BASE_URL=