<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_CFR Status</name>
   <tag></tag>
   <elementGuidId>8ebc1620-14e4-46d8-95bc-d09ef7333731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfrStatus-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='cfrStatus-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fb761224-4e21-408e-a60a-3087a40c7e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-outlined MuiFormLabel-root MuiFormLabel-colorPrimary Mui-disabled MuiFormLabel-filled Mui-required css-u9osun</value>
      <webElementGuid>6d1b414e-1b69-4d7b-a958-a646a3155ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-shrink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61c25d0e-c6db-4b84-8144-ab48c7ef44da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cfrStatus</value>
      <webElementGuid>b1473588-46f6-463e-9184-f8761614b5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfrStatus-label</value>
      <webElementGuid>ea3f64d4-7a6e-4bae-ae22-6d72551b374b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CFR Status *</value>
      <webElementGuid>05ac143e-74e1-4532-93fb-0be13118b616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfrStatus-label&quot;)</value>
      <webElementGuid>96264996-7cbd-45c1-a757-cb5c9b5f53c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='cfrStatus-label']</value>
      <webElementGuid>953b11b0-2bc1-4b94-a363-3d136200fc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cfrstatuscontainer']/div/label</value>
      <webElementGuid>b92218cf-c75f-458f-9521-a186a3a2ce96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version 1'])[1]/following::label[1]</value>
      <webElementGuid>5e72285f-41e1-4482-9150-caeafcbe9fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABC-2099-7734023'])[5]/following::label[1]</value>
      <webElementGuid>d767ae98-a987-4fa9-b4cb-68107cc6c951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/preceding::label[1]</value>
      <webElementGuid>da86e40d-bb80-4ea2-87d1-1c3f2a36bbcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CFR Status']/parent::*</value>
      <webElementGuid>dcb6decc-c526-445c-81a7-b0eaf802907f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/label</value>
      <webElementGuid>5224b10b-d119-4fb0-80c8-8262ce31c31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'cfrStatus-label' and (text() = 'CFR Status *' or . = 'CFR Status *')]</value>
      <webElementGuid>02854428-5db2-441e-a341-5a5fb9887977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
