<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_foiedu, foiedu_selectchk14988</name>
   <tag></tag>
   <elementGuidId>eeba0d59-4eea-4d13-856c-d5b3220e3df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectchk14988']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectchk14988</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d33390f-fbf7-428c-ad7e-150875dd6dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e10cec54-5a08-400a-8d65-abceb08578af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark record-checkmark</value>
      <webElementGuid>cc6ceeed-730c-4111-a949-f505af1d8209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectchk14988</value>
      <webElementGuid>bbc2b77d-261a-47be-9d70-c9d3736e280c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iaocode</name>
      <type>Main</type>
      <value>12403</value>
      <webElementGuid>c2f2a73a-c9f0-42ea-b5e6-4f64e72cecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectchk14988&quot;)</value>
      <webElementGuid>290bc489-c4b8-4a13-958a-6d5f28f03294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectchk14988']</value>
      <webElementGuid>c2810df7-b942-4de4-8951-79030b0ed0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Records']/div/div[2]/div[6]/div[4]/div/input</value>
      <webElementGuid>bab8f3a6-fa5f-406b-9fec-f7473b519fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>22d62e91-fb93-4ab7-8632-8f0754bb8f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectchk14988']</value>
      <webElementGuid>9e24075b-64f6-441b-b03b-82107de61f95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
