<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_INCOMPATIBLE_selectchk14989</name>
   <tag></tag>
   <elementGuidId>f147902d-d962-4f05-bb09-4094c28b4901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectchk14989']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectchk14989</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5393693f-d8e2-45b2-9b23-f299e3c9760f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>684571b5-21f9-4b23-8263-57420f15918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark record-checkmark</value>
      <webElementGuid>54da8396-7c59-4309-a0c2-743cd4f372f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectchk14989</value>
      <webElementGuid>1d1d080e-e3a0-493e-ac0b-727f5421031d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iaocode</name>
      <type>Main</type>
      <value>12404</value>
      <webElementGuid>a1d24588-b97d-4eea-88b2-2aed5c8e236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectchk14989&quot;)</value>
      <webElementGuid>f684e237-62a1-4f71-ba1d-75ed6198928e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectchk14989']</value>
      <webElementGuid>75e3de25-9397-44e1-904e-82c5b84c3ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Records']/div/div[2]/div[6]/div/div/input</value>
      <webElementGuid>3d4caf58-a39e-4ce8-8c97-4aff84ce22f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div/div/input</value>
      <webElementGuid>92e69b50-3c06-41e1-979c-55f507b2d1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectchk14989']</value>
      <webElementGuid>0b843e18-dfee-407d-ba59-f65dc609b19c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
