<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attachment_uploaded2</name>
   <tag></tag>
   <elementGuidId>07df3e74-bd73-4d59-84f1-23abcb963713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='state-change-dialog-description']/section/div/div/article/section/ol/li[2]/section/div/div/aside/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
