<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_input</name>
   <tag></tag>
   <elementGuidId>560d3f0b-30cc-41ee-ba96-eea6154c3665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'fileupload' and @class = 'file-upload-input-multiple']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>088a98d0-b12c-4231-8115-03ecc167b0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileupload</value>
      <webElementGuid>fca54795-f135-4fca-9b33-6d7b13bb95b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple accept</name>
      <type>Main</type>
      <value>application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword,image/bmp,image/gif,image/jpeg,image/png,image/svg+xml,image/tiff,image/webp,application/vnd.ms-excel.sheet.macroEnabled.12,.msg,.eml,.xls,.xlsx,.doc,.docx,.ics,.json,.shx,.shp,.dbf,.kml,.kmz,.geojson,.cpg,.prj,.sbn,.sbx,.gml,.gdb,.freelist,.atx,.gpkg,.mbtiles,.mpk,.wkt,.las,.lasd,.laz,.dwf,.dwg,.dxf,.csv,.txt,.png,.jpg</value>
      <webElementGuid>4e92858f-d56e-47db-aaab-7caaec1ef7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-upload-input-multiple</value>
      <webElementGuid>04905c58-6ef8-4f31-acb9-26de73812658</webElementGuid>
   </webElementProperties>
</WebElementEntity>
