<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_test2.docx_fas fa-times-circle foi-file-close</name>
   <tag></tag>
   <elementGuidId>14c5c04f-c519-4a45-9ea6-4388501354e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-times-circle.foi-file-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='state-change-dialog-description']/section/div/div/article/section/ol/li/section/div/div/aside/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;state-change-dialog-description&quot;)/section[@class=&quot;file-upload-container&quot;]/div[@class=&quot;row file-upload-preview&quot;]/div[@class=&quot;file-upload-column&quot;]/article[@class=&quot;file-preview-container&quot;]/section[1]/ol[@class=&quot;ol-display-none&quot;]/li[@class=&quot;ol-display-none&quot;]/section[1]/div[1]/div[1]/aside[1]/i[@class=&quot;fas fa-times-circle foi-file-close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>53d1e141-3b66-43f0-9770-9ef7311385b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-times-circle foi-file-close</value>
      <webElementGuid>93b7c707-0f38-4a6b-8c35-095c99a57ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state-change-dialog-description&quot;)/section[@class=&quot;file-upload-container&quot;]/div[@class=&quot;row file-upload-preview&quot;]/div[@class=&quot;file-upload-column&quot;]/article[@class=&quot;file-preview-container&quot;]/section[1]/ol[@class=&quot;ol-display-none&quot;]/li[@class=&quot;ol-display-none&quot;]/section[1]/div[1]/div[1]/aside[1]/i[@class=&quot;fas fa-times-circle foi-file-close&quot;]</value>
      <webElementGuid>87ee4623-5ceb-4ef7-a1f0-77e971e7edac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='state-change-dialog-description']/section/div/div/article/section/ol/li/section/div/div/aside/i</value>
      <webElementGuid>ffe9e2c4-df79-4927-a11d-4f27b382125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/i</value>
      <webElementGuid>b0c58bae-13ec-46b0-95c9-48f41f77a1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
