<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Files_file-upload-input</name>
   <tag></tag>
   <elementGuidId>b88dae82-9d29-4473-8c84-d08e3cd6a061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[23]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'file']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.file-upload-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca59ce9f-c981-462f-be16-93aa14290c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-upload-input</value>
      <webElementGuid>51926a61-5eb1-4aec-bd0e-48a20690175a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e5111d7e-d773-4dab-b250-ab663ecdf078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword,image/bmp,image/gif,image/jpeg,image/png,image/svg+xml,image/tiff,image/webp,application/vnd.ms-excel.sheet.macroEnabled.12,.msg</value>
      <webElementGuid>84264227-185d-4725-8d9b-08dcf3697414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state-change-dialog-description&quot;)/section[@class=&quot;file-upload-container&quot;]/div[@class=&quot;row file-upload-preview&quot;]/div[@class=&quot;file-upload-column file-upload-column-2&quot;]/input[@class=&quot;file-upload-input&quot;]</value>
      <webElementGuid>b89cc792-1f8a-47b9-807b-fba2c5c38eb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[23]</value>
      <webElementGuid>5bfa4a59-94f4-460d-8c98-6705261761b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='state-change-dialog-description']/section/input</value>
      <webElementGuid>420a24a0-72cb-4b00-a3d2-10275d58b70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/input</value>
      <webElementGuid>e1faae28-9131-4e70-9718-2f9a0d52c793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
