<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_usersendemailmessage</name>
   <tag></tag>
   <elementGuidId>cb0491c4-ee04-49fa-b01a-522d24d43bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@name='reply_null'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8305735d-6f82-45cd-bebc-f77244a6be8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-halfdiv-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>03c465f2-a852-4204-b69b-6abb6f67fd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reply_null</value>
      <webElementGuid>c5b7722c-85ec-453b-b0b6-2ac9f3de37ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>halfDiv</value>
      <webElementGuid>9ed8cefa-e16d-431e-b535-a00a4313747b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flex, Intake  |  2023 Mar 14 | 11:42 AM Dear Firstname LastnamePlease see the attached regarding your FOI Request. Please review the attached letter, as you have additional options outside of paying the fee including narrowing your request, or requesting a fee waiver.If you would like to pay your estimate online, please click on this link: Pay Online Thank you,Flex Teamtest2.pdf</value>
      <webElementGuid>6ca02945-8bd0-4117-bc02-351bc5c3fa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactApplicant&quot;)/div[@class=&quot;contact-applicant-container&quot;]/div[3]/div[@class=&quot;commentsection&quot;]/div[@class=&quot;halfDiv&quot;]</value>
      <webElementGuid>5574239b-0480-4e4e-bc79-abfdc2cb53d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@name='reply_null'])[2]</value>
      <webElementGuid>379759d2-b98b-4ef1-a4f5-ebef6479d703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactApplicant']/div/div[3]/div[2]/div</value>
      <webElementGuid>fb02312a-4046-4d4f-86c7-911a2630b579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Estimate Payment Receipt.pdf'])[1]/following::div[2]</value>
      <webElementGuid>9ed5d610-687f-404d-9edd-45421eb96e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 300.80'])[1]/following::div[5]</value>
      <webElementGuid>d6762a3c-4e69-455e-bc70-8cf346f512a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div[2]/div</value>
      <webElementGuid>a00fe5b9-a2b2-4e72-af59-3faffc035c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'reply_null' and (text() = 'Flex, Intake  |  2023 Mar 14 | 11:42 AM Dear Firstname LastnamePlease see the attached regarding your FOI Request. Please review the attached letter, as you have additional options outside of paying the fee including narrowing your request, or requesting a fee waiver.If you would like to pay your estimate online, please click on this link: Pay Online Thank you,Flex Teamtest2.pdf' or . = 'Flex, Intake  |  2023 Mar 14 | 11:42 AM Dear Firstname LastnamePlease see the attached regarding your FOI Request. Please review the attached letter, as you have additional options outside of paying the fee including narrowing your request, or requesting a fee waiver.If you would like to pay your estimate online, please click on this link: Pay Online Thank you,Flex Teamtest2.pdf')]</value>
      <webElementGuid>0dacfd9f-d96b-4c64-84f9-a17ec29dee7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
