<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Original Due Date_originalDueDate</name>
   <tag></tag>
   <elementGuidId>bd86b9c5-22cc-4c01-b876-ec8a764de9ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#originalDueDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='originalDueDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7129e82f-f2e4-4753-ba58-177a66f10520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27c1eba9-d820-401d-a1d0-4317ff8cc7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>originalDueDate</value>
      <webElementGuid>90c8ed9b-b79f-49ff-93ae-f6842cf6ceef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f82aabc2-0916-4220-a440-c59dccb51e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>dueDate-label</value>
      <webElementGuid>807f58d7-1d8b-418c-aa3d-b31a16f2cc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input Mui-disabled Mui-disabled</value>
      <webElementGuid>fe396659-a2c4-47c5-b27c-8c71a79955fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N/A</value>
      <webElementGuid>d3466143-9e1d-4870-b1e1-ff0fa07cd116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;originalDueDate&quot;)</value>
      <webElementGuid>491a0bef-26ca-4fe0-bd3b-bf199ed3d0d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='originalDueDate']</value>
      <webElementGuid>da042f4b-fa2b-4f41-a22c-6cfd1275e3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div[7]/div/div[2]/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>3d3899f5-85d2-4e02-9ebb-e46b7ba980a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>eea9ac8d-d314-46df-89a5-d14dda797bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'originalDueDate' and @type = 'text']</value>
      <webElementGuid>434e6217-aa1c-449e-9790-efa565a76f4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
