<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Legislated Due Date_dueDate</name>
   <tag></tag>
   <elementGuidId>5d344928-e12e-4ebb-979d-2557aa21f0e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dueDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dueDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80c66a07-850a-4c21-b530-6a55ea06a7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>667353e0-678c-4fd1-89b7-48ab71ab5225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>0eaf15c7-92ea-44f4-b80c-5940fbe7e885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3af2ee69-4d4b-4ced-a7b2-9f63892a0345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>dueDate-label</value>
      <webElementGuid>efde5767-773f-43c3-af97-7c1bf9ee4f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input Mui-disabled Mui-disabled</value>
      <webElementGuid>7d8f1719-4d61-4369-bb23-79a5604f631a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N/A</value>
      <webElementGuid>84961036-7015-44ae-9751-f4d2c533018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dueDate&quot;)</value>
      <webElementGuid>5ba80685-a9b1-4e1d-a11d-929c51aa05f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dueDate']</value>
      <webElementGuid>701a1028-9c11-4974-9369-cdd4a84ffb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Request']/div/div/form/div[7]/div/div[2]/div/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>aca6bcb6-0804-4bec-aff0-96b16ff0b6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>83489e03-c43d-4b43-aaf5-18821760a2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dueDate' and @type = 'text']</value>
      <webElementGuid>744839d2-4533-4f13-9790-e6201b067a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
