"""empty message

Revision ID: 07a15d90db59
Revises: 7cbff407743e
Create Date: 2021-08-09 15:40:20.322170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a15d90db59'
down_revision = '7cbff407743e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestPersonalAttributes',
    sa.Column('foirequestpersonalattributeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attributevalue', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('personalattributeid', sa.Integer(), nullable=True),
    sa.Column('foirequestid', sa.Integer(), nullable=True),
    sa.Column('foirequestversion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foirequestid', 'foirequestversion'], ['FOIRequests.foirequestid', 'FOIRequests.version'], ),
    sa.ForeignKeyConstraint(['personalattributeid'], ['PersonalInformationAttributes.attributeid'], ),
    sa.PrimaryKeyConstraint('foirequestpersonalattributeid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestPersonalAttributes')
    # ### end Alembic commands ###
