"""empty message

Revision ID: 092981b8477d
Revises: 0cfa2e153eb6
Create Date: 2025-01-10 16:26:13.514838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '092981b8477d'
down_revision = '0cfa2e153eb6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, notificationtypelabel, isactive) values (\'Exemption Request\', \'Exemption Request\', \'exemptionrequest\', true);commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, notificationtypelabel, isactive) values (\'Exemption Approved\', \'Exemption Approved\', \'exemptionapproved\', true);commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, notificationtypelabel, isactive) values (\'Exemption Denied\', \'Exemption Denied\', \'exemptiondenied\', true);commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from  public."NotificationTypes" where name in (\'Exemption Request\');commit;')
    op.execute('delete from  public."NotificationTypes" where name in (\'Exemption Approved\');commit;')
    op.execute('delete from  public."NotificationTypes" where name in (\'Exemption Denied\');commit;')
    # ### end Alembic commands ###