"""empty message

Revision ID: 10aa6d69aeed
Revises: 67e0b98b63ea
Create Date: 2024-04-29 10:00:19.620294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10aa6d69aeed'
down_revision = '67e0b98b63ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.add_column('FOIMinistryRequests', sa.Column('axislanpagecount', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIMinistryRequests', 'axislanpagecount')
    # ### end Alembic commands ###
