"""Add On-Hold Application-Fee state to FOIRequestStatuses

Revision ID: 1491b3126887
Revises: aacdbca19a47
Create Date: 2023-09-26 12:46:12.187207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1491b3126887'
down_revision = 'aacdbca19a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sql = '''INSERT INTO "FOIRequestStatuses" (name, description, isactive) VALUES ('App Fee Owing', 'On Hold for Application Fee', true)'''
    op.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sql = '''DELETE FROM "FOIRequestStatuses" WHERE name = 'App Fee Owing';'''
    op.execute(sql)