"""empty message

Revision ID: 19e3f06e7a32
Revises: 2f06c40a6f46
Create Date: 2022-01-10 16:34:22.877096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e3f06e7a32'
down_revision = '2f06c40a6f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('update  public."NotificationTypes" set name=\'IAO Assignment\', description=\'IAO Assignment\' where name=\'Assignment\';commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Ministry Assignment\', \'Ministry Assignment\', true);commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'CFR Due Reminder\', \'CFR Due Reminder\', true);commit;')  
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Legislative Due Reminder\', \'Legislative Due Reminder\', true);commit;')  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('update  public."NotificationTypes" set name=\'Assignment\', description=\'Assignment\' where name=\'IAO Assignment\';commit;')
    op.execute('delete from  public."NotificationTypes" where name in (\'Ministry Assignment\',\'CFR Due Reminder\',\'Legislative Due Reminder\');commit;')
    # ### end Alembic commands ###
