"""empty message

Revision ID: 1aadec56e7f2
Revises: 81e6ac3ba248
Create Date: 2021-07-21 15:28:33.814563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aadec56e7f2'
down_revision = '81e6ac3ba248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('assignedto', sa.String(length=120), nullable=True))
    op.add_column('FOIRawRequests', sa.Column('updatedby', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'updatedby')
    op.drop_column('FOIRawRequests', 'assignedto')
    # ### end Alembic commands ###
