"""empty message

Revision ID: 1dba7b01aae2
Revises: 49274e42cd98
Create Date: 2026-03-11 13:14:48.296340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dba7b01aae2'
down_revision = '49274e42cd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('version', sa.Integer(), nullable=True))
    op.execute('UPDATE "FOIProactiveDisclosureRequests" SET version = 1 WHERE version IS NULL')
    op.alter_column('FOIProactiveDisclosureRequests', 'version', nullable=False)
    op.drop_constraint('FOIProactiveDisclosureRequests_pkey', 'FOIProactiveDisclosureRequests', type_='primary')
    op.create_primary_key('FOIProactiveDisclosureRequests_pkey', 'FOIProactiveDisclosureRequests', ['proactivedisclosureid', 'version'])
    op.Column('earliesteligiblepublicationdate', sa.DateTime()),
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('pdpublicationstatus_id', sa.Integer(), nullable=True))
    op.execute('UPDATE "FOIProactiveDisclosureRequests" SET pdpublicationstatus_id = (SELECT oipublicationstatusid FROM "OpenInfoPublicationStatuses" WHERE name = \'Do Not Publish\' LIMIT 1) WHERE pdpublicationstatus_id IS NULL')
    op.alter_column('FOIProactiveDisclosureRequests', 'pdpublicationstatus_id', nullable=False)
    op.create_foreign_key('fk_foi_proactive_pdpublicationstatus_id', 'FOIProactiveDisclosureRequests', 'OpenInfoPublicationStatuses', ['pdpublicationstatus_id'], ['oipublicationstatusid'])
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('processingstatus', sa.String(length=120), nullable=True))
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('processingmessage', sa.String(length=250), nullable=True))
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('sitemap_pages', sa.String(length=120), nullable=True))
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('isactive', sa.Boolean(), default=False))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_foi_proactive_pdpublicationstatus_id', 'FOIProactiveDisclosureRequests', type_='foreignkey')
    op.drop_column('FOIProactiveDisclosureRequests', 'isactive')
    op.drop_column('FOIProactiveDisclosureRequests', 'sitemap_pages')
    op.drop_column('FOIProactiveDisclosureRequests', 'processingmessage')
    op.drop_column('FOIProactiveDisclosureRequests', 'processingstatus')
    op.drop_column('FOIProactiveDisclosureRequests', 'pdpublicationstatus_id')
    op.drop_column('FOIProactiveDisclosureRequests', 'version')
    # ### end Alembic commands ###
