"""FOIProactiveDisclosureRequests-Field updates

Revision ID: 1dba7b01aae2
Revises: c94f5a9b3e21
Create Date: 2026-03-11 13:14:48.296340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dba7b01aae2'
down_revision = 'c94f5a9b3e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIProactiveDisclosureRequests',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1')
    )
    op.execute("""
        DO $$ DECLARE
            pk_name text;
        BEGIN
            SELECT constraint_name INTO pk_name 
            FROM information_schema.table_constraints 
            WHERE table_name iLike 'FOIProactiveDisclosureRequests' 
              AND constraint_type = 'PRIMARY KEY';
            
            IF pk_name IS NOT NULL THEN
                EXECUTE 'ALTER TABLE "FOIProactiveDisclosureRequests" DROP CONSTRAINT "' || pk_name || '" CASCADE';
            END IF;
        END $$;
    """)
    op.create_primary_key('FOIProactiveDisclosureRequests_pkey', 'FOIProactiveDisclosureRequests', ['proactivedisclosureid', 'version'])
    op.execute('ALTER TABLE "FOIProactiveDisclosureRequests" ALTER COLUMN version DROP DEFAULT')
    
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('oipublicationstatus_id', sa.Integer(), nullable=True))
    op.execute('UPDATE "FOIProactiveDisclosureRequests" SET oipublicationstatus_id = (SELECT oipublicationstatusid FROM "OpenInfoPublicationStatuses" WHERE name = \'Do Not Publish\' LIMIT 1) WHERE oipublicationstatus_id IS NULL')
    op.alter_column('FOIProactiveDisclosureRequests', 'oipublicationstatus_id', nullable=False)
    op.create_foreign_key('fk_foi_proactive_oipublicationstatus_id', 'FOIProactiveDisclosureRequests', 'OpenInfoPublicationStatuses', ['oipublicationstatus_id'], ['oipublicationstatusid'])
    
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('earliesteligiblepublicationdate', sa.DateTime(), nullable=True))
    op.execute("""
    UPDATE "FOIProactiveDisclosureRequests" 
    SET earliesteligiblepublicationdate = publicationdate
    WHERE earliesteligiblepublicationdate IS NULL
    """)
    op.alter_column('FOIProactiveDisclosureRequests', 'earliesteligiblepublicationdate', nullable=False)

    op.add_column('FOIProactiveDisclosureRequests', sa.Column('processingstatus', sa.String(length=120), nullable=True))
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('processingmessage', sa.String(length=250), nullable=True))
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('sitemap_pages', sa.String(length=120), nullable=True))
    op.add_column('FOIProactiveDisclosureRequests', sa.Column('isactive', sa.Boolean(), nullable=False, server_default='false'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_foi_proactive_oipublicationstatus_id', 'FOIProactiveDisclosureRequests', type_='foreignkey')

    op.drop_column('FOIProactiveDisclosureRequests', 'isactive')
    op.drop_column('FOIProactiveDisclosureRequests', 'sitemap_pages')
    op.drop_column('FOIProactiveDisclosureRequests', 'processingmessage')
    op.drop_column('FOIProactiveDisclosureRequests', 'processingstatus')
    op.drop_column('FOIProactiveDisclosureRequests', 'oipublicationstatus_id')
    op.drop_column('FOIProactiveDisclosureRequests', 'earliesteligiblepublicationdate')
    op.drop_column('FOIProactiveDisclosureRequests', 'version')
    # ### end Alembic commands ###
