"""empty message

Revision ID: 257a134400b8
Revises: f541c6849055
Create Date: 2021-07-08 15:56:15.071736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257a134400b8'
down_revision = 'f541c6849055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApplicantCategories',
    sa.Column('applicantcategoryid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('applicantcategoryid')
    )
    op.create_table('ProgramAreas',
    sa.Column('programareaid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortname', sa.String(length=125), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('programareaid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProgramAreas')
    op.drop_table('ApplicantCategories')
    # ### end Alembic commands ###
