"""empty message

Revision ID: 27e2c0dd4c3c
Revises: cb8806d322d8
Create Date: 2021-07-08 10:08:53.028617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e2c0dd4c3c'
down_revision = 'cb8806d322d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'version')
    # ### end Alembic commands ###
