"""empty message

Revision ID: 2a89e8f8f691
Revises: b659546dc7e4
Create Date: 2021-08-09 14:53:16.924938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a89e8f8f691'
down_revision = 'b659546dc7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RequestorTypes',
    sa.Column('requestortypeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('requestortypeid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RequestorTypes')
    # ### end Alembic commands ###
