"""empty message

Revision ID: 2b4820ee2300
Revises: 6945aa07480d
Create Date: 2022-05-26 12:06:29.360367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b4820ee2300'
down_revision = '6945aa07480d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''update public."ProgramAreas"
        set name = 'Ministry of Transportation and Transit' where bcgovcode = 'TRAN';
        update public."ProgramAreas"
        set name = 'Ministry of Education and Child Care' where bcgovcode = 'ECC';
        update public."ProgramAreas"
        set name = 'Ministry of Post-Secondary and Future Skills' where bcgovcode = 'PSE';
        update public."ProgramAreas"
        set name = 'Ministry of Jobs, Economic Development and Innovation' where bcgovcode = 'JED';
        update public."ProgramAreas"
        set isactive = false where iaocode in ('AED', 'BRD', 'EDU', 'EML', 'JER','MHA', 'MMA');
    ''')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''update public."ProgramAreas"
        set name = 'Ministry of Transportation and Infrastructure' where bcgovcode = 'TRAN';
        update public."ProgramAreas"
        set name = 'Education and Child Care' where bcgovcode = 'ECC';
        update public."ProgramAreas"
        set name = 'Post-Secondary Education and Future Skills' where bcgovcode = 'PSE';
        update public."ProgramAreas"
        set name = 'Jobs, Economic Development and Innovation' where bcgovcode = 'JED';
        update public."ProgramAreas"
        set isactive = true where iaocode in ('AED', 'BRD', 'EDU', 'EML', 'JER','MHA', 'MMA');
    ''')
    # ### end Alembic commands ###
