"""empty message

Revision ID: 2bf3c5d25742
Revises: 3084c5961187
Create Date: 2022-05-26 12:06:29.360367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bf3c5d25742'
down_revision = '3084c5961187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestCFRFees',
    sa.Column('cfrfeeid', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('ministryrequestid', sa.Integer(), nullable=False),
    sa.Column('ministryrequestversion', sa.Integer(), nullable=True),    
    sa.Column('feedata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('overallsuggestions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['ministryrequestid', 'ministryrequestversion'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.PrimaryKeyConstraint('cfrfeeid' , 'version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestCFRFees')
    # ### end Alembic commands ###
