"""empty message

Revision ID: 2bf3c5d25742
Revises: 22fa7e4ccd1a
Create Date: 2022-05-26 12:06:29.360367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bf3c5d25742'
down_revision = '22fa7e4ccd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    cfrfeestatus_stage_table =  op.create_table('CFRFeeStatuses',
    sa.Column('cfrfeestatusid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),  
    sa.PrimaryKeyConstraint('cfrfeestatusid')
    )
    
    op.bulk_insert(
        cfrfeestatus_stage_table,
        [
            {'name':'review','isactive':True, 'description': 'In Review'},
            {'name':'approved','isactive':True, 'description': 'Approved'},
            {'name':'clarification','isactive':True, 'description': 'Clarification'}, 
        ]
    )
    
    op.create_table('FOIRequestCFRFees',
    sa.Column('cfrfeeid', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('ministryrequestid', sa.Integer(), nullable=False),
    sa.Column('ministryrequestversion', sa.Integer(), nullable=True),    
    sa.Column('feedata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('overallsuggestions', sa.Text(), nullable=True),
    sa.Column('cfrfeestatusid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['ministryrequestid', 'ministryrequestversion'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version']),
    sa.ForeignKeyConstraint(['cfrfeestatusid'], ['CFRFeeStatuses.cfrfeestatusid']),
    sa.PrimaryKeyConstraint('cfrfeeid' , 'version')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestCFRFees')
    op.drop_table('CFRFeeStatuses')
    # ### end Alembic commands ###
