"""empty message

Revision ID: 2c15a7379da4
Revises: 2a89e8f8f691
Create Date: 2021-08-09 15:05:46.937974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c15a7379da4'
down_revision = '2a89e8f8f691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestApplicants',
    sa.Column('foirequestapplicantid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('middlename', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('alsoknownas', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('businessname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('foirequestapplicantid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestApplicants')
    # ### end Alembic commands ###
