"""empty message

Revision ID: 2d7cc9c2a4fe
Revises: a0a19680f300
Create Date: 2021-10-08 03:48:48.617627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7cc9c2a4fe'
down_revision = 'a0a19680f300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestWatchers',
    sa.Column('watcherid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ministryrequestid', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('watchedbygroup', sa.String(length=250), nullable=True),
    sa.Column('watchedby', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ministryrequestid', 'version'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.PrimaryKeyConstraint('watcherid')
    )
    
    op.create_table('FOIRawRequestWatchers',
    sa.Column('watcherid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requestid', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('watchedbygroup', sa.String(length=250), nullable=True),
    sa.Column('watchedby', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['requestid', 'version'], ['FOIRawRequests.requestid', 'FOIRawRequests.version'] ),
    sa.PrimaryKeyConstraint('watcherid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestWatchers')
    op.drop_table('FOIRawRequestWatchers')
    # ### end Alembic commands ###
