"""empty message

Revision ID: 2f06c40a6f46
Revises: 596fb5cbb352
Create Date: 2021-12-31 11:07:09.286223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f06c40a6f46'
down_revision = '596fb5cbb352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRequestNotifications', sa.Column('foirequestid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRequestNotifications', 'foirequestid')    
    # ### end Alembic commands ###
