"""empty message

Revision ID: 3084c5961187
Revises: e6c05dfb6977
Create Date: 2022-05-25 10:51:15.520322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3084c5961187'
down_revision = 'e6c05dfb6977'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.execute('ALTER TABLE public."FOIRequests" ALTER COLUMN initialdescription TYPE text')   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRequests" ALTER COLUMN initialdescription TYPE VARCHAR(500)')       
    # ### end Alembic commands ###

