"""empty message

Revision ID: 39989f4c2178
Revises: 3939b9fa5e3b
Create Date: 2022-09-07 14:14:53.235790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39989f4c2178'
down_revision = '3939b9fa5e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    op.create_table('FOIApplicantCorrepondenceTags',

    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.Column('applicantcorrespondenceid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tagid'], ['ApplicantCorrespondenceTags.tagid']), 
    sa.ForeignKeyConstraint(['applicantcorrespondenceid'], ['FOIApplicantCorrespondences.applicantcorrespondenceid']),       
    )   


def downgrade():
    op.drop_table('FOIApplicantCorrepondenceTags')
