"""empty message

Revision ID: 39b8a69fd59a
Revises: be926c984a59
Create Date: 2021-10-25 14:30:43.800004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b8a69fd59a'
down_revision = 'be926c984a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('closedate', sa.DateTime(), nullable=True))
    op.add_column('FOIRawRequests', sa.Column('closereasonid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'FOIRawRequests', 'CloseReasons', ['closereasonid'], ['closereasonid'])
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FOIRawRequests', type_='foreignkey')
    op.drop_column('FOIRawRequests', 'closereasonid')
    op.drop_column('FOIRawRequests', 'closedate')
    # ### end Alembic commands ###
