"""empty message

Revision ID: 3a2ffb0af202
Revises: ec27defe9178
Create Date: 2023-06-01 22:31:24.595281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a2ffb0af202'
down_revision = 'ec27defe9178'

branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRawRequestDocuments" ALTER COLUMN filename TYPE character varying(500);')
    op.execute('ALTER TABLE public."FOIMinistryRequestDocuments" ALTER COLUMN filename TYPE character varying(500);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRawRequestDocuments" ALTER COLUMN filename TYPE character varying(120);')
    op.execute('ALTER TABLE public."FOIMinistryRequestDocuments" ALTER COLUMN filename TYPE character varying(120);')
    # ### end Alembic commands ###
