"""empty message

Revision ID: 3afc864e6815
Revises: 1bda7f7bae57
Create Date: 2025-01-29 20:22:08.177238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3afc864e6815'
down_revision = '1bda7f7bae57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIMinistryRequests', sa.Column('isphasedrelease', sa.Boolean, nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIMinistryRequests', 'isphasedrelease')
    # ### end Alembic commands ###
