"""empty message

Revision ID: 3e91d4f34699
Revises: 455a24da8c58
Create Date: 2023-11-30 00:11:56.160830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e91d4f34699'
down_revision = '455a24da8c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, notificationtypelabel, isactive) values (\'OIPC\', \'OIPC\', \'oipc\', true);commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, notificationtypelabel, isactive) values (\'OIPC Due Reminder\', \'OIPC Due Reminder\', \'oipcduereminder\', true);commit;')
    op.execute('Insert into public."CommentTypes" (name, description, isactive) values (\'OIPC Tracking\', \'OIPC Tracking\', true);commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from  public."NotificationTypes" where name in (\'OIPC\');commit;')
    op.execute('delete from  public."NotificationTypes" where name in (\'OIPC Due Reminder\');commit;')
    op.execute('delete from  public."CommentTypes" where name in (\'OIPC Tracking\');commit;')
    # ### end Alembic commands ###
