"""empty message

Revision ID: 455a24da8c58
Revises: 3b399ca506fe
Create Date: 2023-11-15 12:31:33.274617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '455a24da8c58'
down_revision = '3b399ca506fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIMinistryRequests', sa.Column('isoipcreview', sa.Boolean, nullable=True,default=False))
    op.create_table('FOIRequestOIPC',
    sa.Column('oipcid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foiministryrequest_id', sa.Integer(), nullable=False),
    sa.Column('foiministryrequestversion_id', sa.Integer(), nullable=False),
    sa.Column('oipcno', sa.String(length=250), nullable=False),
    sa.Column('investigator', sa.String(length=500), nullable=True),
    sa.Column('reviewtypeid', sa.Integer(), nullable=False),
    sa.Column('reasonid', sa.Integer(), nullable=False),
    sa.Column('statusid', sa.Integer(), nullable=True),
    sa.Column('outcomeid', sa.Integer(), nullable=True),
    sa.Column('isinquiry', sa.Boolean(), nullable=True),
    sa.Column('isjudicialreview', sa.Boolean(), nullable=True),
    sa.Column('issubsequentappeal', sa.Boolean(), nullable=True),
    sa.Column('inquiryattributes', sa.JSON, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('createdby', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['foiministryrequest_id', 'foiministryrequestversion_id'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.PrimaryKeyConstraint('oipcid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIMinistryRequests', 'isoipcreview')
    op.drop_table('FOIRequestOIPC')
    # ### end Alembic commands ###
