"""empty message

Revision ID: 490bdb384e28
Revises: 56f7d4e5cd1d
Create Date: 2021-08-13 12:45:04.389235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '490bdb384e28'
down_revision = '56f7d4e5cd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('FOIRequests', sa.Column('applicantcategoryid', sa.Integer(), nullable=True))
    op.add_column('FOIRequests', sa.Column('wfinstanceid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'FOIRequests', 'ApplicantCategories', ['applicantcategoryid'], ['applicantcategoryid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FOIRequests', type_='foreignkey')
    op.drop_column('FOIRequests', 'wfinstanceid')
    op.drop_column('FOIRequests', 'applicantcategoryid')
  
    # ### end Alembic commands ###
