"""Mapping table for proactive disclosure requests

Revision ID: 49274e42cd98
Revises: 565afecc8627
Create Date: 2026-01-05 09:30:58.477697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49274e42cd98'
down_revision = '565afecc8627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIProactiveDisclosureRequests',
    sa.Column('proactivedisclosureid', sa.Integer(), primary_key=True , autoincrement=True, nullable=False),
    #sa.Column('version', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('foiministryrequest_id', sa.Integer(), nullable=False),
    sa.Column('foiministryrequestversion_id', sa.Integer(), nullable=False),
    sa.Column('proactivedisclosurecategoryid', sa.Integer(), sa.ForeignKey('ProactiveDisclosureCategories.proactivedisclosurecategoryid'), nullable=False), 
    sa.Column('reportperiod', sa.Text(), nullable=True),
    sa.Column('publicationdate', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(
        ['foiministryrequest_id', 'foiministryrequestversion_id'],
        [
            'FOIMinistryRequests.foiministryrequestid',
            'FOIMinistryRequests.version'
        ]
    ),
    sa.PrimaryKeyConstraint('proactivedisclosureid')
    )

    op.execute('ALTER TABLE public."FOIRequests" ALTER COLUMN requesttype TYPE VARCHAR(30)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRequests" ALTER COLUMN requesttype TYPE VARCHAR(15)')

    op.drop_table('FOIProactiveDisclosureRequests')
    # ### end Alembic commands ###
