"""empty message

Revision ID: 4e1f06469a5a
Revises: 6ef3221d0678
Create Date: 2022-08-04 12:46:09.187587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4e1f06469a5a'
down_revision = '6ef3221d0678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    cfrfeestatus_stage_table =  op.create_table('FeeWaiverStatuses',
    sa.Column('waiverstatusid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('waiverstatusid')
    )

    op.bulk_insert(
        cfrfeestatus_stage_table,
        [
            {'name':'iao','isactive':True, 'description': 'IAO Review'},
            {'name':'ministry','isactive':True, 'description': 'Ministry Review'},
            {'name':'decision','isactive':True, 'description': 'Ministry Decision'},
            {'name':'complete','isactive':True, 'description': 'Completed'},
        ]
    )

    op.create_table('FOIRequestFeeWaiver',
    sa.Column('feewaiverid', sa.Integer(), primary_key=True, autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('ministryrequestid', sa.Integer(), nullable=False),
    sa.Column('ministryrequestversion', sa.Integer(), nullable=True),
    sa.Column('formdata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('waiverstatusid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['ministryrequestid', 'ministryrequestversion'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version']),
    sa.ForeignKeyConstraint(['waiverstatusid'], ['FeeWaiverStatuses.waiverstatusid']),
    sa.PrimaryKeyConstraint('feewaiverid' , 'version')
    )

    op.execute('''INSERT INTO public."NotificationTypes"(
        name, description, isactive)
        VALUES ('Fee Waiver Form', 'Fee Waiver Form', true);commit;''')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestCFRFees')
    op.drop_table('CFRFeeStatuses')
    op.execute('''DELETE FROM public."NotificationTypes"
	WHERE name = 'Fee Waiver Form';commit;''')
    # ### end Alembic commands ###

