"""empty message

Revision ID: 516fbf1b13d9
Revises: 5b9b19213803
Create Date: 2024-08-20 11:13:22.669018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '516fbf1b13d9'
down_revision = '0982b9dca5f2'
# revision = '516fbf1b13d9'
# down_revision = '5b9b19213803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by FAlembic - please adjust! ###
    op.execute("""
               INSERT INTO public."ApplicantCorrespondenceTemplates"( documenturipath, "name", description, active, "version", created_at, createdby, display) 
               VALUES
               ('/TEMPLATES/EMAILS/acknowledgement_letter.html', 'ACKNOWLEDGEMENTLETTER', 'Acknowledgement Letter', true, 1, now(), 'system', true);
               commit;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""delete from public."ApplicantCorrespondenceTemplates" act  where name = 'ACKNOWLEDGEMENTLETTER'; commit;""")
    # ### end Alembic commands ###
