"""empty message

Revision ID: 530dff463b81
Revises: 9ca00a679b09
Create Date: 2022-01-20 03:10:43.822679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '530dff463b81'
down_revision = '9ca00a679b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."NotificationUserTypes" set name = \'Comment User\', description = \'Comment User\' where name = \'Tagged User\';')
    op.execute('Update  public."NotificationTypes" set name=\'New User Comments\', description=\'New User Comments\' where name=\'User Comments\';commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Reply User Comments\', \'Reply User Comments\', true);commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Tagged User Comments\', \'Tagged User Comments\', true);commit;')  
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."NotificationUserTypes" set name = \'Tagged User\', description = \'Tagged User\' where name = \'Comment User\';')
    op.execute('Update  public."NotificationTypes" set name=\'User Comments\', description=\'User Comments\' where name=\'New User Comments\';commit;')
    op.execute('Delete from public."NotificationTypes" where name in (\'Reply User Comments\', \'Tagged User Comments\');commit;')
    
    # ### end Alembic commands ###
