"""empty message

Revision ID: 530dff463b81
Revises: 6ffb804efde9
Create Date: 2022-01-20 03:10:43.822679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '530dff463b81'
down_revision = '6ffb804efde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."NotificationUserTypes" set name = \'Comment User\', description = \'Comment User\' where name = \'Tagged User\';')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."NotificationUserTypes" set name = \'Tagged User\', description = \'Tagged User\' where name = \'Comment User\';')
    # ### end Alembic commands ###
