"""ProactiveDisclosure Categories

Revision ID: 565afecc8627
Revises: 05dee3d60a8c
Create Date: 2025-12-23 11:33:01.546726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '565afecc8627'
down_revision = '05dee3d60a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pd_categories_table = op.create_table('ProactiveDisclosureCategories',
    sa.Column('proactivedisclosurecategoryid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('proactivedisclosurecategoryid')
    )
    op.bulk_insert(
        pd_categories_table,
        [
            {'name':'Briefing Notes','description':'Briefing Notes','isactive':True},
            {'name':'Calendars','description':'Calendars','isactive':True},
            {'name':'Direct Award Contracts','description':'Direct Award Contracts','isactive':True},
            {'name':'Contracts over $10,000','description':'Contracts over $10,000','isactive':True},
            {'name':'DM Travel Expenses','description':'DM Travel Expenses','isactive':True},
            {'name':'Estimates','description':'Estimates','isactive':True},
            {'name':'Minister Quarterly Travel Expenses','description':'Minister Quarterly Travel Expenses','isactive':True},
            {'name':'Transition Binders','description':'Transition Binders','isactive':True},
            {'name':'Alternative Service Delivery Contracts','description':'Alternative Service Delivery Contracts','isactive':True},           
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProactiveDisclosureCategories')
    # ### end Alembic commands ###
