"""empty message

Revision ID: 5782617db307
Revises: e25110cba030
Create Date: 2023-08-13 20:49:54.912638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5782617db307'
down_revision = 'e25110cba030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('FOIMinistryRequests', sa.Column('originalldd', sa.DateTime(), nullable=True))
        op.add_column('FOIMinistryRequests', sa.Column('identityverified', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('FOIMinistryRequests', 'originalldd')
        op.drop_column('FOIMinistryRequests', 'identityverified')


    # ### end Alembic commands ###
