"""empty message

Revision ID: 596fb5cbb352
Revises: 6b93b180199a
Create Date: 2022-01-04 16:25:13.001431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '596fb5cbb352'
down_revision = '6b93b180199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.execute('ALTER TABLE public."FOIMinistryRequests" ALTER COLUMN description TYPE TEXT')   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIMinistryRequests" ALTER COLUMN description TYPE VARCHAR(500)')       
    # ### end Alembic commands ###
