"""add version to applicant

Revision ID: 59a97f42b5f2
Revises: 7fa7236d06fb
Create Date: 2023-12-11 18:12:59.955472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a97f42b5f2'
down_revision = '7fa7236d06fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRequestApplicants', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('FOIRequestApplicantMappings', sa.Column('foirequestapplicant_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRequestApplicants', 'version')
    op.drop_column('FOIRequestApplicantMappings', 'foirequestapplicant_version')
    # ### end Alembic commands ###
