"""add version to applicant

Revision ID: 59a97f42b5f2
Revises: 7fa7236d06fb
Create Date: 2023-12-11 18:12:59.955472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59a97f42b5f2'
down_revision = '7fa7236d06fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRequestApplicants', sa.Column('applicantprofileid', sa.String(length=120), nullable=True))
    #op.add_column('FOIRequestApplicants', sa.Column('isactive', sa.Boolean, unique=False, nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRequestApplicants', 'applicantprofileid')
    #op.drop_column('FOIRequestApplicants', 'isactive')
    # ### end Alembic commands ###
