"""empty message

Revision ID: 5b9b19213803
Revises: dc99ffc3a6f7
Create Date: 2024-08-09 15:35:11.747935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b9b19213803'
down_revision = 'dc99ffc3a6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by FAlembic - please adjust! ###
    op.execute("""
               INSERT INTO public."ApplicantCorrespondenceTemplates"( documenturipath, "name", description, active, "version", created_at, createdby, display) 
               VALUES
               ('/TEMPLATES/EMAILS/generic_cover_email_template.html', 'GENERICCOVEREMAILTEMPLATE', 'Generic Cover Email Template', true, 1, now(), 'system', true);
               commit;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""delete from public."ApplicantCorrespondenceTemplates" act  where name = 'GENERICCOVEREMAILTEMPLATE'; commit;""")
    # ### end Alembic commands ###