"""empty message

Revision ID: 5b9e2fef18f6
Revises: bbf3e8da513b
Create Date: 2021-10-18 08:37:53.778565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime
# revision identifiers, used by Alembic.
revision = '5b9e2fef18f6'
down_revision = 'bbf3e8da513b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIMinistryRequestDivisions',
    sa.Column('foiministrydivisionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('divisionid', sa.Integer(), nullable=False),
    sa.Column('stageid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('foiministryrequest_id', sa.Integer(), nullable=True),
    sa.Column('foiministryrequestversion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foiministryrequest_id', 'foiministryrequestversion_id'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.ForeignKeyConstraint(['divisionid'], ['ProgramAreaDivisions.divisionid'], ),
    sa.ForeignKeyConstraint(['stageid'], ['ProgramAreaDivisionStages.stageid'], ),
    sa.PrimaryKeyConstraint('foiministrydivisionid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIMinistryRequestDivisions')
    # ### end Alembic commands ###
