"""PD Publication Reminder Notification Type

Revision ID: 5ba80deacf94
Revises: 1dba7b01aae2
Create Date: 2026-03-21 19:38:05.812988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ba80deacf94'
down_revision = '1dba7b01aae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, notificationtypelabel, isactive) values (\'Publication Due Reminder\', \'Publication Due Reminder\', \'publicationduereminder\', true);commit;')
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from  public."NotificationTypes" where name in (\'Publication Due Reminder\');commit;')
    # ### end Alembic commands ###
