"""empty message

Revision ID: 5e17e1bf2181
Revises: 369bf06a3501
Create Date: 2022-05-06 14:34:37.493281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e17e1bf2181'
down_revision = '369bf06a3501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."OperatingTeams" set name = \'Social Education\', description = \'Social Education\' where name = \'Social Tech Team\';')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."OperatingTeams" set name = \'Social Tech Team\', description = \Social Tech Team\' where name = \'Social Education\';')

    # ### end Alembic commands ###
