"""empty message

Revision ID: 5f6cccd86344
Revises: 6ea519fd23ca
Create Date: 2021-12-20 14:48:35.949936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String


# revision identifiers, used by Alembic.
revision = '5f6cccd86344'
down_revision = '6ea519fd23ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NotificationTypes',
    sa.Column('notificationtypeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('notificationtypeid')
    )
    notification_type_table = table('NotificationTypes',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                   )
    op.bulk_insert(
        notification_type_table,
        [
            {'name':'State','description':'State','isactive':True},
            {'name':'Division','description':'Division','isactive':True},
            {'name':'User Comments','description':'User Comments','isactive':True},
            {'name':'Extension','description':'Extension','isactive':True},
            {'name':'Assignment','description':'Assignment','isactive':True},
        ]
    )
    op.create_table('NotificationUserTypes',
    sa.Column('notificationusertypeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('notificationusertypeid')
    )
    notification_usertype_table = table('NotificationUserTypes',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                   )
    op.bulk_insert(
        notification_usertype_table,
        [
            {'name':'Watcher','description':'Watcher','isactive':True},
            {'name':'Assignee','description':'Assignee','isactive':True},
            {'name':'Tagged User','description':'Tagged User','isactive':True}
        ]
    )    
    op.create_table('FOIRequestNotifications',
    sa.Column('notificationid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification', sa.TEXT(), nullable=True),    
    sa.Column('notificationtypeid', sa.Integer(), nullable=False),
    sa.Column('requestid', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('idnumber', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['requestid', 'version'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.ForeignKeyConstraint(['notificationtypeid'], ['NotificationTypes.notificationtypeid']),
    sa.PrimaryKeyConstraint('notificationid')
    ) 
    op.create_table('FOIRequestNotificationUsers',
    sa.Column('notificationuserid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notificationid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=100), nullable=False),
    sa.Column('notificationusertypeid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['notificationid'], ['FOIRequestNotifications.notificationid']),
    sa.ForeignKeyConstraint(['notificationusertypeid'], ['NotificationUserTypes.notificationusertypeid']),
    sa.PrimaryKeyConstraint('notificationuserid')
    ) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NotificationTypes')
    op.drop_table('NotificationUserTypes')
    op.drop_table('FOIRequestNotificationUsers')
    op.drop_table('FOIRequestNotifications')
    # ### end Alembic commands ###
