"""empty message

Revision ID: 61a781f50875
Revises: 39b8a69fd59a
Create Date: 2021-10-26 12:08:50.402155

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '61a781f50875'
down_revision = '39b8a69fd59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIMinistryRequestDocuments',
    sa.Column('foiministrydocumentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documentpath', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('foiministryrequest_id', sa.Integer(), nullable=True),
    sa.Column('foiministryrequestversion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foiministryrequest_id', 'foiministryrequestversion_id'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.PrimaryKeyConstraint('foiministrydocumentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIMinistryRequestDocuments')
    # ### end Alembic commands ###
