"""empty message

Revision ID: 639312d3816c
Revises: 8e350023597f
Create Date: 2021-08-09 12:49:20.603488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639312d3816c'
down_revision = '8e350023597f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestStatuses',
    sa.Column('requeststatusid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('requeststatusid')
    )
    op.create_table('FOIMinistryRequests',
    sa.Column('foiministryrequestid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('filenumber', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('recordsearchfromdate', sa.DateTime(), nullable=False),
    sa.Column('recordsearchtodate', sa.DateTime(), nullable=False),
    sa.Column('startdate', sa.DateTime(), nullable=False),
    sa.Column('duedate', sa.DateTime(), nullable=False),
    sa.Column('assignedto', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('programareaid', sa.Integer(), nullable=True),
    sa.Column('requeststatusid', sa.Integer(), nullable=True),
    sa.Column('foirequest_id', sa.Integer(), nullable=True),
    sa.Column('foirequestversion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foirequest_id', 'foirequestversion_id'], ['FOIRequests.foirequestid', 'FOIRequests.version'], ),
    sa.ForeignKeyConstraint(['programareaid'], ['ProgramAreas.programareaid'], ),
    sa.ForeignKeyConstraint(['requeststatusid'], ['FOIRequestStatuses.requeststatusid'], ),
    sa.PrimaryKeyConstraint('foiministryrequestid', 'version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIMinistryRequests')
    op.drop_table('FOIRequestStatuses')
    # ### end Alembic commands ###
