"""empty message

Revision ID: 6a384db9f04b
Revises: 5b9e2fef18f6
Create Date: 2021-10-21 14:12:46.696355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String


# revision identifiers, used by Alembic.
revision = '6a384db9f04b'
down_revision = '5b9e2fef18f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    requeststatus_table = table('FOIRequestStatuses',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                   ) 
    op.bulk_insert(
        requeststatus_table,
        [
            {'name':'On Hold','description':'On Hold','isactive':True},
            {'name':'Deduplication','description':'Deduplication','isactive':True},
            {'name':'Harms Assessment','description':'Harms Assessment','isactive':True},
            {'name':'Response','description':'Response','isactive':True}
           
        ]
    )  
    op.execute('Update public."FOIRequestStatuses" set name = \'Fee Estimate\', description = \'Fee Estimate\' where name = \'Fee Assessed\';')  
    op.execute('Update public."FOIRequestStatuses" set name = \'Records Review\', description = \'Records Review\' where name = \'Review\';')    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."FOIRequestStatuses" where name in (\'On Hold\',\'Deduplication\',\'Harms Assessment\',\'Redirect\',\'Response\');')
    op.execute('Update public."FOIRequestStatuses" set name = \'Fee Assessed\', description = \'Fee Assessed\' where name = \'Fee Estimate\';')  
    op.execute('Update public."FOIRequestStatuses" set name = \'Review\', description = \'Review\' where name = \'Records Review\';')    
    # ### end Alembic commands ###
