"""empty message

Revision ID: 6ae623b1d72d
Revises: 7b70faa9b2ee
Create Date: 2023-02-07 12:09:24.436917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ae623b1d72d'
down_revision = '7b70faa9b2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'HRSS Records\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'HR Specialist Case Files\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'BCPSA Classifications\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Contact Centre\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Peoplesoft Reports\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Performance Records\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Job Competition Files\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'POD - Executive Talent Management\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'POD - Corporate Workforce Strategies\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'POD - Learning Centre\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'PIE - Policy and Research\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'PIE - Behavioural Insights Group\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Employee Relations - Workforce Restructuring\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Employee Relations - Investigations\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Labour Relations - Grievances\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Information Technology Services\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Surveys and Measurement\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'PSA\'), \'Corporate Health Programs\', true, now(), \'system\');commit;')
    op.execute('UPDATE public."ProgramAreaDivisions" SET isactive=false WHERE name in (\'Business Performance Division\', \'Custom Research\', \'Corporate Health Program\', \'Employee Relations\', \'Policy, Innovation & Engagement\', \'People and Organizational Development\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'HRSS Records\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'HR Specialist Case Files\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'BCPSA Classifications\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Contact Centre\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Peoplesoft Reports\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Performance Records\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Job Competition Files\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'POD - Executive Talent Management\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'POD - Corporate Workforce Strategies\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'POD - Learning Centre\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'PIE - Policy and Research\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'PIE - Behavioural Insights Group\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Employee Relations - Workforce Restructuring\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Employee Relations - Investigations\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Labour Relations - Grievances\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Information Technology Services\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Surveys and Measurement\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Corporate Health Programs\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    op.execute('UPDATE public."ProgramAreaDivisions" SET isactive=true WHERE name in (\'Business Performance Division\', \'Custom Research\', \'Corporate Health Program\', \'Employee Relations\', \'Policy, Innovation & Engagement\', \'People and Organizational Development\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'PSA\');commit;')
    # ### end Alembic commands ###
