"""empty message

Revision ID: 7475fca04f69
Revises: e3fc2c864677
Create Date: 2021-12-08 22:50:04.398610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String


# revision identifiers, used by Alembic.
revision = '7475fca04f69'
down_revision = 'e3fc2c864677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    requeststatus_table = table('FOIRequestStatuses',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                   ) 
    op.bulk_insert(
        requeststatus_table,
        [
            {'name':'Archived','description':'Archived','isactive':True}
           
        ]
    ) # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."FOIRequestStatuses" where name in (\'Archived\');')
    # ### end Alembic commands ###
