"""empty message

Revision ID: 789c89c4306c
Revises: 530dff463b81
Create Date: 2022-01-25 10:03:06.255756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '789c89c4306c'
down_revision = '530dff463b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRawRequestNotifications" ALTER COLUMN notification TYPE JSON USING notification::JSON;')
    op.execute('ALTER TABLE public."FOIRequestNotifications" ALTER COLUMN notification TYPE JSON USING notification::JSON;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRawRequestNotifications" ALTER COLUMN notification TYPE text;')
    op.execute('ALTER TABLE public."FOIRequestNotifications" ALTER COLUMN notification TYPE text;')
    # ### end Alembic commands ###
