"""empty message

Revision ID: 7a554bfa243d
Revises: c43a8e0104bc
Create Date: 2025-01-28 16:41:05.689226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a554bfa243d'
down_revision = '880547157deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('isconsultflag', sa.Boolean, unique=False, nullable=True, default=False))
    op.add_column('FOIMinistryRequests', sa.Column('isconsultflag', sa.Boolean, unique=False, nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'isconsultflag')
    op.drop_column('FOIMinistryRequests', 'isconsultflag')
    # ### end Alembic commands ###