"""empty message

Revision ID: 7b70faa9b2ee
Revises: ea8dbc7b1ea0
Create Date: 2023-02-03 22:31:44.342097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b70faa9b2ee'
down_revision = 'ea8dbc7b1ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIMinistryRequests" ADD isofflinepayment Boolean')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIMinistryRequests" DROP isofflinepayment')
    # ### end Alembic commands ###
