"""empty message

Revision ID: 7cbff407743e
Revises: 46c75ba1a9fd
Create Date: 2021-08-09 15:32:54.124156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbff407743e'
down_revision = '46c75ba1a9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PersonalInformationAttributes',
    sa.Column('attributeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('attributeid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PersonalInformationAttributes')
    # ### end Alembic commands ###
