"""empty message

Revision ID: 7d393fc1fc31
Revises: d64df04da9df
Create Date: 2023-07-13 14:42:47.605001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d393fc1fc31'
down_revision = 'd64df04da9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute('DROP INDEX "FOIRawRequests_axis";')    
    
    op.execute('CREATE INDEX "FOIRawRequests_event" ON "FOIRawRequests" (axisrequestid, assignedto, assignedgroup, status);')
    
    op.execute('DROP INDEX "FOIMinistryRequests_axis";')
    op.execute('DROP INDEX "FOIMinistryRequests_statusid";')
    op.execute('DROP INDEX "FOIMinistryRequests_group";')
    op.execute('DROP INDEX "FOIMinistryRequests_ministrygroup";')    
    op.execute('DROP INDEX "FOIMinistryRequests_assignedto";')
    op.execute('DROP INDEX "FOIMinistryRequests_minassignedto";')
    
    op.execute('CREATE INDEX "FOIMinistryRequests_event" ON "FOIMinistryRequests"(axisrequestid, assignedto, assignedgroup, assignedministryperson, assignedministrygroup, requeststatusid);')
    
    op.execute('DROP INDEX "FOIRawRequestNotifications_axis";')    
    op.execute('DROP INDEX "FOIRawRequestNotifications_typeid";')
    
    op.execute('CREATE INDEX "FOIRawRequestNotifications_event" ON "FOIRawRequestNotifications"(axisnumber, notificationtypeid);')

    
    op.execute('DROP INDEX "FOIRequestNotifications_axis";')    
    op.execute('DROP INDEX "FOIRequestNotifications_typeid";')    
    
    op.execute('CREATE INDEX "FOIRequestNotifications_event" ON "FOIRequestNotifications"(axisnumber, notificationtypeid);')
    
    op.execute('DROP INDEX "FOIRestrictedMinistryRequests_minid";')
    
    op.execute('CREATE INDEX "FOIRestrictedMinistryRequests_event" ON "FOIRestrictedMinistryRequests"(ministryrequestid, type, isactive);')
    
    op.execute('DROP INDEX "FOIRawRequestWatchers_watchedby";')
    op.execute('CREATE INDEX "FOIRawRequestWatchers_event" ON "FOIRawRequestWatchers"(requestid, watchedby);')
    
    op.execute('DROP INDEX "FOIRequestWatchers_watchedby";')  
    op.execute('CREATE INDEX "FOIRequestWatchers_event" ON "FOIRequestWatchers"(ministryrequestid, watchedby);')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute('CREATE INDEX "FOIRawRequests_axis" ON "FOIRawRequests"(axisrequestid);')
    
    op.execute('CREATE INDEX "FOIMinistryRequests_axis" ON "FOIMinistryRequests"(axisrequestid);')
    op.execute('CREATE INDEX "FOIMinistryRequests_statusid" ON "FOIMinistryRequests"(requeststatusid);')
    op.execute('CREATE INDEX "FOIMinistryRequests_group" ON "FOIMinistryRequests"(assignedgroup);')
    op.execute('CREATE INDEX "FOIMinistryRequests_ministrygroup" ON "FOIMinistryRequests"(assignedministrygroup);')    
    op.execute('CREATE INDEX "FOIMinistryRequests_assignedto" ON "FOIMinistryRequests"(assignedto)')
    op.execute('CREATE INDEX "FOIMinistryRequests_minassignedto" ON "FOIMinistryRequests"(assignedministryperson);')
    
    op.execute('CREATE INDEX "FOIRawRequestNotifications_axis" ON "FOIRawRequestNotifications"(axisnumber);')
    op.execute('CREATE INDEX "FOIRawRequestNotifications_typeid" ON "FOIRawRequestNotifications"(notificationtypeid);')
    
    op.execute('CREATE INDEX "FOIRequestNotifications_typeid" ON "FOIRequestNotifications"(notificationtypeid);')    
    op.execute('CREATE INDEX "FOIRequestNotifications_axis" ON "FOIRequestNotifications"(axisnumber);')
   
    op.execute('CREATE INDEX "FOIRestrictedMinistryRequests_minid" ON "FOIRestrictedMinistryRequests"(ministryrequestid);')
        
    
    op.execute('CREATE INDEX "FOIRawRequestWatchers_watchedby" ON "FOIRawRequestWatchers"(watchedby);')
    op.execute('CREATE INDEX "FOIRequestWatchers_watchedby" ON "FOIRequestWatchers"(watchedby);')  

    op.execute('DROP INDEX "FOIRawRequests_event";')  
    op.execute('DROP INDEX "FOIMinistryRequests_event";')  
    op.execute('DROP INDEX "FOIRawRequestNotifications_event";')  
    op.execute('DROP INDEX "FOIRequestNotifications_event";')  
    op.execute('DROP INDEX "FOIRestrictedMinistryRequests_event";')  
    op.execute('DROP INDEX "FOIRawRequestWatchers_event";')  
    op.execute('DROP INDEX "FOIRequestWatchers_event";')    
    
    # ### end Alembic commands ###
