"""empty message

Revision ID: 81e6ac3ba248
Revises: 257a134400b8
Create Date: 2021-07-08 16:54:39.480648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e6ac3ba248'
down_revision = '257a134400b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProgramAreas', sa.Column('bcgovcode', sa.String(length=30), nullable=True))
    op.add_column('ProgramAreas', sa.Column('iaocode', sa.String(length=30), nullable=True))
    op.drop_column('ProgramAreas', 'code')
    op.drop_column('ProgramAreas', 'shortname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProgramAreas', sa.Column('shortname', sa.VARCHAR(length=125), autoincrement=False, nullable=True))
    op.add_column('ProgramAreas', sa.Column('code', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('ProgramAreas', 'iaocode')
    op.drop_column('ProgramAreas', 'bcgovcode')
    # ### end Alembic commands ###
