"""empty message

Revision ID: 828583f30d60
Revises: 5ef3541c7524
Create Date: 2023-04-06 11:00:09.035947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '828583f30d60'
down_revision = '5ef3541c7524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # EML
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Minister’s Office\', true, now(), \'system\',1);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Deputy Minister’s Office\', true, now(), \'system\',2);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Electricity and Alternative Energy Division\', true, now(), \'system\',3);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'LNG Canada Implementation Secretariat\', true, now(), \'system\',4);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Mines, Competitiveness and Authorizations Division\', true, now(), \'system\',5);commit;')    
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Oil and Gas Division\', true, now(), \'system\',6);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Strategic and Indigenous Affairs Division\', true, now(), \'system\',7);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'EML\'), \'Woodfibre Implementation Group\', true, now(), \'system\',8);commit;')
    #FOR
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'Minister’s Office\', true, now(), \'system\',1);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'Deputy Minister’s Office\', true, now(), \'system\',2);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'DMO - Strategic Priorities Group\', true, now(), \'system\',3);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'Associate Deputy Minister’s Office\', true, now(), \'system\',4);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'Associate DM - Indigenous Relations\', true, now(), \'system\',5);commit;')    
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'Associate DM - Operations\', true, now(), \'system\',6);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - BC Wildfire Service\', true, now(), \'system\',7);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - Office of the Chief Forester\', true, now(), \'system\',8);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - Integrated Resource Operations\', true, now(), \'system\',9);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - Timber, Range, and Economics\', true, now(), \'system\',10);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - BC Timber Sales\', true, now(), \'system\',11);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - Forest Renewal Initiative and Old Growth\', true, now(), \'system\',12);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - Corporate Services for Natural Resources\', true, now(), \'system\',13);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - North Region\', true, now(), \'system\',14);commit;')    
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - South Region\', true, now(), \'system\',15);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'ADM - Coast Region\', true, now(), \'system\',16);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - Northeast\', true, now(), \'system\',17);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - Omineca\', true, now(), \'system\',18);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - Skeena\', true, now(), \'system\',19);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - Cariboo\', true, now(), \'system\',20);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - Kootenay Boundary\', true, now(), \'system\',21);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - Thompson Okanagan\', true, now(), \'system\',22);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - South Coast\', true, now(), \'system\',23);commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby,sortorder) VALUES ((select programareaid from public."ProgramAreas" where isactive = true and iaocode=\'FOR\'), \'RED - West Coast\', true, now(), \'system\',24);commit;')

def downgrade():
    op.execute('delete from public."ProgramAreaDivisions" WHERE programareaid in (SELECT programareaid FROM "ProgramAreas" WHERE iaocode in(\'FOR\',\'EML\') and isactive = true)')
    # ### end Alembic commands ###
