"""empty message

Revision ID: 83ce6c30feec
Revises: 07a15d90db59
Create Date: 2021-08-09 16:22:56.348961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83ce6c30feec'
down_revision = '07a15d90db59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FOIMinistryRequests', 'recordsearchfromdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('FOIMinistryRequests', 'recordsearchtodate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FOIMinistryRequests', 'recordsearchtodate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('FOIMinistryRequests', 'recordsearchfromdate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
