"""empty message

Revision ID: 83cfc8047acf
Revises: 77ef102e9823
Create Date: 2024-10-31 12:47:04.379106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String

# revision identifiers, used by Alembic.
revision = '83cfc8047acf'
down_revision = '77ef102e9823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    requeststatus_table = table('FOIRequestStatuses',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                 column('statuslabel',String),
                                   ) 
    op.bulk_insert(
        requeststatus_table,
        [
            {'name':'On Hold - Other','description':'On Hold for Other reasons','isactive':True, 'statuslabel':'onholdother'},
        ]
    )  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."FOIRequestStatuses" where name = \'On Hold - Other\';')
    # ### end Alembic commands ###

