"""empty message

Revision ID: 880547157deb
Revises: c43a8e0104bc
Create Date: 2025-02-10 09:55:02.853876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '880547157deb'
down_revision = 'c43a8e0104bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute('INSERT INTO public."CloseReasons"(name, isactive, created_at, createdby) VALUES (\'Cancelled\', true, now(), \'System\');commit;')
     op.execute('INSERT INTO public."CloseReasons"(name, isactive, created_at, createdby) VALUES (\'Opened In Error\', true, now(), \'System\');commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute('DELETE FROM public."CloseReasons" WHERE name IN (\'Cancelled\', \'Opened In Error\');commit;')
    # ### end Alembic commands ###
