"""empty message

Revision ID: 8bcfbbd263fe
Revises: 5da11b0ca205
Create Date: 2021-11-02 16:53:50.264767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcfbbd263fe'
down_revision = '5da11b0ca205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestComments',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parentcommentid', sa.Integer(), nullable=True),
    sa.Column('ministryrequestid', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),    
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('commenttypeid', sa.Integer(), nullable=False,default=1),
    sa.ForeignKeyConstraint(['ministryrequestid', 'version'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.ForeignKeyConstraint(['commenttypeid'], ['CommentTypes.commenttypeid'] ),
    sa.PrimaryKeyConstraint('commentid')
    )
    
    op.create_table('FOIRawRequestComments',
    sa.Column('commentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parentcommentid', sa.Integer(), nullable=True),
    sa.Column('requestid', sa.Integer(), nullable=True),   
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),    
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('commenttypeid', sa.Integer(), nullable=False,default=1),
    sa.ForeignKeyConstraint(['requestid', 'version'], ['FOIRawRequests.requestid', 'FOIRawRequests.version'] ),
    sa.ForeignKeyConstraint(['commenttypeid'], ['CommentTypes.commenttypeid'] ),
    sa.PrimaryKeyConstraint('commentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestComments')
    op.drop_table('FOIRawRequestComments')
    # ### end Alembic commands ###