"""empty message

Revision ID: 8e350023597f
Revises: 385d72859d39
Create Date: 2021-08-09 11:33:06.292274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e350023597f'
down_revision = '385d72859d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequests',
    sa.Column('foirequestid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('requesttype', sa.String(length=15), nullable=False),
    sa.Column('receiveddate', sa.DateTime(), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('initialdescription', sa.String(length=500), nullable=True),
    sa.Column('initialrecordsearchfromdate', sa.DateTime(), nullable=True),
    sa.Column('initialrecordsearchtodate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('deliverymodeid', sa.Integer(), nullable=True),
    sa.Column('receivedmodeid', sa.Integer(), nullable=True),
    sa.Column('foirawrequestid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliverymodeid'], ['DeliveryModes.deliverymodeid'], ),    
    sa.ForeignKeyConstraint(['receivedmodeid'], ['ReceivedModes.receivedmodeid'], ),
    sa.PrimaryKeyConstraint('foirequestid', 'version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequests')
    # ### end Alembic commands ###
