"""empty message

Revision ID: 9f8be53ede97
Revises: 52fa2ae5aa88
Create Date: 2022-07-27 17:38:41.811192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f8be53ede97'
down_revision = '52fa2ae5aa88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Email Failure\', \'Email Failure\', true);commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from  public."NotificationTypes" where name in (\'Email Failure\');commit;')
    # ### end Alembic commands ###
