"""empty message

Revision ID: a03fb36ee924
Revises: bf8a28cb0063
Create Date: 2021-12-01 01:32:16.418645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03fb36ee924'
down_revision = 'bf8a28cb0063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('requirespayment', sa.Boolean, unique=False, nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'requirespayment')
    # ### end Alembic commands ###
