"""empty message

Revision ID: a0a19680f300
Revises: eae7d7d5b20c
Create Date: 2021-11-24 22:19:47.899429

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a0a19680f300'
down_revision = 'eae7d7d5b20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE public."FeeCodes" SET fee= 10 WHERE code = \'FOI0001\'')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE public."FeeCodes" SET fee= 20 WHERE code = \'FOI0001\'')
    # ### end Alembic commands ###
