"""empty message

Revision ID: a445517cd06a
Revises: b4889383db92
Create Date: 2023-02-08 13:54:10.525425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a445517cd06a'
down_revision = 'b4889383db92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'ECC\'), \'Communications\', true, now(), \'system\');commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Communications\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'ECC\');commit;')
    # ### end Alembic commands ###
