"""empty message

Revision ID: a4a987c529f1
Revises: 61a781f50875
Create Date: 2021-11-03 15:43:07.838174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a987c529f1'
down_revision = '61a781f50875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute('Update public."CloseReasons" set name = \'Outside Scope of Act\' where name = \'Outdated Scope of Act\';')  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Update public."CloseReasons" set name = \'Outdated Scope of Act\' where name = \'Outside Scope of Act\';')  
    # ### end Alembic commands ###
