"""empty message

Revision ID: a869dfc9df17
Revises: 2bf3c5d25742
Create Date: 2022-06-08 14:33:19.480068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a869dfc9df17'
down_revision = '2bf3c5d25742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'CFR Fee Form\', \'CFR Fee Form\', true);commit;')
    op.execute('update  public."NotificationTypes" set description=\'Needs Clarification\' where name=\'clarification\';commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from  public."NotificationTypes" where name in (\'CFR Fee Form\');commit;')
    op.execute('update  public."NotificationTypes" set description=\'Clarification\' where name=\'clarification\';commit;')
    # ### end Alembic commands ###
