"""MSD CFD Req. status for personal

Revision ID: aacdbca19a47
Revises: 07a6d930b276
Create Date: 2023-09-18 16:40:31.999882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String


# revision identifiers, used by Alembic.
revision = 'aacdbca19a47'
down_revision = '6b94062ebea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    requeststatus_table = table('FOIRequestStatuses',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                   ) 
    op.bulk_insert(
        requeststatus_table,
        [
            {'name':'Tagging','description':'Tagging','isactive':True},
            {'name':'Ready to Scan','description':'Ready to Scan','isactive':True}
           
        ]
    ) # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."FOIRequestStatuses" where name in (\'Tagging\',\'Ready to Scan\');')
    # ### end Alembic commands ###