"""empty message

Revision ID: ac36538aa6d9
Revises: 
Create Date: 2021-06-02 11:34:05.727827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac36538aa6d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRawRequests',
    sa.Column('requestid', sa.Integer(), nullable=False),
    sa.Column('requestrawdata', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('notes', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('requestid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRawRequests')
    # ### end Alembic commands ###
