"""empty message

Revision ID: ad8196316506
Revises: c5b40cc3adfb
Create Date: 2021-10-26 02:39:57.007460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8196316506'
down_revision = 'c5b40cc3adfb'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payments', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.execute('UPDATE public."FeeCodes" SET fee= 20 WHERE code = \'FOI0001\'')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payments', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.execute('UPDATE public."FeeCodes" SET fee= 10 WHERE code = \'FOI0001\'')
    ### end Alembic commands ###
