"""empty message

Revision ID: b4889383db92
Revises: 6ae623b1d72d
Create Date: 2023-02-07 15:44:20.723520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4889383db92'
down_revision = '6ae623b1d72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('INSERT INTO public."ProgramAreaDivisions"(programareaid, name, isactive, created_at, createdby) VALUES ((select programareaid from public."ProgramAreas" where iaocode=\'EDU\'), \'Communications\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisionStages"(name, isactive, created_at, createdby) VALUES (\'In Review\', true, now(), \'system\');commit;')
    op.execute('INSERT INTO public."ProgramAreaDivisionStages"(name, isactive, created_at, createdby) VALUES (\'Review Complete\', true, now(), \'system\');commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."ProgramAreaDivisions" WHERE name in (\'Communications\') and programareaid = (select programareaid from public."ProgramAreas" where iaocode=\'EDU\');commit;')
    op.execute('delete from public."ProgramAreaDivisionStages" WHERE name in (\'In Review\');commit;')
    op.execute('delete from public."ProgramAreaDivisionStages" WHERE name in (\'Review Complete\');commit;')
    # ### end Alembic commands ###
