"""empty message

Revision ID: b4da31675bd0
Revises: 3e91d4f34699
Create Date: 2023-12-12 23:18:19.440544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4da31675bd0'
down_revision = '3e91d4f34699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('update public."FOIRequestComments" set commenttypeid = (select commenttypeid  from "CommentTypes"  where name = \'System generated\') where commenttypeid = (select commenttypeid  from "CommentTypes"  where name = \'OIPC Tracking\');commit;')
    op.execute('delete from  public."CommentTypes" where name in (\'OIPC Tracking\');commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from  public."CommentTypes" where name in (\'OIPC Tracking\');commit;')
    # ### end Alembic commands ###
