"""empty message

Revision ID: b863a277c491
Revises: 3ef2a6dbf556
Create Date: 2023-05-26 10:10:29.244184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b863a277c491'
down_revision = '3ef2a6dbf556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequestNotifications', sa.Column('isdeleted', sa.Boolean, nullable=False, server_default="false"))
    op.add_column('FOIRawRequestNotificationUsers', sa.Column('isdeleted', sa.Boolean, nullable=False, server_default="false"))
    op.add_column('FOIRequestNotifications', sa.Column('isdeleted', sa.Boolean, nullable=False, server_default="false"))    
    op.add_column('FOIRequestNotificationUsers', sa.Column('isdeleted', sa.Boolean, nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequestNotifications', 'isdeleted')
    op.drop_column('FOIRawRequestNotificationUsers', 'isdeleted')    
    op.drop_column('FOIRequestNotifications', 'isdeleted')
    op.drop_column('FOIRequestNotificationUsers', 'isdeleted')
    # ### end Alembic commands ###
