"""add category to applicant

Revision ID: ba218164248e
Revises: 59a97f42b5f2
Create Date: 2024-01-15 13:09:57.278888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba218164248e'
down_revision = '59a97f42b5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRequestApplicants', sa.Column('applicantcategoryid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRequestApplicants', 'applicantcategoryid')
    # ### end Alembic commands ###