"""empty message

Revision ID: bab145529239
Revises: 2c15a7379da4
Create Date: 2021-08-09 15:18:22.003298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab145529239'
down_revision = '2c15a7379da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestApplicantMappings',
    sa.Column('foirequestapplicantmappingid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('requestortypeid', sa.Integer(), nullable=True),
    sa.Column('foirequestapplicantid', sa.Integer(), nullable=True),
    sa.Column('foirequestid', sa.Integer(), nullable=True),
    sa.Column('foirequestversion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foirequestapplicantid'], ['FOIRequestApplicants.foirequestapplicantid'], ),
    sa.ForeignKeyConstraint(['foirequestid', 'foirequestversion'], ['FOIRequests.foirequestid', 'FOIRequests.version'], ),
    sa.ForeignKeyConstraint(['requestortypeid'], ['RequestorTypes.requestortypeid'], ),
    sa.PrimaryKeyConstraint('foirequestapplicantmappingid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestApplicantMappings')
    # ### end Alembic commands ###
