"""empty message

Revision ID: bbee01df3e8d
Revises: 3a2ffb0af202
Create Date: 2023-06-01 22:31:24.595281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbee01df3e8d'
down_revision = '3a2ffb0af202'

branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''INSERT INTO public."SubjectCodes" (name, description, isaxissubjectcode, isactive) VALUES ('CFD Re-print', 'CFD Re-print', true, true);''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''DELETE FROM public."SubjectCodes" WHERE name = 'CFD Re-print';''')
    # ### end Alembic commands ###
