"""empty message

Revision ID: bbf3e8da513b
Revises: 2d7cc9c2a4fe
Create Date: 2021-10-14 00:23:07.065982

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'bbf3e8da513b'
down_revision = '2d7cc9c2a4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProgramAreaDivisions',
    sa.Column('divisionid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programareaid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True, default ='System'),
    sa.ForeignKeyConstraint(['programareaid'], ['ProgramAreas.programareaid'], ),
    sa.PrimaryKeyConstraint('divisionid')
    )
    
    division_stage_table = op.create_table('ProgramAreaDivisionStages',
    sa.Column('stageid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True, default ='System'),
    sa.PrimaryKeyConstraint('stageid')
    )
    op.execute('Truncate table public."ProgramAreaDivisionStages";') 
    op.execute('Truncate table public."ProgramAreaDivisions";')  
    
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'Deputy Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'Education Programs\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'Learning\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'services & Technology\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'Governance & Analytics\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Education\'), \'Resource Management\', true, now(), \'system\');')             
    
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Municipal Affairs\'), \'Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Municipal Affairs\'), \'Deputy Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Municipal Affairs\'), \'Management Services\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Municipal Affairs\'), \'Immigration Services and Strategic Planning\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Municipal Affairs\'), \'Local Government\', true, now(), \'system\');') 
  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Deputy Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Labour\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Management Services\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Policy and Legislation\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Employment Standards\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Workers’ Advisor’s Office\', true, now(), \'system\');') 
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Labour\'), \'Employers’ Advisor’s Office\', true, now(), \'system\');') 
    
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Deputy Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Management Services\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Trade & Industry Development\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'small Business & Economic Development\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Economic Restart (? – maybe part of DMO?)\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Mass Timber Implementation\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Innovation, Technology & Investment Capital\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Jobs, Economic Recovery and Innovation\'), \'Investment & Innovation\', true, now(), \'system\');')
    
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Tourism, Arts, Culture and Sport\'), \'Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Tourism, Arts, Culture and Sport\'), \'Deputy Minister’s Office\', true, now(), \'system\');')  
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Tourism, Arts, Culture and Sport\'), \'sport and Creative Sector\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Tourism, Arts, Culture and Sport\'), \'Management Services\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Tourism, Arts, Culture and Sport\'), \'Arts & Cultur\', true, now(), \'system\');')
    op.execute('Insert into public."ProgramAreaDivisions" (programareaid, name, isactive, created_at, createdby) values ((select programareaid from public."ProgramAreas" where name=\'Ministry of Tourism, Arts, Culture and Sport\'), \'Tourism Sector Strategy\', true, now(), \'system\');')
 
    
    op.bulk_insert(
        division_stage_table,
        [
            {'name':'Clarification','isactive':True},
            {'name':'Assigned to Division','isactive':True},
            {'name':'Awaiting Fees','isactive':True},
            {'name':'Fees Received','isactive':True},
            {'name':'Gathering Records','isactive':True},
            {'name':'Records Received','isactive':True},
            {'name':'Awaiting Harms','isactive':True},
            {'name':'Harms Received','isactive':True},
            {'name':'Pending Sign Off','isactive':True},
            {'name':'Sign Off Complete','isactive':True},
            {'name':'No Records Response','isactive':True},
           
        ]
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProgramAreaDivisionStages')
    op.drop_table('ProgramAreaDivisions')
    # ### end Alembic commands ###