"""empty message

Revision ID: be926c984a59
Revises: 5c10c2b1b92a
Create Date: 2021-10-25 11:22:00.712854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be926c984a59'
down_revision = '5c10c2b1b92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIMinistryRequests', sa.Column('closedate', sa.DateTime(), nullable=True))
    op.add_column('FOIMinistryRequests', sa.Column('closereasonid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'FOIMinistryRequests', 'CloseReasons', ['closereasonid'], ['closereasonid'])   
     
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'FOIMinistryRequests', type_='foreignkey')
    op.drop_column('FOIMinistryRequests', 'closereasonid')
    op.drop_column('FOIMinistryRequests', 'closedate')    
    # ### end Alembic commands ###
