"""empty message

Revision ID: beb310568ee4
Revises: 3ef2a6dbf556
Create Date: 2023-05-29 17:59:09.742752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'beb310568ee4'
down_revision = '3ef2a6dbf556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIMinistryRequests', sa.Column('linkedrequests', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('FOIRawRequests', sa.Column('linkedrequests', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIMinistryRequests', 'linkedrequests')
    op.drop_column('FOIRawRequests', 'linkedrequests')
    # ### end Alembic commands ###