"""empty message

Revision ID: c1c980e4b969
Revises: cd078dd1b149
Create Date: 2022-10-07 05:32:35.308785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String
from datetime import datetime
import os

# revision identifiers, used by Alembic.
revision = 'c1c980e4b969'
down_revision = 'cd078dd1b149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentPathMapper',
        sa.Column('documentpathid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('category', sa.Text,nullable=False),
        sa.Column('bucket', sa.Text,nullable=False),
        sa.Column('attributes', sa.Text,nullable=True),
        sa.Column('isactive', sa.Boolean(), nullable=False),
        sa.Column('createdby', sa.String(length=120), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.now()),
        sa.Column('updatedby', sa.String(length=120), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('documentpathid')
    )
    docment_path_mapper = table('DocumentPathMapper',
                                 column('category',String),
                                 column('bucket',String),
                                 column('attributes',String),
                                 column('isactive',Boolean),
                                 column('createdby',String),
                                   )

    s3environment = os.getenv('OSS_S3_ENVIRONMENT')

    op.bulk_insert(
        docment_path_mapper,
        [
            {'category':'Attachments','bucket': s3environment + '-forms-foirequests','isactive':True,'createdby':'System'},
        ]
    )
    op.execute('''INSERT INTO public."DocumentPathMapper"(
	category, bucket, isactive, createdby)
	Select 'Records', lower(bcgovcode) || '-''' + s3environment + '''' , true, 'System' from
	public."ProgramAreas" where isactive = true''')


    # ### end Alembic commands ###

    # #### run the following query separately through pgAdmin

    # update public."DocumentPathMapper" set attributes = '{
    #     "s3accesskey":"** enter access key **",
    #     "s3secretkey":"** enter secret key **"
    # }' where bucket ilike '** enter bucket name here **%'


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentPathMapper')
    # ### end Alembic commands ###
