"""empty message

Revision ID: c2b0e6e5352e
Revises: dd1c1df8264a
Create Date: 2022-11-14 12:10:32.561867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b0e6e5352e'
down_revision = 'dd1c1df8264a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Watcher\', \'Watcher\', true);commit;')  
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'User Assignment Removal\', \'User Assignment Removal\', true);commit;')  
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Email Failure\', \'Email Failure\', true);commit;')
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Payment\', \'Payment\', true);commit;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Delete from public."NotificationTypes" where name in (\'Watcher\');commit;')
    op.execute('Delete from public."NotificationTypes" where name in (\'User Assignment Removal\');commit;')
    op.execute('delete from  public."NotificationTypes" where name in (\'Email Failure\');commit;')
    op.execute('delete from  public."NotificationTypes" where name in (\'Payment\');commit;')
    # ### end Alembic commands ###
