"""empty message

Revision ID: c3e447d3d94d
Revises: fe203f06525d
Create Date: 2024-06-05 12:32:36.602944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3e447d3d94d'
down_revision = 'fe203f06525d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments" DROP CONSTRAINT "FOIApplicantCorrespondenceAttachments_pkey";') 
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  ADD COLUMN "version" INTEGER DEFAULT 1;')
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments" ADD PRIMARY KEY (applicantcorrespondenceattachmentid, version);') 
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  ALTER COLUMN "applicantcorrespondenceid" DROP NOT NULL;')  
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  ADD COLUMN "isresponse" BOOLEAN DEFAULT FALSE;')  
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  ADD COLUMN "applicantcorrespondenceresponseid" INTEGER;')  
    
    op.create_table('FOIApplicantCorrespondenceResponses',
    sa.Column('applicantcorrespondenceresponseid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('applicantcorrespondenceid', sa.Integer(), nullable=True),    
    sa.Column('isdeleted', sa.Boolean(), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),    
    sa.Column('foiministryrequest_id', sa.Integer(), nullable=True),
    sa.Column('foiministryrequestversion_id', sa.Integer(), nullable=True),
 
    sa.ForeignKeyConstraint(['foiministryrequest_id', 'foiministryrequestversion_id'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.PrimaryKeyConstraint('applicantcorrespondenceresponseid', 'version')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  ALTER COLUMN "applicantcorrespondenceid" DROP NOT NULL;')  
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  DROP COLUMN "isresponse";')  
    op.execute('ALTER TABLE public."FOIApplicantCorrespondenceAttachments"  DROP COLUMN "applicantcorrespondenceresponseid";')  
    op.drop_table('FOIApplicantCorrespondenceResponses')
    # ### end Alembic commands ###
