"""empty message

Revision ID: c54870295758
Revises: 0b551f4a8cce
Create Date: 2023-06-13 10:27:04.512021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c54870295758'
down_revision = '0b551f4a8cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIUsers',
    sa.Column('foiuserid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text, nullable=False),
    sa.Column('preferred_username', sa.Text, nullable=True),
    sa.Column('firstname', sa.Text, nullable=True),
    sa.Column('lastname', sa.Text, nullable=True),    
    sa.Column('email', sa.Text, nullable=True),
    sa.Column('isactive', sa.Boolean, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('foiuserid'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIUsers')
    # ### end Alembic commands ###
