"""fee_payment

Revision ID: c5b40cc3adfb
Revises: 5c17c63881c8
Create Date: 2021-10-18 20:52:52.502931

"""

from datetime import date

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5b40cc3adfb'
down_revision = '5c17c63881c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    revenue_account = op.create_table('RevenueAccounts',
                                      sa.Column('revenue_account_id', sa.Integer(), autoincrement=True, nullable=False),
                                      sa.Column('client', sa.String(length=3), nullable=True),
                                      sa.Column('responsibility_centre', sa.String(length=5), nullable=True),
                                      sa.Column('service_line', sa.String(length=5), nullable=True),
                                      sa.Column('stob', sa.String(length=4), nullable=True),
                                      sa.Column('project_code', sa.String(length=7), nullable=True),
                                      sa.PrimaryKeyConstraint('revenue_account_id')
                                      )
    fee_code = op.create_table('FeeCodes',
                               sa.Column('fee_code_id', sa.Integer(), autoincrement=True, nullable=False),
                               sa.Column('code', sa.String(length=10), nullable=False),
                               sa.Column('description', sa.String(length=100), nullable=True),
                               sa.Column('start_date', sa.Date(), nullable=False),
                               sa.Column('end_date', sa.Date(), nullable=True),
                               sa.Column('fee', sa.Float(), nullable=False),
                               sa.Column('revenue_account_id', sa.Integer(), nullable=False),
                               sa.ForeignKeyConstraint(['revenue_account_id'],
                                                       ['RevenueAccounts.revenue_account_id'], ),
                               sa.PrimaryKeyConstraint('fee_code_id')
                               )
    op.create_table('Payments',
                    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('fee_code_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('total', sa.Float(), nullable=False),
                    sa.Column('status', sa.String(length=10), nullable=False),
                    sa.Column('request_id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=False),
                    sa.Column('completed_on', sa.DateTime(), nullable=True),
                    sa.Column('paybc_url', sa.String(), nullable=True),
                    sa.Column('response_url', sa.String(), nullable=True),
                    sa.Column('order_id', sa.String(length=50), nullable=True),
                    sa.Column('transaction_number', sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(['fee_code_id'], ['FeeCodes.fee_code_id'], ),
                    sa.PrimaryKeyConstraint('payment_id')
                    )
    # Insert master fee records.
    op.bulk_insert(
        revenue_account,
        [
            {
                'revenue_account_id': 1,
                'client': '000',
                'responsibility_centre': '00000',
                'service_line': '00000',
                'stob': '0000',
                'project_code': '0000000'
            }
        ]
    )
    op.bulk_insert(
        fee_code,
        [
            {
                'code': 'FOI0001',
                'description': 'Freedom of Information Fee',
                'start_date': date.today(),
                'end_date': None,
                'fee': 10.00,
                'revenue_account_id': 1
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Payments')
    op.drop_table('FeeCodes')
    op.drop_table('RevenueAccounts')
    # ### end Alembic commands ###
