"""empty message

Revision ID: c87f7d0b9606
Revises: 4bd9d39a052e
Create Date: 2022-10-13 14:51:16.370522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c87f7d0b9606'
down_revision = '4bd9d39a052e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIApplicantCorrespondences', sa.Column('sentcorrespondencemessage', sa.Text, nullable=True))
    op.add_column('FOIApplicantCorrespondences', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('FOIApplicantCorrespondences', sa.Column('sentby', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIApplicantCorrespondences', 'sentcorrespondencemessage')
    op.drop_column('FOIApplicantCorrespondences', 'sent_at')
    op.drop_column('FOIApplicantCorrespondences', 'sentby')
    # ### end Alembic commands ###
