"""empty message

Revision ID: c8b147681f8b
Revises: e1f9f06bcc9f
Create Date: 2021-09-22 08:58:46.033017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b147681f8b'
down_revision = 'e1f9f06bcc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('createdby', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'createdby')
    # ### end Alembic commands ###
