"""empty message

Revision ID: ca17d3f81205
Revises: d1503b142889
Create Date: 2022-10-31 11:22:36.146431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca17d3f81205'
down_revision = 'd1503b142889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Watcher\', \'Watcher\', true);commit;')  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Delete from public."NotificationTypes" where name in (\'Watcher\');commit;')
    # ### end Alembic commands ###