"""empty message

Revision ID: cb8806d322d8
Revises: d6cb86e76ea7
Create Date: 2021-07-08 09:56:09.637108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb8806d322d8'
down_revision = 'd6cb86e76ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('wfinstanceid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'wfinstanceid')
    # ### end Alembic commands ###
