"""empty message

Revision ID: cb95a7af8067
Revises: ecf3560e32a3
Create Date: 2022-05-27 11:24:29.919209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb95a7af8067'
down_revision = 'ecf3560e32a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestDivisionFees',
    sa.Column('divisionfeeid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('divisionid', sa.Integer(), nullable=False),
    sa.Column('divisionname', sa.String(length=500), nullable=False),    
    sa.Column('ministryrequest_id', sa.Integer(), nullable=False),
    sa.Column('ministryrequest_version', sa.Integer(), nullable=False),    
    sa.Column('feedata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('estimatedhournotes', sa.TEXT(), nullable=True),  
    sa.Column('clarificationnotes', sa.TEXT(), nullable=True),      
    sa.Column('isresponsive', sa.Boolean(), nullable=False),
    sa.Column('responsivenotes', sa.TEXT(), nullable=True),
    sa.Column('isinternalresponsive', sa.Boolean(), nullable=False),
    sa.Column('internalresponsivenotes', sa.TEXT(), nullable=True),
    sa.Column('isexternalresponsive', sa.Boolean(), nullable=False),
    sa.Column('externalresponsivenotes', sa.TEXT(), nullable=True),    
    sa.Column('norecordapproval_at', sa.DateTime(), nullable=True),
    sa.Column('norecordapprovalby', sa.String(length=120), nullable=True),    
    sa.Column('searchsummary', sa.TEXT(), nullable=True),    
    sa.Column('isharmsassessed', sa.Boolean(), nullable=False),    
    sa.Column('concernnotes', sa.TEXT(), nullable=True),    
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completedby', sa.String(length=120), nullable=True),    
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['ministryrequest_id', 'ministryrequest_version'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'] ),
    sa.ForeignKeyConstraint(['divisionid'], ['ProgramAreaDivisions.divisionid']),
    sa.PrimaryKeyConstraint('divisionfeeid', 'version')
    )
    
    op.create_table('FOIRequestDivisionFeeDocumentMappings',
    sa.Column('divisionfeedocumentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('divisionfee_id', sa.Integer(), nullable=False),
    sa.Column('divisionfee_version', sa.Integer(), nullable=False),
    sa.Column('ministrydocumentid', sa.Integer(), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=True), 
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['divisionfee_id', 'divisionfee_version'], ['FOIRequestDivisionFees.divisionfeeid', 'FOIRequestDivisionFees.version'] ),
    sa.PrimaryKeyConstraint('divisionfeedocumentid')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestDivisionFees')
    op.drop_table('FOIRequestDivisionFeeDocumentMappings')
    # ### end Alembic commands ###
