"""empty message

Revision ID: cd078dd1b149
Revises: 4d97fe0e4979
Create Date: 2022-10-02 09:55:49.536826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd078dd1b149'
down_revision = '4d97fe0e4979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOIRequestRecords',
        sa.Column('recordid', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),   
        sa.Column('foirequestid', sa.Integer(), nullable=False),
        sa.Column('ministryrequestid', sa.Integer(), nullable=False),
        sa.Column('ministryrequestversion', sa.Integer(), nullable=True),  
        sa.Column('filename', sa.String(length=500),nullable=False),
        sa.Column('s3uripath', sa.Text,nullable=False),
        sa.Column('divisionid', sa.Integer(), nullable=True),
        sa.Column('createdby', sa.String(length=120), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updatedby', sa.String(length=120), nullable=True), 
        sa.Column('updated_at', sa.DateTime(), nullable=True),   
        sa.ForeignKeyConstraint(['ministryrequestid', 'ministryrequestversion'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version']),
        sa.ForeignKeyConstraint(['divisionid'], ['ProgramAreaDivisions.divisionid']),
        sa.PrimaryKeyConstraint('recordid' , 'version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRequestRecords')
    # ### end Alembic commands ###
