"""update-alsoknownas data length

Revision ID: cfe019598f8b
Revises: f5150a6969c6
Create Date: 2025-08-22 13:04:56.853452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfe019598f8b'
down_revision = 'f5150a6969c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "FOIRequestApplicants",
        "alsoknownas",
        existing_type=sa.String(length=50),
        type_=sa.String(length=255),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "FOIRequestApplicants",
        "alsoknownas",
        existing_type=sa.String(length=255),
        type_=sa.String(length=50),
    )
    # ### end Alembic commands ###
