"""empty message

Revision ID: d1503b142889
Revises: 7959ccaa7f9d
Create Date: 2022-10-04 16:15:34.458408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1503b142889'
down_revision = '7959ccaa7f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Division Due Reminder\', \'Division Due Reminder\', true);commit;') 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Delete from public."NotificationTypes" where name in (\'Division Due Reminder\');commit;') 
    # ### end Alembic commands ###
