"""empty message

Revision ID: d185518c3661
Revises: 7fa7236d06fb
Create Date: 2023-06-01 22:31:24.595281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd185518c3661'
down_revision = '7fa7236d06fb'

branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRequestStatuses" ADD COLUMN statuslabel VARCHAR(50);')
    op.execute('UPDATE public."FOIRequestStatuses" SET statuslabel = REPLACE(LOWER(name), \' \', \'\');')
    op.execute('ALTER TABLE public."FOIRequestStatuses" ALTER COLUMN statuslabel SET NOT NULL;')
    op.execute('ALTER TABLE public."FOIRequestStatuses" ADD CONSTRAINT unique_statuslabel UNIQUE (statuslabel);')

    op.execute('ALTER TABLE public."FOIMinistryRequests" ADD COLUMN requeststatuslabel VARCHAR(50);')
    op.execute('UPDATE public."FOIMinistryRequests" AS mr SET requeststatuslabel = st.statuslabel FROM public."FOIRequestStatuses" AS st WHERE mr.requeststatusid = st.requeststatusid;')
    op.execute('ALTER TABLE public."FOIMinistryRequests" ALTER COLUMN requeststatuslabel SET NOT NULL;')

    op.execute('ALTER TABLE public."FOIRawRequests" ADD COLUMN requeststatuslabel VARCHAR(50);')
    op.execute('UPDATE public."FOIRawRequests" SET requeststatuslabel = REPLACE(LOWER(status), \' \', \'\');')
    op.execute('ALTER TABLE public."FOIRawRequests" ALTER COLUMN requeststatuslabel SET NOT NULL;')

    op.execute('ALTER TABLE public."FOIRequestTeams" ADD COLUMN requeststatuslabel VARCHAR(50);')
    op.execute('UPDATE public."FOIRequestTeams" AS rt SET requeststatuslabel = st.statuslabel FROM public."FOIRequestStatuses" AS st WHERE rt.requeststatusid = st.requeststatusid;')
    op.execute('ALTER TABLE public."FOIRequestTeams" ALTER COLUMN requeststatuslabel SET NOT NULL;')
    # ### end Alembic commands ### 


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE public."FOIRequestStatuses" drop column statuslabel;')
    op.execute('ALTER TABLE public."FOIMinistryRequests" drop column requeststatuslabel;')
    op.execute('ALTER TABLE public."FOIRawRequests" drop column requeststatuslabel;')
    op.execute('ALTER TABLE public."FOIRequestTeams" drop column requeststatuslabel;')
    # ### end Alembic commands ###
