"""empty message

Revision ID: d43db71d53e5
Revises: 5782617db307
Create Date: 2023-08-18 12:40:33.968711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd43db71d53e5'
down_revision = '5782617db307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.execute('UPDATE public."OperatingTeams" set isactive = false where name in (\'Central Team\', \'Flex Team\', \'Justice Health Team\', \'Resource Team\', \'Social Education\');')
        
        op.execute('UPDATE public."FOIRequestTeams" set isactive = false where teamid in (select teamid from public."OperatingTeams" where name in (\'Central Team\', \'Flex Team\', \'Justice Health Team\', \'Resource Team\', \'Social Education\'));')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.execute('UPDATE public."OperatingTeams" set isactive = true where name in (\'Central Team\', \'Flex Team\', \'Justice Health Team\', \'Resource Team\', \'Social Education\');')

        op.execute('UPDATE public."FOIRequestTeams" set isactive = true where teamid in (select teamid from public."OperatingTeams" where name in (\'Central Team\', \'Flex Team\', \'Justice Health Team\', \'Resource Team\', \'Social Education\'));')

    # ### end Alembic commands ###
