"""empty message

Revision ID: d64df04da9df
Revises: c54870295758
Create Date: 2023-06-26 10:26:13.253713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd64df04da9df'
down_revision = 'c54870295758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX "FOIUsers_pusername" ON "FOIUsers"(preferred_username);')
    op.execute('CREATE INDEX "FOIRequestNotifications_axis" ON "FOIRequestNotifications"(axisnumber);')
    op.execute('CREATE INDEX "FOIRawRequestNotifications_axis" ON "FOIRawRequestNotifications"(axisnumber);')
    op.execute('CREATE INDEX "FOIRequestNotifications_typeid" ON "FOIRequestNotifications"(notificationtypeid);')
    op.execute('CREATE INDEX "FOIRawRequestNotifications_typeid" ON "FOIRawRequestNotifications"(notificationtypeid);')
    op.execute('CREATE INDEX "FOIRequestNotificationUsers_userid" ON "FOIRequestNotificationUsers"(userid);')
    op.execute('CREATE INDEX "FOIRawRequestNotificationUsers_userid" ON "FOIRawRequestNotificationUsers"(userid);')
    op.execute('CREATE INDEX "NotificationTypes_idx" ON "NotificationTypes"(notificationtypeid);')
    op.execute('CREATE INDEX "FOIMinistryRequests_axis" ON "FOIMinistryRequests"(axisrequestid);')
    op.execute('CREATE INDEX "FOIMinistryRequests_group" ON "FOIMinistryRequests"(assignedgroup);')
    op.execute('CREATE INDEX "FOIMinistryRequests_ministrygroup" ON "FOIMinistryRequests"(assignedministrygroup);')
    op.execute('CREATE INDEX "FOIMinistryRequests_statusid" ON "FOIMinistryRequests"(requeststatusid);')
    op.execute('CREATE INDEX "FOIMinistryRequests_assignedto" ON "FOIMinistryRequests"(assignedto)')
    op.execute('CREATE INDEX "FOIMinistryRequests_minassignedto" ON "FOIMinistryRequests"(assignedministryperson);')
    op.execute('CREATE INDEX "FOIRawRequests_axis" ON "FOIRawRequests"(axisrequestid);')    
    op.execute('CREATE INDEX "FOIRequests_rawid" ON "FOIRequests"(foirawrequestid);')
    op.execute('CREATE INDEX "FOIRestrictedMinistryRequests_minid" ON "FOIRestrictedMinistryRequests"(ministryrequestid);')
    op.execute('CREATE INDEX "FOIRawRequestWatchers_watchedby" ON "FOIRawRequestWatchers"(watchedby);')
    op.execute('CREATE INDEX "FOIRequestWatchers_watchedby" ON "FOIRequestWatchers"(watchedby);')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX "FOIUsers_pusername";')
    op.execute('DROP INDEX "FOIRequestNotifications_axis";')
    op.execute('DROP INDEX "FOIRawRequestNotifications_axis";')
    op.execute('DROP INDEX "FOIRequestNotifications_typeid";')
    op.execute('DROP INDEX "FOIRawRequestNotifications_typeid";')
    op.execute('DROP INDEX "FOIRequestNotificationUsers_userid";')
    op.execute('DROP INDEX "FOIRawRequestNotificationUsers_userid";')
    op.execute('DROP INDEX "NotificationTypes_idx";')
    op.execute('DROP INDEX "FOIMinistryRequests_axis";')
    op.execute('DROP INDEX "FOIMinistryRequests_group";')
    op.execute('DROP INDEX "FOIMinistryRequests_ministrygroup";')
    op.execute('DROP INDEX "FOIMinistryRequests_statusid";')
    op.execute('DROP INDEX "FOIMinistryRequests_assignedto";')
    op.execute('DROP INDEX "FOIMinistryRequests_minassignedto";')
    op.execute('DROP INDEX "FOIRawRequests_axis";')    
    op.execute('DROP INDEX "FOIRequests_rawid";')
    op.execute('DROP INDEX "FOIRestrictedMinistryRequests_minid";')    
    op.execute('DROP INDEX "FOIRawRequestWatchers_watchedby";')
    op.execute('DROP INDEX "FOIRequestWatchers_watchedby";')
    # ### end Alembic commands ###
