"""empty message

Revision ID: dc99ffc3a6f7
Revises: 8487688c2e35
Create Date: 2024-06-26 11:57:44.772711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc99ffc3a6f7'
down_revision = '8487688c2e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by FAlembic - please adjust! ###
    op.execute("""
               INSERT INTO public."ApplicantCorrespondenceTemplates"( documenturipath, "name", description, active, "version", created_at, createdby, display) 
               VALUES
               ('/TEMPLATES/EMAILS/extension_pb.html', 'EXTENSIONS-PB', 'Extensions for public body', true, 1, now(), 'system', true);
               commit;""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""delete from public."ApplicantCorrespondenceTemplates" act  where name = 'EXTENSIONS-PB'; commit;""")
    # ### end Alembic commands ###
