"""empty message

Revision ID: dd1c1df8264a
Revises: fdd652c06c3e
Create Date: 2022-11-14 11:52:52.287598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1c1df8264a'
down_revision = 'fdd652c06c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Insert into public."NotificationTypes" (name, description, isactive) values (\'Division Due Reminder\', \'Division Due Reminder\', true);commit;') 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('Delete from public."NotificationTypes" where name in (\'Division Due Reminder\');commit;') 
    # ### end Alembic commands ###
