"""empty message

Revision ID: e1f9f06bcc9f
Revises: f61413c0517d
Create Date: 2021-09-15 13:15:25.336038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f9f06bcc9f'
down_revision = 'f61413c0517d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('ispiiredacted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'ispiiredacted')
    # ### end Alembic commands ###
