"""empty message

Revision ID: e3839ed176e5
Revises: 8bcfbbd263fe
Create Date: 2021-11-08 15:47:06.092261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3839ed176e5'
down_revision = '8bcfbbd263fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.add_column('FOIMinistryRequestDocuments', sa.Column('filename', sa.String(length=120), nullable=True))
    op.add_column('FOIMinistryRequestDocuments', sa.Column('isactive', sa.Boolean, nullable=True))
    op.add_column('FOIMinistryRequestDocuments', sa.Column('category', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIMinistryRequestDocuments', 'filename')
    op.drop_column('FOIMinistryRequestDocuments', 'isactive')
    op.drop_column('FOIMinistryRequestDocuments', 'category')
    # ### end Alembic commands ###
