"""empty message

Revision ID: e3fc2c864677
Revises: fc26a7b65a2a
Create Date: 2021-11-17 10:15:40.926895

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'e3fc2c864677'
down_revision = 'fc26a7b65a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    op.create_table('FOIRawRequestDocuments',
    sa.Column('foidocumentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('documentpath', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('isactive', sa.Boolean, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.now()),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('foirequest_id', sa.Integer(), nullable=True),
    sa.Column('foirequestversion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foirequest_id', 'foirequestversion_id'], ['FOIRawRequests.requestid', 'FOIRawRequests.version']),
    sa.PrimaryKeyConstraint('foidocumentid', 'version')
    )   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOIRawRequestDocuments')
    # ### end Alembic commands ###
