"""empty message

Revision ID: e630f23aaaf9
Revises: 789c89c4306c
Create Date: 2022-03-03 13:20:28.123808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e630f23aaaf9'
down_revision = '789c89c4306c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('axisrequestid', sa.String(length=120), nullable=True))
    op.add_column('FOIRawRequests', sa.Column('axissyncdate', sa.DateTime(), nullable=True))
    op.add_column('FOIMinistryRequests', sa.Column('axisrequestid', sa.String(length=120), nullable=True))
    op.add_column('FOIMinistryRequests', sa.Column('axissyncdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'axisrequestid')
    op.drop_column('FOIRawRequests', 'axissyncdate')
    op.drop_column('FOIMinistryRequests', 'axisrequestid')
    op.drop_column('FOIMinistryRequests', 'axissyncdate')
    # ### end Alembic commands ###
