"""empty message

Revision ID: e6c05dfb6977
Revises: 5e17e1bf2181
Create Date: 2022-05-16 16:57:06.298429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c05dfb6977'
down_revision = '5e17e1bf2181'
branch_labels = None
depends_on = None


def upgrade():

    # Personal - Deduplication
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Intake Team\'),null,true);commit;')   
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'AEST Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'AED\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'AGR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'AGR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'AG Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MAG\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'MCF Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CFD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'CITZ Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CTZ\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'EDU Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EDU\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'EMLI Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EML\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'ENV Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MOE\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'FIN Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FIN\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'FOR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FOR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'HLTH Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'HLTH\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'IRR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IRR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'JERI Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'JER\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'LBR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LBR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'MMHA Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MHA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'MUNI Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MMA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'PSSG Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'SDPR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MSD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'TACS Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TAC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'TRAN Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TRA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'OCC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OCC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'PSA Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'BRD Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'BRD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'CLB Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CLB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'CAS Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CAS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'EMBC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EMB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'EAO Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EAO\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'GCPE Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'GCP\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'IIO Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IIO\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'PREM Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OOP\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'LDB Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LDB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'TIC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TIC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'OBC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OBC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'MGC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MGC\'),true);commit;')
	
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'CLB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'EDU\'),true);commit;')    
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'MSD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'AED\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'GCP\'),true);commit;')			
			
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'AGR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EML\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EAO\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MOE\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IRR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FOR\'),true);commit;')
	
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'MCFD Personals Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CFD\'),true);commit;')
			
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MMA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LBR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'JER\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TRA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TAC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TIC\'),true);commit;')
			
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FIN\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OOP\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CTZ\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OBC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MGC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CAS\'),true);commit;')
    
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MAG\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OCC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LDB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EMB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'HLTH\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MHA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IIO\'),true);commit;')

    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'DAS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Deduplication\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LWR\'),true);commit;')

    # Personal - Harms Assessment

    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Intake Team\'),null,true);commit;')   
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'AEST Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'AED\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'AGR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'AGR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'AG Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MAG\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'MCF Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CFD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'CITZ Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CTZ\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'EDU Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EDU\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'EMLI Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EML\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'ENV Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MOE\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'FIN Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FIN\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'FOR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FOR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'HLTH Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'HLTH\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'IRR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IRR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'JERI Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'JER\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'LBR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LBR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'MMHA Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MHA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'MUNI Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MMA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'PSSG Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'SDPR Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MSD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'TACS Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TAC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'TRAN Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TRA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'OCC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OCC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'PSA Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'BRD Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'BRD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'CLB Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CLB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'CAS Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CAS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'EMBC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EMB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'EAO Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EAO\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'GCPE Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'GCP\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'IIO Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IIO\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'PREM Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OOP\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'LDB Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LDB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'TIC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TIC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'OBC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OBC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'MGC Ministry Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MGC\'),true);commit;')
	
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'CLB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'EDU\'),true);commit;')    
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'MSD\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'AED\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Social Education\'),(select programareaid from public."ProgramAreas" where iaocode=\'GCP\'),true);commit;')			
			
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'AGR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EML\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EAO\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MOE\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IRR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FOR\'),true);commit;')
	
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'MCFD Personals Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CFD\'),true);commit;')
			
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MMA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LBR\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'JER\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TRA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TAC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Business Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'TIC\'),true);commit;')
			
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'FIN\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OOP\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CTZ\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OBC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MGC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Central Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'CAS\'),true);commit;')
    
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MAG\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'PSS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'OCC\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LDB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'EMB\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'HLTH\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'MHA\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Justice Health Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'IIO\'),true);commit;')

    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'DAS\'),true);commit;')
    op.execute('Insert into public."FOIRequestTeams" (requesttype, requeststatusid, teamid, programareaid, isactive) values (\'Personal\',(select requeststatusid from public."FOIRequestStatuses" where name=\'Harms Assessment\'),(select teamid from public."OperatingTeams" where name=\'Resource Team\'),(select programareaid from public."ProgramAreas" where iaocode=\'LWR\'),true);commit;')


def downgrade():
    op.execute('DELETE FROM public."FOIRequestTeams" WHERE requesttype = \'Personal\'and requeststatusid in (select requeststatusid from public."FOIRequestStatuses" where name in (\'Harms Assessment\',\'Deduplication\'));commit;')
