"""empty message

Revision ID: eae7d7d5b20c
Revises: ad8196316506
Create Date: 2021-11-05 22:27:31.741726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae7d7d5b20c'
down_revision = 'ad8196316506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    document_type = op.create_table('DocumentTypes',
        sa.Column('document_type_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('document_type_name', sa.String(length=30), nullable=False, unique=False),
        sa.Column('description', sa.String(length=100), nullable=True, unique=False),
        sa.PrimaryKeyConstraint('document_type_id')
        )

    document_template = op.create_table('DocumentTemplates',
        sa.Column('template_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('cdogs_hash_code', sa.String(length=64), nullable=True, unique=False),
        sa.Column('extension', sa.String(length=10), nullable=False),
        sa.Column('document_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['document_type_id'],
                                ['DocumentTypes.document_type_id'], ),
        sa.PrimaryKeyConstraint('template_id')
        )
    # Insert document template records.
    op.bulk_insert(
        document_type,
        [
            {
                'document_type_id': 1,
                'document_type_name': 'Receipt Template',
                'description': 'A word template for generating receipts with Common Document Generation Service'
            }
        ]
    )
    op.bulk_insert(
        document_template,
        [
            {
                'template_id': 1,
                'cdogs_hash_code': None,
                'extension': 'docx',
                'document_type_id': 1,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentTemplates')
    op.drop_table('DocumentTypes')
    # ### end Alembic commands ###
