"""empty message

Revision ID: eea7ea4d60ac
Revises: d64df04da9df
Create Date: 2023-07-12 18:09:59.244266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import column, table
from sqlalchemy.sql.sqltypes import Boolean, String

# revision identifiers, used by Alembic.
revision = 'eea7ea4d60ac'
down_revision = 'd64df04da9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    requeststatus_table = table('FOIRequestStatuses',
                                 column('name',String),
                                 column('description',String),
                                 column('isactive',Boolean),
                                   ) 
    op.bulk_insert(
        requeststatus_table,
        [
            {'name':'Peer Review','description':'Peer Review','isactive':True}
           
        ]
    ) # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('delete from public."FOIRequestStatuses" where name in (\'Peer Review\');')
    # ### end Alembic commands ###
