"""empty message

Revision ID: f541c6849055
Revises: 27e2c0dd4c3c
Create Date: 2021-07-08 10:30:44.371282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f541c6849055'
down_revision = '27e2c0dd4c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'updated_at')
    # ### end Alembic commands ###
