"""empty message

Revision ID: f61413c0517d
Revises: 490bdb384e28
Create Date: 2021-08-23 10:00:27.399097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61413c0517d'
down_revision = '490bdb384e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FOIRawRequests', sa.Column('assignedgroup', sa.String(length=250), nullable=True))
    op.add_column('FOIMinistryRequests', sa.Column('assignedgroup', sa.String(length=250), nullable=True))
    op.alter_column('FOIMinistryRequests', 'assignedto', nullable=True)
    #ALTER TABLE "FOIMinistryRequests" ALTER COLUMN "assignedto" DROP NOT NULL;
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FOIRawRequests', 'assignedgroup')
    op.drop_column('FOIMinistryRequests', 'assignedgroup')
    op.alter_column('FOIMinistryRequests', 'assignedto', nullable=False)
    # ### end Alembic commands ###
