"""empty message

Revision ID: f994bce775b6
Revises: 828583f30d60
Create Date: 2023-04-06 14:44:48.587573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f994bce775b6'
down_revision = '828583f30d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProgramAreaDivisions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ProgramAreaDivisions', sa.Column('updatedby', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProgramAreaDivisions', 'updated_at')
    op.drop_column('ProgramAreaDivisions', 'updatedby')
    # ### end Alembic commands ###
