"""empty message

Revision ID: fe203f06525d
Revises: 10aa6d69aeed
Create Date: 2024-05-27 09:44:03.810144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe203f06525d'
down_revision = 'e698b39da6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FOICorrespondenceEmails',
    sa.Column('correspondenceemailid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),
    sa.Column('foiministryrequest_id', sa.Integer(), nullable=True),
    sa.Column('foiministryrequestversion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foiministryrequest_id', 'foiministryrequestversion_id'], ['FOIMinistryRequests.foiministryrequestid', 'FOIMinistryRequests.version'], ),
    sa.PrimaryKeyConstraint('correspondenceemailid')
    )

    op.create_table('FOIApplicantCorrespondenceEmails',
    sa.Column('applicantcorrespondenceemailid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicantcorrespondenceid', sa.Integer(), nullable=False),
    sa.Column('correspondence_to', sa.Text(), nullable=False), 
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('createdby', sa.String(length=120), nullable=True),
    sa.Column('updatedby', sa.String(length=120), nullable=True),    
    sa.ForeignKeyConstraint(['applicantcorrespondenceid'], ['FOIApplicantCorrespondences.applicantcorrespondenceid'] ,),
    sa.PrimaryKeyConstraint('applicantcorrespondenceemailid')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FOICorrespondenceEmails')
    op.drop_table('FOIApplicantCorrespondenceEmails')
    # ### end Alembic commands ###
