<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>7bc44efa-626d-4ee9-b0c6-9508a3d2e850</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btncfrsave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btncfrsave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e89253c-59bd-4dcc-bf3a-49cb32e419d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b65be265-a65c-4280-bc94-8e495bfc565d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-4 btn btn-bottom btn-save</value>
      <webElementGuid>fa58f1ea-d72f-482e-92fe-dbe8ea0dc207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btncfrsave</value>
      <webElementGuid>6c53433d-4eb2-48ed-80ee-31f89bf068fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>2feebe55-508d-4792-8e7f-b39c5eaba013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>3f113522-4d9e-41e6-960f-dce46f98f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btncfrsave&quot;)</value>
      <webElementGuid>1f556df8-6120-4e37-a422-c4a56027c33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btncfrsave']</value>
      <webElementGuid>590bf853-7333-4637-8c77-f21e4f8453d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[5]/button</value>
      <webElementGuid>650682b4-b6ad-405b-a97e-c7f97a82c865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combined suggestions for futher clarifications'])[2]/following::button[1]</value>
      <webElementGuid>df7d0122-3f6a-409f-8a74-d462ddf46ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combined suggestions for futher clarifications'])[1]/following::button[1]</value>
      <webElementGuid>529976dd-3a0a-4ebb-954c-d71e2a418dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Create New CFR Form'])[1]/preceding::button[1]</value>
      <webElementGuid>c788d34f-fb90-4bb8-a945-3ba1dcafd697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #ABC-2099-1759409'])[1]/preceding::button[2]</value>
      <webElementGuid>ba4b02d2-52e7-4fd9-a18e-c226d6df2578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>4151049d-a4e8-4e30-9602-4ccb5d76e6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btncfrsave' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>a421b602-865a-45c9-8ffb-e9510c61cee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
