<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_ABC-2099-1759409</name>
   <tag></tag>
   <elementGuidId>6230c78f-996a-4773-9ff6-98d7585ffeef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.foileftpanelrequestno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>37c23443-00e0-4e74-85db-6cf657a00889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foileftpanelrequestno</value>
      <webElementGuid>117cd5ca-cdb3-4f19-9b4e-e0e915af6d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABC-2099-1759409</value>
      <webElementGuid>4d2e9c4b-cb73-489f-84de-804b677653b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;foiformcontent&quot;]/div[@class=&quot;foitabbedContainer&quot;]/div[@class=&quot;foitabheadercollection foitabheaderFeeBG&quot;]/h4[@class=&quot;foileftpanelrequestno&quot;]</value>
      <webElementGuid>564e1d52-7c58-46c4-8554-b2c8f69f2b77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/h4</value>
      <webElementGuid>c368a329-4981-4edf-a86f-8271773acaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::h4[1]</value>
      <webElementGuid>856b3f9a-29b3-4308-ab90-3d7586e36a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::h4[1]</value>
      <webElementGuid>336a4f3d-f856-41ba-b9ab-9aaff186ae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fee Estimate'])[1]/preceding::h4[1]</value>
      <webElementGuid>f0a7faef-5a13-45ec-80f0-6b368cf26f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>b3a9938e-fa7d-4330-9d79-d9abcf40410a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'ABC-2099-1759409' or . = 'ABC-2099-1759409')]</value>
      <webElementGuid>f8c5583f-7cd5-4e68-b8aa-0d5dcb0302e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
