<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s this)_cancelButton</name>
   <tag></tag>
   <elementGuidId>14779b70-fb79-437c-822f-9502f04f8228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cancelButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cancelButton&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f5fda41-81d0-4504-a79b-7b39e356e657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d75303f-99c9-486d-b451-8d03d1dcbea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelButton</value>
      <webElementGuid>0a00f76c-27e3-49a7-8c07-c6c25f06f5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>1b42c544-b81f-45cd-8d21-2b9841190234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DisableButtons(true);CancelTrans();</value>
      <webElementGuid>0294d411-b4ee-41d3-9b5f-9e2d5f586559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPayment&quot;)/table[2]/tbody[1]/tr[12]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/input[1]</value>
      <webElementGuid>fb3c035a-5807-4f5f-a06f-bf75ccd65514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cancelButton']</value>
      <webElementGuid>7e9069f3-c78a-4aa3-8039-3bce31f0d859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPayment']/table[2]/tbody/tr[12]/td/table/tbody/tr/td/input</value>
      <webElementGuid>e4bed5ee-c577-4e8f-9f3b-912409c7598a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td/input</value>
      <webElementGuid>00457e7e-ade3-4210-b57b-c7e20b122c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'cancelButton']</value>
      <webElementGuid>aa981df6-bc47-4fb8-b350-a27d87189bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
