<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EDU_selectspanEDU</name>
   <tag></tag>
   <elementGuidId>b554a910-a534-4f2f-8654-83cb3528fdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='selectspanEDU']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectspanEDU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3809166b-d1d0-41ca-84f1-87d3464e60e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectspanEDU</value>
      <webElementGuid>9475b12f-66e8-428f-afba-33b39f2c961f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>5be13301-7b25-4af5-9572-8c9ce937fdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectspanEDU&quot;)</value>
      <webElementGuid>07db8047-ced5-47a6-8915-999f522c88b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='selectspanEDU']</value>
      <webElementGuid>87079a8e-3617-4306-bf8c-6beac69dd17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lblEDU']/span</value>
      <webElementGuid>a58d0f2d-a64d-4fff-b031-3bca968a4eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[11]/span</value>
      <webElementGuid>2c24c425-0f54-4159-b465-5d60a42d2ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'selectspanEDU']</value>
      <webElementGuid>b038c17e-5e6e-4ce9-aa03-8f4b786fd8a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
