<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hardcopy Estimated Pages_hardcopyPages</name>
   <tag></tag>
   <elementGuidId>1ac96068-b879-462e-9b5a-f1fa6e956a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimatedhardcopy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimatedhardcopy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4909a0ed-44a3-460c-8699-5171f88c7a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aefaf23d-53d7-4467-9692-3a0380157371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimatedhardcopy</value>
      <webElementGuid>dc811b16-229f-41c4-819a-562807fb66d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hardcopyPages</value>
      <webElementGuid>83167461-134e-41c1-b947-77d1c040a5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1b49bf4a-b481-450a-81b1-484d5edca385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>estimatedelectronic-label</value>
      <webElementGuid>b4fbdd55-1bc1-412e-82ad-af87177db9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c59d3d1b-292d-46aa-873e-bcf8b25b882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b9c3d95-2cf1-446b-91a9-f3b85e586e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^([1-9]+|0{1})(?:.d{1,2})?$</value>
      <webElementGuid>17effefe-2925-415f-a805-7b7d9afb4fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedEnd css-1uvydh2</value>
      <webElementGuid>c4cfab97-d63e-45e2-b7c5-ad3497271091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>662c7734-6cea-4417-9a8f-b36f2faa2473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimatedhardcopy&quot;)</value>
      <webElementGuid>e7ad8b62-7159-466c-91d3-878beca99cf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimatedhardcopy']</value>
      <webElementGuid>bec64c86-76be-4eeb-8677-849d80870920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[8]/div/div[2]/div/input</value>
      <webElementGuid>92cf010f-69d5-4bfa-b26b-69a32578271b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/input</value>
      <webElementGuid>ae4efe72-ba96-4d3d-9542-7b58eb3b9a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimatedhardcopy' and @name = 'hardcopyPages' and @type = 'number']</value>
      <webElementGuid>2316c097-d33e-4a9c-bd8b-5b76cc67c3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
