<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount Paid_amountPaid</name>
   <tag></tag>
   <elementGuidId>1706f688-0741-456e-8275-e4329c60ccea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amountpaid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amountpaid']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'amountpaid' and @name = 'amountPaid' and @type = 'number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf377506-c338-4b9c-8610-d0f28fca7caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce3d1f64-c32c-44a6-b0a6-826a1e466a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amountpaid</value>
      <webElementGuid>90b9bdda-8327-4961-b653-3b6d5876f09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amountPaid</value>
      <webElementGuid>a4df2ecb-25f7-4f40-8d72-12a2ccb1bd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>00afee30-532e-42df-ba24-afa3c31993f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>amountpaid-label</value>
      <webElementGuid>dda2b30d-eb7b-46da-86e4-cc83b81bcef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>58af4a21-095e-4b71-bc99-c6e93bdca241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36ee133b-1b62-4747-b0d0-b47363a3e8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>613b9ff0-02fc-4724-b3eb-1a48385bf18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedStart css-1ixds2g</value>
      <webElementGuid>796a376f-d28f-44c0-a09c-4a99be8a41ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c7ffedf4-d6f6-4693-8db6-e752a454cfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amountpaid&quot;)</value>
      <webElementGuid>b7ee1a3d-38f1-42af-be66-258a90b6fabf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amountpaid']</value>
      <webElementGuid>3258badd-3067-42c9-bb43-accb1c05be25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1bca60f3-7ac1-46da-9ca0-211bf40de5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>16899c66-0b6f-4efe-ba8d-aed07f0d9f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amountpaid' and @name = 'amountPaid' and @type = 'number']</value>
      <webElementGuid>df5d2922-8335-4dc3-aa23-65203fe30ab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
