<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimated Hours_locating</name>
   <tag></tag>
   <elementGuidId>12b8a60c-61ea-434d-a4cf-2383e0b1a6ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimatedlocating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimatedlocating']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'estimatedlocating' and @name = 'locating' and @type = 'number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3a8f02e-db34-48d1-8d20-6825d8790196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ae4c629-8109-4a66-8005-bfeac96e99cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimatedlocating</value>
      <webElementGuid>32b5c071-a43e-4186-84dc-cbfad5da219b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locating</value>
      <webElementGuid>90d34570-fabc-4a8f-af77-0be07f808a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1bb92170-a9c5-4035-b4ed-41373bf8ee8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>estimatedlocating-label</value>
      <webElementGuid>54201759-6e38-49af-b55d-228d698650b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.25</value>
      <webElementGuid>20f9802b-4238-41b7-a1de-d7e8bfd26c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c729bd6c-fe17-4626-a569-b6efaf831553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedEnd css-1uvydh2</value>
      <webElementGuid>5da31301-01e3-4676-a11f-aeea23029b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b6b819b-3de2-47c7-ad03-545764592878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimatedlocating&quot;)</value>
      <webElementGuid>13b2e589-20d3-4527-ab43-66041c5a89ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimatedlocating']</value>
      <webElementGuid>4298235f-b157-4955-b985-8008a52f6b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>3245978f-39ca-46a7-992d-7b0d730db82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>aeb76e77-7bec-4dba-98c0-ac8f0cd86ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimatedlocating' and @name = 'locating' and @type = 'number']</value>
      <webElementGuid>fec8a061-8caf-4dfa-84b1-b8d97ba59e3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
