<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimated Hours_producing</name>
   <tag></tag>
   <elementGuidId>de730d95-8725-4b7d-b347-ff10b20494ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimatedproducing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimatedproducing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fb10d3a-f201-42cc-a3c2-48dded6cf06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60435d7d-5262-46c8-adda-ee08d93bc2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimatedproducing</value>
      <webElementGuid>bca7d3ff-1dfc-4ae7-8f08-da409b6baf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>producing</value>
      <webElementGuid>72f7ab0c-4e2a-484d-a2ab-9b2f86d3dccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>71ca9e79-9dad-43e5-88c2-b7a388d9ab90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>estimatedproducing-label</value>
      <webElementGuid>8600e3cd-ef60-4baf-a829-9ba78b9d3b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.25</value>
      <webElementGuid>950949fb-12a4-445d-a963-a0782fcc5b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56d4bc8b-f827-446e-81c4-50e25a7b01e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedEnd css-1uvydh2</value>
      <webElementGuid>62304f56-f589-4987-9acd-e51d41b145d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f371be1d-64bf-4ad9-b390-9c5114752cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimatedproducing&quot;)</value>
      <webElementGuid>a94f06d3-8c55-46cf-9125-e99425bad89e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimatedproducing']</value>
      <webElementGuid>3fa22062-a43d-4f50-87d5-aec96ce19243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>fb778dcf-4e3e-49e6-9886-a4faf8b21bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>8b391349-c699-4209-985f-504da24f5807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimatedproducing' and @name = 'producing' and @type = 'number']</value>
      <webElementGuid>0b12bf31-1ff5-4b4d-8fb0-952250287d39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
