<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimated Hours IAO_iaoPreparing</name>
   <tag></tag>
   <elementGuidId>3c094bad-bbeb-40ce-b885-4ae442083f3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimatediaopreparing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimatediaopreparing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4413f76f-2217-4cdc-8664-1c508d6dca00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d3b05d1-a110-4f35-9905-f04601110bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimatediaopreparing</value>
      <webElementGuid>853c0666-78de-42ce-b6a3-4a95edb5558c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iaoPreparing</value>
      <webElementGuid>88cf0cd6-86f0-4b0c-addc-d3b2569cf77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8b7461dd-ef67-48c6-9678-9b442f26eedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>estimatedpreparing-label</value>
      <webElementGuid>4a1b760b-2ab5-43be-b176-32dbf53076fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.25</value>
      <webElementGuid>93d61a38-2d11-416d-93b0-9dbe3d69003e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>57bce7ab-6d51-4f68-8131-66c903a51cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedEnd css-1uvydh2</value>
      <webElementGuid>8631c012-2e27-4dea-9e4b-3cf2e4b27042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2891e703-30ee-4fc8-a271-b6e46a825132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimatediaopreparing&quot;)</value>
      <webElementGuid>622818ad-50b2-4fda-a10c-0562f4341f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimatediaopreparing']</value>
      <webElementGuid>aa9e9866-a755-46e6-b937-1a15c72333d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[6]/div/div/div/input</value>
      <webElementGuid>b4b4db06-fd5c-4f12-a977-9ff34e5b5fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div[6]/div/div/div/input</value>
      <webElementGuid>9512ed7a-e48a-4daf-8a8e-8bdd6ecdac22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimatediaopreparing' and @name = 'iaoPreparing' and @type = 'number']</value>
      <webElementGuid>3acf590d-bac5-4353-ab4d-978cbfc2d7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
