<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Balance Remaining_balanceRemaining</name>
   <tag></tag>
   <elementGuidId>799928ea-3f8f-4f03-a979-bb0435669826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#balanceremaining</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'balanceremaining']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='balanceremaining']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>071d39e7-a085-40f5-9695-1036174cab29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec1b0cc5-a6f2-470d-b3df-daa306a8fa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>balanceremaining</value>
      <webElementGuid>c343a52a-2cce-4838-92aa-f974356334d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>balanceRemaining</value>
      <webElementGuid>9c742f72-48c4-4967-93f8-ade816c66816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>62322f6c-91e8-4c70-b1d8-9cc0b4e23a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32a27dab-2315-4f2e-b97f-9436c6893e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>balanceremaining-label</value>
      <webElementGuid>3e3c4e39-7be3-47fd-ac4d-23408dacb084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedStart css-1ixds2g</value>
      <webElementGuid>a98eb021-989f-4e0a-8165-bef72ce4e7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>12f63455-94ec-42b7-832e-fd211e7790e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;balanceremaining&quot;)</value>
      <webElementGuid>e1c8582e-7d71-48fb-aac4-081adfba759f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='balanceremaining']</value>
      <webElementGuid>00d1f707-d2db-4428-978f-b94a119b60e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>bbc3d7ae-2fdb-4016-a55e-aefbb8dfa9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>c005b459-4cda-461d-ad4c-0090a36b3f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'balanceremaining' and @name = 'balanceRemaining' and @placeholder = '0' and @type = 'text']</value>
      <webElementGuid>be5cffdf-38dc-41c9-9900-b28221fad652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
