<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actual Hours IAO_iaoPreparing</name>
   <tag></tag>
   <elementGuidId>f676b617-bda6-4408-b62f-37ab3e811a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actualiaopreparing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actualiaopreparing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0152f9b1-1119-465b-aaaa-a1a1633f8d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f83af4b-5bf9-4ad4-a773-a2303fbf5c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actualiaopreparing</value>
      <webElementGuid>fb5bf39a-be54-4e10-a9d7-8aa1d4e63cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>iaoPreparing</value>
      <webElementGuid>884c8b09-ae22-432c-af1d-71fa89f72376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dc7c070a-8a10-4400-8c3b-44d280823a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>actualiaopreparing-label</value>
      <webElementGuid>6ff53326-9db2-4bf3-8c7e-679906311b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.25</value>
      <webElementGuid>50f55c62-cb4c-4744-bcc5-4e1e1f90ceca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8207afcd-8713-4377-94c2-2759c71f6d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input Mui-disabled MuiInputBase-inputAdornedEnd css-1uvydh2</value>
      <webElementGuid>079b803c-62fe-4b8a-a89c-8f5438a839aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>06bfc12f-c0e6-4708-9cfa-be45b32bc84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actualiaopreparing&quot;)</value>
      <webElementGuid>1b5f5619-d47c-4598-98b9-07eef5f53229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actualiaopreparing']</value>
      <webElementGuid>c5f02573-0e5c-421e-9608-8b742733df67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[3]/div[2]/div[2]/div/div/div/div/div[6]/div[3]/div/div/input</value>
      <webElementGuid>9133ce76-7bbe-4056-9f83-c62abf85d95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>2c370283-0ce7-44ff-b60a-dc0b2ccf5b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'actualiaopreparing' and @name = 'iaoPreparing' and @type = 'number']</value>
      <webElementGuid>afd07b79-873a-46eb-8c0c-faf14856dd31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
