<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Combined suggestions for futher clarifications_suggestions</name>
   <tag></tag>
   <elementGuidId>2c298d94-d583-4f05-b259-eed169e6eafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combinedsuggestions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='combinedsuggestions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>56a458b6-fdfd-48a6-b02b-a24bf8321de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fd76322b-3278-4985-9818-47f8438bf202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b7fc7dd2-07f5-4513-9799-64da2f2e5e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combinedsuggestions</value>
      <webElementGuid>cb074849-e166-40f4-82c2-56033370bea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>suggestions</value>
      <webElementGuid>386aeb82-a288-418b-bf9f-196ae577c6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputMultiline css-u36398</value>
      <webElementGuid>6a975a07-7e35-4e4f-a673-c8c1fbed7b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combinedsuggestions&quot;)</value>
      <webElementGuid>13412404-b78c-413d-b0d7-44c25df5b6b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='combinedsuggestions']</value>
      <webElementGuid>8521df83-ce21-4677-b2bb-ab44294ae46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[4]/div/div[2]/div/div/div/div/div/div/div/div/textarea</value>
      <webElementGuid>cff7fc6a-eb22-4b87-9bf5-8fa76ae9152b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>22bb368b-5e92-4dd0-a387-b09150089b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'combinedsuggestions' and @name = 'suggestions']</value>
      <webElementGuid>5d2cf438-c50c-4198-acb6-6c8b06902b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
