<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Watching Notifications</name>
   <tag></tag>
   <elementGuidId>d1aaa468-ddfc-46fd-a25d-c60660e4437e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uncontrolled-tab-example-tab-watch-request</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uncontrolled-tab-example-tab-watch-request']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f060a4ae-9b4c-47d0-babd-44d014326854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tab-watch-request</value>
      <webElementGuid>3c6c5a30-51b0-45ae-b0a2-97d170843059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>485025d9-96fc-493f-a354-857ed5d3666a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>39de63ba-8f02-45da-b549-98bd9ddc175e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>watch-request</value>
      <webElementGuid>e35ae3e9-e6ec-4fb5-9868-e3754dc21ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tabpane-watch-request</value>
      <webElementGuid>aaee84ab-7dfe-4b83-ba30-e6c3f41e1921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15dbcb62-63f1-4ce5-a836-dc96bc524e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link</value>
      <webElementGuid>5ab106a0-ff78-4266-bab5-f0fe03ef79a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watching Notifications</value>
      <webElementGuid>1cd434e8-84e5-489c-84ca-f432a6ce4fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uncontrolled-tab-example-tab-watch-request&quot;)</value>
      <webElementGuid>21aa0281-bd63-4d97-ba2d-af7005bba150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uncontrolled-tab-example-tab-watch-request']</value>
      <webElementGuid>8742fb5e-60fa-418f-b472-10b0281c294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup-2']/nav/a[2]</value>
      <webElementGuid>d70fbb34-0634-481e-95a9-60346a9f46d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Watching Notifications')]</value>
      <webElementGuid>74e5b8ff-7b7b-46be-a095-32ec99da7458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'uncontrolled-tab-example-tab-watch-request', '&quot;', ')')])[1]/following::a[2]</value>
      <webElementGuid>a005b393-4c52-4ed8-a590-45bfdae2c4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All Filters'])[1]/following::a[8]</value>
      <webElementGuid>8ae96e82-b247-4690-a668-e4a0c1c6ce94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dismiss All'])[1]/preceding::a[1]</value>
      <webElementGuid>76a20f8b-ef25-4d1b-b23e-b20c464a0e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Reply to a comment:'])[1]/preceding::a[1]</value>
      <webElementGuid>07e92966-f6f4-4b03-9749-c0e6af40026e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Watching Notifications']/parent::*</value>
      <webElementGuid>a24e6e45-920b-435a-a391-00875933bda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>eef02c45-0589-490e-b3f3-5d4d3a1f0746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>20caedf3-305a-4ff5-a2a7-f776861c77eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uncontrolled-tab-example-tab-watch-request' and @href = '#' and (text() = 'Watching Notifications' or . = 'Watching Notifications')]</value>
      <webElementGuid>e55a63b2-9954-482c-8ab6-ccf1d2d73899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
