<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_FOI</name>
   <tag></tag>
   <elementGuidId>937468f6-d8ef-4f59-82b3-6865e0781c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-home.foihomebtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/nav/div/div/div/div[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>da2654e5-518a-4584-8cc4-8090e6802033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home foihomebtn</value>
      <webElementGuid>2aba0bb4-166a-43d6-9aed-a42550e5207b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FOI</value>
      <webElementGuid>395640cf-085c-4862-b037-a822418b56e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[2]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-expand-sm navbar-dark bg-#036 fixed-top&quot;]/div[@class=&quot;MuiContainer-root foiContainer MuiContainer-maxWidthLg&quot;]/div[@class=&quot;ml-auto navbar-nav&quot;]/div[@class=&quot;col-md-12 col-sm-12&quot;]/div[@class=&quot;col-md-3 col-sm-4 foiheaderAppNamesection&quot;]/a[1]/i[@class=&quot;fa fa-home foihomebtn&quot;]</value>
      <webElementGuid>158b7cc6-4931-4281-bd99-826bf5e3df68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/nav/div/div/div/div[2]/a/i</value>
      <webElementGuid>61c7fbf8-c0d3-4b5b-a974-f63ed86dab85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>28f7d621-9a8a-4a70-9102-c2a6ee184fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'FOI' or . = 'FOI')]</value>
      <webElementGuid>799b7b06-609f-4890-a081-23478e40c2b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
