<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Intake Flex_fa fa-bell-o foi-bell</name>
   <tag></tag>
   <elementGuidId>087f4ab8-5ff5-4504-8f81-642c7afdd351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-bell-o.foi-bell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='responsive-navbar-nav']/div/div/ul/li[3]/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1992c174-952b-4679-ad04-b586dcd2192f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-bell-o foi-bell</value>
      <webElementGuid>50bd473f-3c77-4324-a4b4-e489de567ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsive-navbar-nav&quot;)/div[@class=&quot;ml-auto navbar-nav&quot;]/div[@class=&quot;ml-auto banner-right foihamburgermenu&quot;]/ul[@class=&quot;navbar-nav foihamburgermenulist&quot;]/li[@class=&quot;bell-icon foinavitem&quot;]/div[@class=&quot;drawer-div false&quot;]/span[@class=&quot;MuiBadge-root&quot;]/i[@class=&quot;fa fa-bell-o foi-bell&quot;]</value>
      <webElementGuid>d09db804-3f28-4e83-ba64-bcc83b85ed83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responsive-navbar-nav']/div/div/ul/li[3]/div/span/i</value>
      <webElementGuid>e0a8d13b-dd8d-4f00-ae98-e23ef6a0c58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>23af58d5-03bf-41e1-93f6-5a80357cf2dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
