<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create New CFR Form</name>
   <tag></tag>
   <elementGuidId>5772ca7d-a3a3-4b81-960f-153f5bd2eddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.col-lg-4.btn.btn-bottom.btn-cancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e34bc6e-88b7-49b9-a929-dba47f50b1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a498a96d-5b05-4f0b-a1ac-c78ae2691694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-lg-4 btn btn-bottom btn-cancel</value>
      <webElementGuid>3cb8ce28-5b9b-4ced-bda3-1ec3082f9e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Create New CFR Form</value>
      <webElementGuid>ef971a19-b385-4261-95ff-d68552b9a125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CFRForm&quot;)/div[@class=&quot;foi-review-container&quot;]/form[@class=&quot;MuiBox-root css-1cidgyh&quot;]/div[@class=&quot;foi-request-form&quot;]/div[@class=&quot;container foi-review-request-container cfrform-container&quot;]/div[@class=&quot;foi-bottom-button-group cfrform&quot;]/button[@class=&quot;col-lg-4 btn btn-bottom btn-cancel&quot;]</value>
      <webElementGuid>11bd2115-c68a-4d5c-a786-b322508dd1d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>a01e63d1-1427-4e4a-ab90-3d41fc47bb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CFRForm']/div/form/div/div[2]/div[5]/button[2]</value>
      <webElementGuid>a7bca21a-a6cf-4dc5-af43-44b4e8f90e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::button[1]</value>
      <webElementGuid>09ac1c79-6dac-4051-8112-df24d0436d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combined suggestions for futher clarifications'])[2]/following::button[2]</value>
      <webElementGuid>9ae8e94b-512e-4b94-8d78-c34109c4bc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request #ABC-2099-14102'])[1]/preceding::button[1]</value>
      <webElementGuid>6f9fa73d-d298-44b1-b9fb-4f22bd632a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add Attachment'])[1]/preceding::button[1]</value>
      <webElementGuid>3fd26044-1f8e-4052-ab08-bfb500ccc62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Create New CFR Form']/parent::*</value>
      <webElementGuid>6efeff2b-9a09-4438-bd69-1305c00e7a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f1836448-3c98-48fd-8011-52c07ed446cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+ Create New CFR Form' or . = '+ Create New CFR Form')]</value>
      <webElementGuid>20968179-1b2b-4db9-9721-6591828d5a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
