apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      API_DATABASE_URL: "${API_DATABASE_URL}"
      DEBUG: formio:*
      FFA_BPM_API_BASE: "${FFA_BPM_API_BASE}"
      FFA_BPM_CLIENT_ID: "${FFA_BPM_CLIENT_ID}"
      FFA_BPM_CLIENT_SECRET: "${FFA_BPM_CLIENT_SECRET}"
      FFA_BPM_TOKEN_API: "${FFA_BPM_TOKEN_API}"
      INSIGHT_API_KEY: "${INSIGHT_API_KEY}"
      INSIGHT_API_URL: "${INSIGHT_API_URL}"
      JWT_OIDC_ALGORITHMS: RS256
      JWT_OIDC_AUDIENCE: forms-flow-web
      JWT_OIDC_CACHING_ENABLED: "True"
      JWT_OIDC_ISSUER: "${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}"
      JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
      JWT_OIDC_JWKS_URI: "${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs"
      JWT_OIDC_WELL_KNOWN_CONFIG: "${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_URL: "${KEYCLOAK_URL}"
      MONGODB_URI: "${MONGODB_URI}"
      NODE_CONFIG: '{"mongo": "${MONGODB_URI}"}'
      FORMIO_JWT_SECRET: "${FORMIO_JWT_SECRET}"
      FORMIO_ROOT_EMAIL: "${FORMIO_ROOT_EMAIL}"
      FORMIO_ROOT_PASSWORD: "${FORMIO_ROOT_PASSWORD}"
      WEB_API_BASE_URL: "${WEB_API_BASE_URL}"
    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: false
    value: forms-flow-ai
  - name: API_DATABASE_URL
    description: API_DATABASE_URL
    required: false
  - name: FFA_BPM_API_BASE
    description: FFA_BPM_API_BASE
    required: true
  - name: FFA_BPM_CLIENT_ID
    description: FFA_BPM_CLIENT_ID
    required: true
  - name: FFA_BPM_CLIENT_SECRET
    description: FFA_BPM_CLIENT_SECRET
    required: true
  - name: FFA_BPM_TOKEN_API
    description: FFA_BPM_TOKEN_API
    required: true    
  - name: INSIGHT_API_KEY
    description: INSIGHT_API_KEY
    required: false
  - name: INSIGHT_API_URL
    description: INSIGHT_API_URL
    required: false
  - name: KEYCLOAK_URL
    displayName: KEYCLOAK_URL
    description: KEYCLOAK_URL
    required: true
  - name: KEYCLOAK_REALM
    displayName: KEYCLOAK_REALM
    description: KEYCLOAK_REALM
    required: true
  - name: MONGODB_URI
    description: MONGODB_URI
    required: true
  - name: FORMIO_JWT_SECRET
    description: FORMIO_JWT_SECRET
    required: true   
  - name: FORMIO_ROOT_EMAIL
    description: FORMIO_ROOT_EMAIL
    required: true
  - name: FORMIO_ROOT_PASSWORD
    description: FORMIO_ROOT_PASSWORD
    required: true
  - name: WEB_API_BASE_URL
    description: WEB_API_BASE_URL
    required: true
