const FOI_COMPONENT_CONSTANTS = {
    ASSIGNED_TO: "assignedTo",
    MINISTRY_ASSIGNED_TO: "ministryAssignedTo",
    APPLICANT_FIRST_NAME: "firstName",
    APPLICANT_LAST_NAME: "lastName",
    APPLICANT_MIDDLE_NAME: "middleName",
    FOI_CATEGORY: "category",
    FOI_SELECTED_CATEGORY: "selectedCategory",
    APPLICANT_EMAIL: "email",
    ORGANIZATION: "businessName",

    CHILD_FIRST_NAME: "childFirstName",
    CHILD_LAST_NAME: "childLastName",
    CHILD_MIDDLE_NAME: "childMiddleName",
    CHILD_NICKNAME: "childAlsoKnownAs",
    CHILD_DOB: "childBirthDate",

    ANOTHER_FIRST_NAME: "anotherFirstName",
    ANOTHER_LAST_NAME: "anotherLastName",
    ANOTHER_MIDDLE_NAME: "anotherMiddleName",
    ANOTHER_NICKNAME: "anotherAlsoKnownAs",
    ANOTHER_DOB: "anotherBirthDate",

    HOME_PHONE: "phonePrimary",
    MOBILE_PHONE: "phoneSecondary",
    WORK_PHONE_PRIMARY: "workPhonePrimary",
    WORK_PHONE_SECONDARY: "workPhoneSecondary",
    STREET_ADDRESS_PRIMARY: "address",
    STREET_ADDRESS_SECONDARY: "addressSecondary",
    CITY: "city",
    POSTALCODE: "postal",
    PROVINCE: "province",
    COUNTRY: "country",

    FROM_DATE: "fromDate",
    TO_DATE: "toDate",
    DESCRIPTION: "description",
    IS_PROGRAM_AREA_SELECTED: "isProgramAreaSelected",
    PROGRAM_AREA_LIST: "programAreaList",

    REQUEST_TYPE: "requestType",
    RECEIVED_MODE: "receivedMode",
    DELIVERY_MODE: "deliveryMode",
    RECEIVED_DATE: "receivedDate",
    RECEIVED_DATE_UF: "receivedDateUF",
    REQUEST_START_DATE: "requestStartDate",
    DUE_DATE: "dueDate",

    PERSONAL_HEALTH_NUMBER: "personalHealthNumber",
    CORRECTIONS_NUMBER: "correctionalServiceNumber",
    DOB: "birthDate",
    ALSO_KNOWN_AS: "alsoKnownAs",
    EMPLOYEE_NUMBER: "publicServiceEmployeeNumber",
    IDENTITY_VERIFIED: "identityVerified",

    REQUEST_TYPE_GENERAL: "general",
    REQUEST_TYPE_PERSONAL: "personal",
    CURRENT_STATE: "currentState",
    XGOVE: "xgov",
    ID_NUMBER: "idNumber",    
    SELECTED_MINISTRIES: "selectedMinistries",
    PROGRAM_AREA_CODE: "code",
    PROGRAM_AREA_NAME: "name",
    PROGRAM_AREA_SELECTED: "selected",
    ADDITIONAL_PERSONAL_INFORMATION: "additionalPersonalInfo",
    ADDREQUEST: "addrequest",
    RQUESTDETAILS_INITIALVALUES: "initialValues",
    ASSIGNEE_GROUPS: ["Intake Team", "Flex Team", "Processing Team"],
    ONLINE_FORM: "Online Form",
    ADD_REQUEST: "Add Request",
    REVIEW_REQUEST: "Review Request",
    ISPIIREDACTED:"ispiiredacted",
    DIVISION:"division",
    DIVISION_STAGE:"divisionStage",
    AXIS_REQUEST_ID:"axisRequestId",
    EAPPROVAL:"eApproval",
    DIVISION_DUE_DATE: "divisionDueDate",
    DIVISION_RECEIVED_DATE: "divisionReceivedDate",

    SUBJECT_CODE: "subjectCode",
    LINKED_REQUESTS: "linkedRequests"
  };
  
  export default FOI_COMPONENT_CONSTANTS;