<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Extended Due Days_numberDays</name>
   <tag></tag>
   <elementGuidId>1820cfc3-8ef6-4a2b-b956-45e339be3aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outlined-extension-number-days</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outlined-extension-number-days']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'outlined-extension-number-days' and @name = 'numberDays' and @type = 'number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2872cfd-066b-40f0-8028-dc39f738ce1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61f803c7-6465-4ec4-b504-ea50851cc90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-extension-number-days</value>
      <webElementGuid>bcd049f8-b64b-406c-b709-1d21ef21e9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberDays</value>
      <webElementGuid>d2cadb0c-9f7a-44f1-9514-712d2678b20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>98dd47b0-e5ea-4283-9482-8fe1a3f78492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0ced2a34-d52c-4ca1-afbd-d07ba5b1d8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ed1756a8-3786-4a1a-8aaf-db70c19f6f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd</value>
      <webElementGuid>9686fc14-16c4-4f3e-9783-0953f705f114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b37d0e6c-3374-4a71-9dba-e13e43e57c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-extension-number-days&quot;)</value>
      <webElementGuid>10247c14-f2c3-42cd-aed8-cd46fcdf0128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-extension-number-days']</value>
      <webElementGuid>3e1493de-1212-4930-b00c-07145cac6764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-extension-dialog']/div[3]/div/div[2]/div/div[5]/div/div/input</value>
      <webElementGuid>a352ad93-84ea-4b30-a4da-c4e6fcfb30d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/input</value>
      <webElementGuid>d27fbdee-f106-4382-b9f5-141cff2defdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-extension-number-days' and @name = 'numberDays' and @type = 'number']</value>
      <webElementGuid>50318134-66d4-4d50-a62b-517dfc11a43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
