<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approved Date_approvedDate</name>
   <tag></tag>
   <elementGuidId>26676082-a086-4a0c-8123-03f354220fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#approvedDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='approvedDate']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'approvedDate' and @type = 'date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c777a97-30cf-457e-a637-826847fd06af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8dadb31-a750-48b5-88d8-addb3f5d4c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approvedDate</value>
      <webElementGuid>37310818-a300-4eb1-842c-c194a915eaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>7874b43f-58e2-4ac8-bd10-188fa48382b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2023-04-21</value>
      <webElementGuid>a67e71f1-4102-4b3e-b9ba-0635eb4d8222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>approvedDate-label</value>
      <webElementGuid>f9595c48-310a-4b2b-a1ff-b342a9503afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>5e224f35-58b5-4724-94e0-7f66f841c587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-04-21</value>
      <webElementGuid>e50802d4-6188-45f2-9ae7-bbc452ac1301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approvedDate&quot;)</value>
      <webElementGuid>ac462167-6651-4855-b2f9-2ae0603f30b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='approvedDate']</value>
      <webElementGuid>a4b5ec1e-b7c0-4907-87c9-46dfb3d0c55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-extension-dialog']/div[3]/div/div[2]/div/div[9]/div/div/input</value>
      <webElementGuid>e9ee6a01-8010-4b9b-8cf3-3329fc75c4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>ab5a73fa-f948-4162-bd06-b2f7160d5280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'approvedDate' and @type = 'date']</value>
      <webElementGuid>4d3a8d07-f6ee-41b3-961d-ebfdb8e901e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
