<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pending_MuiButtonBase-root MuiIconButton-root jss166 MuiRadio-root</name>
   <tag></tag>
   <elementGuidId>0f943f1d-f731-4ebd-a5b5-7c08b5c05184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='status-options']/label[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;status-options&quot;)/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss166 MuiRadio-root&quot;][count(. | //*[@class = 'MuiButtonBase-root MuiIconButton-root jss166 MuiRadio-root']) = count(//*[@class = 'MuiButtonBase-root MuiIconButton-root jss166 MuiRadio-root'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2e9a105-f019-48eb-be9f-4946fcc54816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiIconButton-root jss166 MuiRadio-root</value>
      <webElementGuid>997ba327-2e9e-4ffa-9b7d-c2af245d0d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9aa1d315-13f8-4466-9df4-578f7b025b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status-options&quot;)/label[@class=&quot;MuiFormControlLabel-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss166 MuiRadio-root&quot;]</value>
      <webElementGuid>7de9a345-cd7e-4b4b-b9a7-105a72dad596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='status-options']/label[2]/span</value>
      <webElementGuid>af5f1663-d775-491b-a097-e1af0d77c50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::span[1]</value>
      <webElementGuid>e53450df-1dce-466f-acc4-52bfd075e232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extended Due Date'])[2]/following::span[5]</value>
      <webElementGuid>1497cbcf-366b-4441-827f-baa3303eea9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[2]/preceding::span[3]</value>
      <webElementGuid>3aca3177-ca1c-496c-926c-68711fac86e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denied'])[1]/preceding::span[7]</value>
      <webElementGuid>5ff83ec1-d4b8-4ab7-80a2-0fea145126e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>5bdca6b6-25e1-418d-a047-23f435ea2103</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
