const FOI_ACTION_CONSTANTS = {
  ERROR: "ERROR",
  IS_LOADING: "IS_LOADING",
  QUEUE_FILTER: "QUEUE_FILTER",
  QUEUE_PARAMS: "QUEUE_PARAMS",
  SHOW_ADVANCED_SEARCH: "SHOW_ADVANCED_SEARCH",
  FOI_ADVANCED_SEARCH_PARAMS: "FOI_ADVANCED_SEARCH_PARAMS",
  IS_ASSIGNEDTOLIST_LOADING: "IS_ASSIGNEDTOLIST_LOADING",
  IS_ATTACHMENTLIST_LOADING: "IS_ATTACHMENTLIST_LOADING",
  FOI_CATEGORYLIST: "FOI_CATEGORYLIST",
  FOI_COUNTRYLIST: "FOI_COUNTRYLIST",
  FOI_PROVINCELIST: "FOI_PROVINCELIST",
  FOI_REQUEST_TYPELIST: "FOI_REQUEST_TYPELIST",
  FOI_RECEIVED_MODELIST: "FOI_RECEIVED_MODELIST",
  FOI_DELIVERY_MODELIST: "FOI_DELIVERY_MODELIST",
  FOI_ASSIGNED_TOLIST: "FOI_ASSIGNED_TOLIST",
  FOI_PROCESSING_TEAM_LIST: "FOI_PROCESSING_TEAM_LIST",
  FOI_FULL_ASSIGNED_TOLIST: "FOI_FULL_ASSIGNED_TOLIST",
  FOI_MINISTRY_ASSIGNED_TOLIST: "FOI_MINISTRY_ASSIGNED_TOLIST",
  FOI_PROGRAM_AREALIST: "FOI_PROGRAM_AREALIST",

  FOI_LIST_REQUESTS: "FOI_LIST_REQUESTS",
  FOI_REQUESTS_COUNT: "FOI_REQUESTS_COUNT",

  FOI_REQUEST_DETAIL: "FOI_REQUEST_DETAIL",
  FOI_MINISTRYVIEW_REQUEST_DETAIL: "FOI_MINISTRYVIEW_REQUEST_DETAIL",
  CLEAR_REQUEST_DETAILS: "CLEAR_REQUEST_DETAILS",
  CLEAR_MINISTRYVIEWREQUEST_DETAILS: "CLEAR_MINISTRYVIEWREQUEST_DETAILS",
  FOI_REQUEST_DUE_DATE: "FOI_REQUEST_DUE_DATE",

  FOI_IS_REQUEST_UPDATED: "FOI_IS_REQUEST_UPDATED",
  FOI_REQUEST_DESCRIPTION_HISTORY: "FOI_REQUEST_DESCRIPTION_HISTORY",
  FOI_MINISTRY_REQUESTSLIST: "FOI_MINISTRY_REQUESTSLIST",
  FOI_MINISTRY_DIVISIONALSTAGES: "FOI_MINISTRY_DIVISIONALSTAGES",

  FOI_WATCHER_LIST: "FOI_WATCHER_LIST",

  CLOSING_REASONS: "CLOSING_REASONS",

  FOI_REQUEST_COMMENTS: "FOI_REQUEST_COMMENTS",

  FOI_REQUEST_ATTACHMENTS: "FOI_REQUEST_ATTACHMENTS",
  
  FOI_REQUEST_CFR_FORM: "FOI_REQUEST_CFR_FORM",
  FOI_REQUEST_CFR_FORM_HISTORY: "FOI_REQUEST_CFR_FORM_HISTORY",

  FOI_REQUEST_APPLICANT_CORRESPONDENCE: "FOI_REQUEST_APPLICANT_CORRESPONDENCE",
  FOI_REQUEST_APPLICANT_CORRESPONDENCE_TEMPLATES: "FOI_REQUEST_APPLICANT_CORRESPONDENCE_TEMPLATES",

  FOI_NOTIFICATIONS: "FOI_NOTIFICATIONS",
  FOI_REQUEST_EXTENSIONS: "FOI_REQUEST_EXTENSIONS",

  FOI_OPENED_MINISTRIES: "FOI_OPENED_MINISTRIES",

  FOI_AXIS_REQUEST_IDS: "FOI_AXIS_REQUEST_IDS",

  RESUME_DEFAULT_SORTING: "RESUME_DEFAULT_SORTING",
};
  
  export default FOI_ACTION_CONSTANTS;
  