<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_close dropdown</name>
   <tag></tag>
   <elementGuidId>ec5bdba9-9edc-41df-b1e3-008b2d6dd8d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;menu-&quot;)/div[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu- > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>600fdaba-5cc2-4f16-801b-3312e6b5556c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21b01b22-dcfd-45cc-a705-acd0019b67e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[1]</value>
      <webElementGuid>9fa4f367-15b0-4e9d-9832-e118dfe94db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div</value>
      <webElementGuid>c202970a-9dc0-4307-9a2e-20a6f32c5d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>e1cc2b12-5867-4926-bd8c-cbf71c36e8a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
