apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-usage-emails
  namespace: d7abee-dev
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: '0 0 1 * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: send-usage-emails
              image: image-registry.openshift-image-registry.svc:5000/d7abeez-tools/backup-to-s3:latest
              args:
          restartPolicy: OnFailure