<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IDIR</name>
   <tag></tag>
   <elementGuidId>0ebb7e1e-ff42-4946-af45-c865cec57bab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kc-social-providers']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zocial-idir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca79971d-c1d5-4b43-9cf5-6993b19af7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/realms/5k8dbl4h/broker/idir/login?client_id=forms-flow-web&amp;tab_id=RQXT3JxCjRU&amp;session_code=l_AcZmV-mxyKRUa3581fCsjJpZWO4OCep-_qxfYTRlQ</value>
      <webElementGuid>4a977537-c362-480e-804c-45bcb922b71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zocial-idir</value>
      <webElementGuid>7b97b013-fce1-403e-a2c1-bfa6c111f9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zocial keycloak-oidc</value>
      <webElementGuid>f8cde1a2-1aa6-41e4-a1aa-fa1c48c116ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> IDIR</value>
      <webElementGuid>b6e4bb5f-df7c-4c07-b293-8f06ddd78894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zocial-idir&quot;)</value>
      <webElementGuid>906bb9fd-cc28-4839-8c62-825d9571db47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='zocial-idir']</value>
      <webElementGuid>253dcfca-81f1-46a7-b871-f37779233587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-social-providers']/ul/li/a</value>
      <webElementGuid>cc2419e5-84ab-477b-9d48-755b4f9f7b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>8c047a7d-a484-40fd-a0e5-7eff1dc74049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username or email'])[1]/following::a[1]</value>
      <webElementGuid>f20bf999-be56-43a5-833a-620a17ed4f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub'])[1]/preceding::a[1]</value>
      <webElementGuid>0bf2da3f-45c2-4f4e-bbc6-5b42f39c775b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/realms/5k8dbl4h/broker/idir/login?client_id=forms-flow-web&amp;tab_id=RQXT3JxCjRU&amp;session_code=l_AcZmV-mxyKRUa3581fCsjJpZWO4OCep-_qxfYTRlQ')]</value>
      <webElementGuid>55fa76af-064d-40a2-bf0f-d7411e2a8aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>026a7807-0885-4ed5-bda6-a444205aa648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
