name: Forms-Flow-AI-Web CI


on:
  pull_request:
    branches:
      - dev
      - main
      - dev-marshal
      - test-marshal
      - dev-rook
      - test-rook
    paths:
      - "apps/forms-flow-ai/forms-flow-ai-web/**"
      - "!apps/forms-flow-ai/forms-flow-ai-web/src/forms/**"

defaults:
  run:
    shell: bash
    working-directory: ./apps/forms-flow-ai/forms-flow-ai-web

jobs:
  forms-flow-ai-web-docker-build-check:
    runs-on: ubuntu-20.04
    name: Build dockerfile to ensure it works

    steps:
      - uses: actions/checkout@v2
      - name: docker build to check strictness
        id: docker-build
        run: |
          docker build -f Dockerfile.local .

