name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    paths:
      - "apps/forms-flow-ai/forms-flow-ai-web/**"
      - ".github/workflows/forms-flow-ai-web-cd.yml"

defaults:
  run:
    shell: bash
    working-directory: ./apps/forms-flow-ai/forms-flow-ai-web
env:
  APP_NAME: "forms-flow-ai-web"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "forms-flow-ai-web"
    # if: github.event_name == 'push' && github.repository == 'bcgov/foi-flow' && github.ref_name == 'dev-DV-3160'
    # run: echo "github.ref_name name is ${{ github.ref_name }}"
    # env:
    #   APP_NAME: "forms-flow-ai-web"
    #   TAG_NAME: "dev"
    #   BRANCH_NAME: "dev"
    # if: github.event_name == 'push' && github.repository == 'bcgov/foi-flow' && github.ref_name == 'main'
    # run: echo "github.ref_name name is ${{ github.ref_name }}"
    # env:
    #   APP_NAME: "forms-flow-ai-web"
    #   TAG_NAME: "test"
    #   BRANCH_NAME: "main"
    if: github.event_name == 'push' && github.repository == 'bcgov/foi-flow'
    steps:
      - uses: actions/checkout@v2
      - name: Set test variable
        id: set-variable
        run: |
          if [ ${{ github.ref_name }} == 'dev' ]; then
            echo "For ${{ github.ref_name }} branch"
            echo "TOOLS_NAME=${{secrets.OPENSHIFT4_AI_FRONTEND_REPOSITORY}}" >> $GITHUB_ENV
            echo "TAG_NAME="dev"" >> $GITHUB_ENV
            echo "BRANCH_NAME="dev"" >> $GITHUB_ENV
          elif [ ${{ github.ref }} == 'dev-marshal' ]; then
            echo "For ${{ github.ref_name }} branch"
            echo "TOOLS_NAME=${{secrets.OPENSHIFT4_AI_FRONTEND_REPOSITORY}}" >> $GITHUB_ENV
            echo "TAG_NAME="dev"" >> $GITHUB_ENV
            echo "BRANCH_NAME="dev-marshal"" >> $GITHUB_ENV
          else
            echo "For ${{ github.ref_name }} branch"
          fi
        shell: bash
        #TOOLS_NAME=$secrets.OPENSHIFT4_AI_FRONTEND_REPOSITORY

        # if [ ${{ github.ref }} == 'refs/heads/dev-DV-3160' ]; then
        #     echo "IS dev-DV-3160 branch"
        #     echo "BRANCH_NAME='dev'
        #       TAG_NAME='dev'              
        #       " >> $GITHUB_ENV
        #   else
        #     echo "IS dev branch"
        #   fi


      # - name: check current branch is dev      
      #   if: github.ref_name == 'dev-DV-3160'
      #   env:
      #     APP_NAME: "forms-flow-ai-web"
      #     TAG_NAME: "dev"
      #     BRANCH_NAME: "dev-DV-3160"
      #   run: |
      #   echo "TOOLS_NAME=${{secrets.OPENSHIFT4_AI_FRONTEND_REPOSITORY}}" >> $GITHUB_ENV

      # - name: check current branch is dev-marshal
      #   if: github.ref_name == 'dev-marshal'
      #   env:
      #     APP_NAME: "forms-flow-ai-web-marshal"
      #     TAG_NAME: "dev-marshal"
      #     BRANCH_NAME: "dev-marshal"
      # #   run: |
      # #   echo "APP_NAME = forms-flow-ai-web
      # #   TAG_NAME = dev"
      #   run: echo "App name is ${{ env.APP_NAME }}, Branch name is ${{ env.BRANCH_NAME }}, Tag name is ${{ env.TAG_NAME }}"

      - name: print variables
        run: echo "App name is ${{ env.APP_NAME }}, Branch name is ${{ env.BRANCH_NAME }}, Tag name is ${{ env.TAG_NAME }}, Tools name is ${{env.TOOLS_NAME}}"
     