name: Katalon
on:
  push:
    branches: [ dev-NK-automationscripts ]
  # pull_request:
    # branches: [ dev ]

jobs:
  katalon-win:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.2.0'
          projectPath: '${{ github.workspace }}/testing/foi-qa-automation/foi-qa-automation.prj'
          args: '-noSplash -retry=0  -testSuitePath="Test Suites/foi-test-failure" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true -licenseRelease=true -browserType="Chrome" -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -executionProfile="dev" '
    - name: Archive Katalon report
      uses: actions/upload-artifact@v2
      with:
        name: katalon-report
        path: testing\foi-qa-automation\Reports\
        # D:\a\foi-flow\foi-flow\testing\foi-qa-automation\Reports\20220217_191948\foi-test-homepage-and-login\20220217_191954
  # katalon-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Katalon Studio Github Action
  #     uses: katalon-studio/katalon-studio-github-action@v2.1
  #     with:
  #         version: '7.5.5'
  #         projectPath: '${{ github.workspace }}'
  #         args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'


  ## TODO
  # Make sure license renewal / refresh is working
  # Run every single test (test suites stuff). How long?
  # Socialize impact with team
  # Delete this file when done - should be integrated in other files
  # Integrate into end of CD scripts, it's replacing manual regression testing
  # Mainly forms-flow-web-cd.yml - others? Ask team.