name: Katalon
on:
  schedule:
    - cron: "0 13 * * *"
  # push:
  #   branches: [ dev-NK-automationscripts ]
  # pull_request:
    # branches: [ dev ]

jobs:
  katalon-win:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0
      with:
        ref: dev-automationscripts
    - name: set screen resolution
	@@ -35,9 +35,9 @@ jobs:
            dir
      shell: cmd
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: '8.2.0'
          projectPath: '${{ github.workspace }}/testing/foi-qa-automation/foi-qa-automation.prj'
          args: '-noSplash -retry=0  -testSuiteCollectionPath="Test Suites/foi-test" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true -licenseRelease=true -browserType="Chrome" -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -executionProfile="dev" '
    - name: copy reports to one folder
	@@ -50,15 +50,15 @@ jobs:
            dir
      shell: cmd
    - name: Setup Node.js
      uses: actions/setup-node@v3.0
      with:
        node-version: '14'
    - name: Create collection report    
      run: |
            npm i -g xunit-viewer
            xunit-viewer -r  artifacts\JUnit_Report.xml -o artifacts\foi-test.html
    - name: Archive Katalon report
      uses: actions/upload-artifact@v3.0
      with:
        name: katalon-report
        path: artifacts
        # D:\a\foi-flow\foi-flow\testing\foi-qa-automation\Reports\20220217_191948\foi-test-homepage-and-login\20220217_191954
  # katalon-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Katalon Studio Github Action
  #     uses: katalon-studio/katalon-studio-github-action@v3.2.0
  #     with:
  #         version: '7.5.5'
  #         projectPath: '${{ github.workspace }}'
  #         args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
