name: Template API CI

on:
  pull_request:
    branches:
      - main
      - dev
      - dev-marshal
      - test-marshal
      - dev-rook
      - test-rook
    paths:
      - "integrationapi/MCS.FOI.Integration/**"

defaults:
  run:
    shell: bash
    working-directory: ./integrationapi/MCS.FOI.Integration

jobs:
  docker-build-check:
    runs-on: ubuntu-latest
    name: Build dockerfile to ensure it works

    steps:
    - uses: actions/checkout@v3

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: '8.0.x'

    - name: docker build to check strictness
      id: docker-build
      run: |
        docker build -f Dockerfile .
