kind: Template
apiVersion: v1
metadata:
  name: forms-flow-ai
  annotations:
    description: RocktChat Reggie Secrets
parameters:
  - name: API_DATABASE_URL
    displayName: API_DATABASE_URL
    description: The FF API URL  used by this application.
    required: true
  - name: FFA_BPM_API_BASE
    displayName: FFA_BPM_API_BASE
    description: CAMUNDA API URL - This is wil be from FOI FLOW.
    required: true
  - name: FFA_BPM_CLIENT_ID
    descripiton: CLIENT ID.
    displayName: FFA_BPM_CLIENT_ID
    required: true
  - name: FFA_BPM_CLIENT_SECRET
    displayName: FFA_BPM_CLIENT_SECRET
    descripiton: CAMUNDA CLIENT SECRET
    required: true
  - name: FFA_BPM_TOKEN_API
    display name: FFA_BPM_TOKEN_API
    description:
    required: true
  - name: INSIGHT_API_KEY
    display name: INSIGHT_API_KEY
    description:
    required: false
  - name: INSIGHT_API_URL
    display name: INSIGHT_API_URL
    description:
    required: true 
  - name: KEYCLOAK_URL
    display name: KEYCLOAK_URL
    description:
    required: true 
  - name: KEYCLOAK_REALM
    display name: KEYCLOAK_REALM
    description:
    required: true 
  - name: MONGODB_URI
    display name: MONGODB_URI
    description:
    required: true 
  - name: FORMIO_JWT_SECRET
    display name: FORMIO_JWT_SECRET
    description:
    required: true 
  - name: FORMIO_ROOT_EMAIL
    display name: FORMIO_ROOT_EMAIL
    description:
    required: true 
  - name: FORMIO_ROOT_PASSWORD
    display name: FORMIO_ROOT_PASSWORD
    description:
    required: true  
  - name: WEB_API_BASE_URL
    display name: WEB_API_BASE_URL
    description:
    required: true
  - name: DEBUG
    display name: DEBUG
    description:
    required: false 
  - name: NODE_CONFIG
    display name: NODE_CONFIG
    description:
    required: false
  - name: JWT_OIDC_ISSUER
    display name: JWT_OIDC_ISSUER
    description:
    required: false  
  - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
    display name: JWT_OIDC_JWKS_CACHE_TIMEOUT
    description:
    required: false  
  - name: JWT_OIDC_JWKS_URI
    display name: JWT_OIDC_JWKS_URI
    description:
    required: false 
  - name: JWT_OIDC_WELL_KNOWN_CONFIG
    display name: JWT_OIDC_WELL_KNOWN_CONFIG
    description:
    required: false 
  - name: JWT_OIDC_CACHING_ENABLED
    display name: JWT_OIDC_CACHING_ENABLED
    description:
    required: false
  - name: JWT_OIDC_ALGORITHMS
    display name: JWT_OIDC_ALGORITHMS
    description:
    required: false 
  - name: JWT_OIDC_AUDIENCE
    display name: JWT_OIDC_AUDIENCE
    description:
    required: false                                       
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: forms-flow-ai
      labels:
        app: forms-flow-ai
    stringData:
      API_DATABASE_URL: ${API_DATABASE_URL}
      FFA_BPM_API_BASE: ${FFA_BPM_API_BASE}
      FFA_BPM_CLIENT_ID: ${FFA_BPM_CLIENT_ID}
      FFA_BPM_CLIENT_SECRET: ${FFA_BPM_CLIENT_SECRET}
      FFA_BPM_TOKEN_API: ${FFA_BPM_TOKEN_API}
      INSIGHT_API_KEY: ${INSIGHT_API_KEY}
      INSIGHT_API_URL: ${INSIGHT_API_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      MONGODB_URI: ${MONGODB_URI}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET}
      FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL}
      FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD}
      WEB_API_BASE_URL: ${WEB_API_BASE_URL}
      DEBUG: ${DEBUG}
      NODE_CONFIG: ${NODE_CONFIG}
      JWT_OIDC_ISSUER: ${JWT_OIDC_ISSUER}
      JWT_OIDC_JWKS_CACHE_TIMEOUT: ${JWT_OIDC_JWKS_CACHE_TIMEOUT}
      JWT_OIDC_JWKS_URI: ${JWT_OIDC_JWKS_URI}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${JWT_OIDC_WELL_KNOWN_CONFIG}
      JWT_OIDC_CACHING_ENABLED: ${JWT_OIDC_CACHING_ENABLED}
      JWT_OIDC_ALGORITHMS: ${JWT_OIDC_ALGORITHMS}
      JWT_OIDC_AUDIENCE: ${JWT_OIDC_AUDIENCE}
