kind: Template
apiVersion: v1
metadata:
  name: api-creds
  annotations:
    description: RocktChat Reggie Secrets
parameters:
  - name: FOI_KC_CLIENTID
    displayName: FOI KC ClientID
    description: The SSO client ID used by this application.
    required: true
  - name: FOI_KC_SECRET
    displayName: FOI KC Secret
    description: The SSO secret used by this particular client.
    required: true
  - name: FOI_REQUEST_INBOX
    descripiton: The email address requests are sent to by the API.
    displayName: FOI Request Inbox
    required: true
  - name: FOI_KC_REALM
    displayName: FOI KC Realm
    descripiton: The name of the SSO realm.
    required: true
  - name: JWKS_URI
    display name: JWK URI
    description:
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: api-creds
      labels:
        app: foi-request-form
    stringData:
      FOI_KC_CLIENTID: ${FOI_KC_CLIENTID}
      FOI_KC_SECRET: ${FOI_KC_SECRET}
      FOI_REQUEST_INBOX: ${FOI_REQUEST_INBOX}
      FOI_KC_REALM: ${FOI_KC_REALM}
      JWKS_URI: ${JWKS_URI}